// biology_model.js - ለ Natural ዘርፍ የተዘጋጀ

if (typeof QUESTIONS_DB === 'undefined') { var QUESTIONS_DB = {}; }
if (!QUESTIONS_DB.ModelExams) QUESTIONS_DB.ModelExams = { Natural: {} };
if (!QUESTIONS_DB.ModelExams.Natural) QUESTIONS_DB.ModelExams.Natural = {};

// ባዮሎጂን በ Natural ስር መመደብ
QUESTIONS_DB.ModelExams.Natural.Biology = {
    "2017_Model": [
        { "q": "Which organelle is known as the powerhouse of the cell?", "opts": ["Nucleus", "Ribosome", "**Mitochondria**", "Golgi body"] },
        { "q": "The building blocks of proteins are:", "opts": ["Fatty acids", "**Amino acids**", "Nucleotides", "Monosaccharides"] },
        { "q": "What is the process by which plants make their own food?", "opts": ["Respiration", "**Photosynthesis**", "Transpiration", "Fermentation"] },
        { "q": "Which blood type is a universal recipient?", "opts": ["O-", "A+", "B-", "**AB+**"] },
        { "q": "The double helix structure of DNA was first described by:", "opts": ["Mendel", "Darwin", "**Watson and Crick**", "Pasteur"] },
        { "q": "Human somatic cells contain how many chromosomes?", "opts": ["23", "**46**", "44", "48"] },
        { "q": "Which hormone regulates blood sugar levels?", "opts": ["Adrenaline", "**Insulin**", "Thyroxine", "Estrogen"] },
        { "q": "The movement of water across a semi-permeable membrane is:", "opts": ["Diffusion", "**Osmosis**", "Active transport", "Endocytosis"] },
        { "q": "In an ecosystem, fungi and bacteria are usually:", "opts": ["Producers", "Consumers", "**Decomposers**", "Predators"] },
        { "q": "Which part of the brain controls balance and coordination?", "opts": ["Cerebrum", "**Cerebellum**", "Medulla", "Thalamus"] },
        { "q": "The study of heredity is known as:", "opts": ["Ecology", "**Genetics**", "Evolution", "Botany"] },
        { "q": "Which vitamin is synthesized when skin is exposed to sunlight?", "opts": ["Vitamin A", "Vitamin C", "**Vitamin D**", "Vitamin K"] },
        { "q": "A symbiotic relationship where both organisms benefit is:", "opts": ["Parasitism", "Commensalism", "**Mutualism**", "Competition"] },
        { "q": "The site of protein synthesis in a cell is the:", "opts": ["Nucleus", "**Ribosome**", "Lysosome", "Vacuole"] },
        { "q": "Which gas is released as a byproduct of photosynthesis?", "opts": ["Carbon dioxide", "**Oxygen**", "Nitrogen", "Methane"] },
        { "q": "The structural and functional unit of life is the:", "opts": ["Tissue", "Organ", "**Cell**", "Organism"] },
        { "q": "Who is known as the father of genetics?", "opts": ["Charles Darwin", "**Gregor Mendel**", "Louis Pasteur", "Lamarck"] },
        { "q": "Which human organ system is responsible for gas exchange?", "opts": ["Digestive", "**Respiratory**", "Circulatory", "Excretory"] },
        { "q": "The liquid part of the blood is called:", "opts": ["Hemoglobin", "**Plasma**", "Serum", "Platelet"] },
        { "q": "Which base is NOT found in DNA?", "opts": ["Adenine", "Guanine", "Cytosine", "**Uracil**"] },
        { "q": "The primary source of energy for all living things is:", "opts": ["ATP", "**The Sun**", "Plants", "Oxygen"] },
        { "q": "A group of similar cells performing a specific function is a:", "opts": ["Organ", "**Tissue**", "System", "Population"] },
        { "q": "Which of these is a biotic factor?", "opts": ["Temperature", "Water", "**Bacteria**", "pH level"] },
        { "q": "The process of cell division in body cells is called:", "opts": ["Meiosis", "**Mitosis**", "Budding", "Fission"] },
        { "q": "Which organ produces bile?", "opts": ["Stomach", "Pancreas", "**Liver**", "Gallbladder"] },
        { "q": "What is the main function of red blood cells?", "opts": ["Clotting", "Immunity", "**Oxygen transport**", "Hormone production"] },
        { "q": "Which kingdom includes organisms like mushrooms?", "opts": ["Plantae", "Animalia", "**Fungi**", "Protista"] },
        { "q": "The 'master gland' of the endocrine system is:", "opts": ["Thyroid", "Adrenal", "**Pituitary**", "Pancreas"] },
        { "q": "What is the genetic material in most viruses?", "opts": ["Proteins", "**DNA or RNA**", "Lipids", "Carbohydrates"] },
        { "q": "Which process converts glucose into energy in cells?", "opts": ["Photosynthesis", "**Cellular Respiration**", "Digestion", "Absorption"] },
        { "q": "Which of these is a non-renewable resource?", "opts": ["Sunlight", "Wind", "**Fossil Fuels**", "Water"] },
        { "q": "The flap that prevents food from entering the windpipe is:", "opts": ["Pharynx", "**Epiglottis**", "Larynx", "Esophagus"] },
        { "q": "The small air sacs in the lungs where gas exchange occurs are:", "opts": ["Bronchi", "Bronchioles", "**Alveoli**", "Trachea"] },
        { "q": "Which part of the flower receives pollen during pollination?", "opts": ["Anther", "Filament", "**Stigma**", "Style"] },
        { "q": "The basic unit of the nervous system is the:", "opts": ["Nephron", "**Neuron**", "Axon", "Dendrite"] },
        { "q": "Which organ filters waste from the blood to form urine?", "opts": ["Liver", "**Kidney**", "Bladder", "Spleen"] },
        { "q": "What type of blood vessel carries blood away from the heart?", "opts": ["Vein", "Capillary", "**Artery**", "Venule"] },
        { "q": "Which instrument is used to see microscopic organisms?", "opts": ["Telescope", "**Microscope**", "Stethoscope", "Periscope"] },
        { "q": "What is the study of interaction between organisms and environment?", "opts": ["Genetics", "**Ecology**", "Zoology", "Evolution"] },
        { "q": "Which carbohydrate is stored in the liver of animals?", "opts": ["Starch", "Cellulose", "**Glycogen**", "Sucrose"] },
        { "q": "The change in inherited characteristics over time is:", "opts": ["Mutation", "Adaptation", "**Evolution**", "Selection"] },
        { "q": "Which of these is a cold-blooded animal?", "opts": ["Bird", "Mammal", "**Reptile**", "Human"] },
        { "q": "What is the largest organ of the human body?", "opts": ["Liver", "Brain", "**Skin**", "Lungs"] },
        { "q": "Which mineral is essential for healthy bones and teeth?", "opts": ["Iron", "**Calcium**", "Iodine", "Sodium"] },
        { "q": "The process of maintaining a stable internal environment is:", "opts": ["Metabolism", "Growth", "**Homeostasis**", "Reproduction"] },
        { "q": "Which part of a plant cell provides structural support?", "opts": ["Cytoplasm", "Cell Membrane", "**Cell Wall**", "Nucleus"] },
        { "q": "What is the normal body temperature of a human in Celsius?", "opts": ["35°C", "**37°C**", "39°C", "41°C"] },
        { "q": "Which acid is found in the human stomach?", "opts": ["Sulfuric", "Nitric", "**Hydrochloric**", "Acetic"] },
        { "q": "The movement of molecules from high to low concentration is:", "opts": ["Osmosis", "**Diffusion**", "Active transport", "Endocytosis"] },
        { "q": "Which vitamin helps in blood clotting?", "opts": ["Vitamin A", "Vitamin B", "Vitamin C", "**Vitamin K**"] },
        { "q": "What is the most common gas in the Earth's atmosphere?", "opts": ["Oxygen", "**Nitrogen**", "Carbon dioxide", "Argon"] },
        { "q": "Which organelle contains digestive enzymes to break down waste?", "opts": ["Vacuole", "**Lysosome**", "Ribosome", "Nucleus"] },
        { "q": "The chemical used to test for the presence of starch is:", "opts": ["Benedict's", "**Iodine**", "Biuret", "Ethanol"] },
        { "q": "Which part of the eye controls the amount of light entering?", "opts": ["Retina", "Cornea", "**Iris**", "Lens"] },
        { "q": "A sudden change in the DNA sequence is called a:", "opts": ["Evolution", "**Mutation**", "Speciation", "Variation"] },
        { "q": "Which of these is a viral disease?", "opts": ["Malaria", "Tuberculosis", "**AIDS**", "Cholera"] },
        { "q": "The heart has how many chambers?", "opts": ["2", "3", "**4**", "5"] },
        { "q": "Which scientist developed the theory of natural selection?", "opts": ["Mendel", "**Charles Darwin**", "Hooke", "Linnaeus"] },
        { "q": "What is the main source of vitamin C?", "opts": ["Meat", "Eggs", "**Citrus fruits**", "Bread"] },
        { "q": "The joint at the elbow is an example of a:", "opts": ["Ball and socket", "**Hinge joint**", "Pivot joint", "Fixed joint"] },
        { "q": "Which part of the blood helps in fighting infections?", "opts": ["Red cells", "**White cells**", "Plasma", "Platelets"] },
        { "q": "The green pigment in plants is called:", "opts": ["Carotene", "**Chlorophyll**", "Xanthophyll", "Melanin"] },
        { "q": "In humans, fertilization usually occurs in the:", "opts": ["Ovary", "**Fallopian tube**", "Uterus", "Vagina"] },
        { "q": "Which organ stores bile?", "opts": ["Liver", "Pancreas", "**Gallbladder**", "Stomach"] },
        { "q": "The functional unit of the kidney is the:", "opts": ["Neuron", "**Nephron**", "Alveoli", "Villi"] },
        { "q": "Which of these is a decomposer?", "opts": ["Grass", "Lion", "**Mushroom**", "Rabbit"] },
        { "q": "The 'S' shape of the human spine is called the:", "opts": ["Cervical", "Thoracic", "**Vertebral column**", "Sacrum"] },
        { "q": "Which gas is needed by plants for photosynthesis?", "opts": ["Oxygen", "**Carbon dioxide**", "Nitrogen", "Hydrogen"] },
        { "q": "A baby develops inside the mother's:", "opts": ["Ovary", "**Uterus**", "Bladder", "Stomach"] },
        { "q": "The study of fossils is called:", "opts": ["Biology", "Geology", "**Paleontology**", "Archaeology"] },
        { "q": "Which part of the brain is responsible for thinking?", "opts": ["Cerebellum", "**Cerebrum**", "Medulla", "Brainstem"] },
        { "q": "The hard outer covering of an insect is an:", "opts": ["Endoskeleton", "**Exoskeleton**", "Shell", "Skin"] },
        { "q": "Which blood vessel has the thinnest walls?", "opts": ["Artery", "Vein", "**Capillary**", "Aorta"] },
        { "q": "What is the primary function of leaves?", "opts": ["Support", "**Photosynthesis**", "Absorption", "Reproduction"] },
        { "q": "Which disease is caused by lack of Vitamin D?", "opts": ["Scurvy", "Beriberi", "**Rickets**", "Anemia"] },
        { "q": "The universal currency of energy in cells is:", "opts": ["Glucose", "DNA", "**ATP**", "RNA"] },
        { "q": "What type of reproduction involves only one parent?", "opts": ["Sexual", "**Asexual**", "Internal", "External"] },
        { "q": "Which of these is a greenhouse gas?", "opts": ["Oxygen", "Nitrogen", "**Methane**", "Helium"] },
        { "q": "The place where an organism lives is its:", "opts": ["Niche", "**Habitat**", "Community", "Biome"] },
        { "q": "Which part of the tooth is the hardest?", "opts": ["Dentin", "Pulp", "**Enamel**", "Cementum"] },
        { "q": "Which hormone is known as the 'fight or flight' hormone?", "opts": ["Insulin", "Thyroxine", "**Adrenaline**", "Estrogen"] },
        { "q": "What is the male gamete in plants?", "opts": ["Ovule", "**Pollen**", "Seed", "Fruit"] },
        { "q": "Which of these is a flightless bird?", "opts": ["Eagle", "Sparrow", "**Ostrich**", "Hawk"] },
        { "q": "The process of liquid changing into gas is:", "opts": ["Condensation", "**Evaporation**", "Melting", "Freezing"] },
        { "q": "Which part of the ear is responsible for balance?", "opts": ["Eardrum", "Cochlea", "**Semicircular canals**", "Ossicles"] },
        { "q": "What is the main function of the large intestine?", "opts": ["Digestion", "**Water absorption**", "Protein breakdown", "Bile storage"] },
        { "q": "A person who studies plants is a:", "opts": ["Zoologist", "**Botanist**", "Ecologist", "Geneticist"] },
        { "q": "Which layer of the Earth supports life?", "opts": ["Core", "Mantle", "**Crust**", "Atmosphere"] },
        { "q": "What is the basic unit of classification?", "opts": ["Genus", "Family", "**Species**", "Kingdom"] },
        { "q": "Which food group provides quick energy?", "opts": ["Proteins", "Fats", "**Carbohydrates**", "Vitamins"] },
        { "q": "The tiny pores on the surface of leaves are:", "opts": ["Villi", "**Stomata**", "Alveoli", "Pores"] },
        { "q": "Which organ system protects internal organs?", "opts": ["Muscular", "**Skeletal**", "Digestive", "Nervous"] },
        { "q": "What is the lifespan of a red blood cell?", "opts": ["10 days", "30 days", "**120 days**", "1 year"] },
        { "q": "Which vitamin is found in oranges?", "opts": ["Vitamin A", "Vitamin B", "**Vitamin C**", "Vitamin D"] },
        { "q": "The process of a seed growing into a plant is:", "opts": ["Pollination", "Fertilization", "**Germination**", "Dispersal"] },
        { "q": "Which of these is a producer in a pond?", "opts": ["Fish", "Frog", "**Algae**", "Snail"] },
        { "q": "How many lungs does a human have?", "opts": ["1", "**2**", "3", "4"] },
        { "q": "Which part of the cell contains genetic information?", "opts": ["Cytoplasm", "Cell wall", "**Nucleus**", "Ribosome"] },
        { "q": "What is the function of the heart?", "opts": ["Breathing", "**Pumping blood**", "Digestion", "Thinking"] },
        { "q": "Which organ is used for tasting?", "opts": ["Nose", "**Tongue**", "Skin", "Ear"] }
    ]
};
