// biology.js - Natural Science Biology Questions (2010 - 2017)

// --- 2010 E.C ---
QUESTIONS_DB.Natural.Biology["2010"] = [{ q: "Which of the following is a characteristic of all living things?", opts: ["Locomotion", "**Metabolism**", "Photosynthesis", "Multicellularity"] },
    { q: "The cell organelle responsible for protein synthesis is:", opts: ["Nucleus", "Mitochondria", "**Ribosome**", "Golgi body"] },
    { q: "Which of the following is a prokaryotic organism?", opts: ["Amoeba", "Yeast", "**Bacteria**", "Mushroom"] },
    { q: "The movement of water molecules from high to low concentration through a membrane is:", opts: ["Diffusion", "**Osmosis**", "Active transport", "Endocytosis"] },
    { q: "Which molecule is known as the 'energy currency' of the cell?", opts: ["DNA", "Glucose", "**ATP**", "RNA"] },
    { q: "The process by which green plants make their own food is:", opts: ["Respiration", "**Photosynthesis**", "Digestion", "Fermentation"] },
    { q: "Which of these is a biotic component of an ecosystem?", opts: ["Soil", "Water", "Sunlight", "**Plants**"] },
    { q: "The heredity units passed from parents to offspring are:", opts: ["Chromosomes", "**Genes**", "Proteins", "Cells"] },
    { q: "Human somatic cells contain how many chromosomes?", opts: ["23", "**46**", "44", "48"] },
    { q: "Which enzyme starts the digestion of carbohydrates in the mouth?", opts: ["Pepsin", "Lipase", "**Amylase**", "Trypsin"] },
    { q: "The main function of white blood cells is:", opts: ["Oxygen transport", "Blood clotting", "**Fighting infections**", "Nutrient transport"] },
    { q: "Which part of the brain controls balance and coordination?", opts: ["Cerebrum", "**Cerebellum**", "Medulla", "Thalamus"] },
    { q: "The structural and functional unit of the kidney is:", opts: ["Neuron", "**Nephron**", "Alveoli", "Villi"] },
    { q: "Which hormone regulates blood sugar levels?", opts: ["Adrenaline", "Thyroxine", "**Insulin**", "Estrogen"] },
    { q: "In DNA, Adenine always pairs with:", opts: ["Guanine", "Cytosine", "**Thymine**", "Uracil"] },
    { q: "Which of the following is a viral disease?", opts: ["Tuberculosis", "Malaria", "**AIDS**", "Cholera"] },
    { q: "The study of interactions between organisms and their environment is:", opts: ["Genetics", "**Ecology**", "Evolution", "Taxonomy"] },
    { q: "Which blood group is known as the universal donor?", opts: ["A", "B", "AB", "**O**"] },
    { q: "The phase of mitosis where chromosomes line up at the center is:", opts: ["Prophase", "**Metaphase**", "Anaphase", "Telophase"] },
    { q: "Which vitamin is synthesized by the skin in sunlight?", opts: ["Vitamin A", "Vitamin B", "Vitamin C", "**Vitamin D**"] },
    { q: "The gas exchange in humans occurs in the:", opts: ["Trachea", "Bronchi", "**Alveoli**", "Larynx"] },
    { q: "Which of the following is a primary consumer?", opts: ["Lion", "**Grasshopper**", "Green plant", "Fungi"] },
    { q: "The genetic makeup of an organism is called its:", opts: ["Phenotype", "**Genotype**", "Allele", "Mutation"] },
    { q: "Which organ produces bile?", opts: ["Stomach", "Pancreas", "**Liver**", "Gallbladder"] },
    { q: "The theory of natural selection was proposed by:", opts: ["Gregor Mendel", "**Charles Darwin**", "Louis Pasteur", "Robert Hooke"] },
    { q: "Which mineral is essential for bone and teeth formation?", opts: ["Iron", "Iodine", "**Calcium**", "Sodium"] },
    { q: "The asexual reproduction method in yeast is:", opts: ["Fragmentation", "**Budding**", "Spore formation", "Binary fission"] },
    { q: "Which of the following is a complex carbohydrate?", opts: ["Glucose", "Fructose", "**Starch**", "Sucrose"] },
    { q: "The site of aerobic respiration in a cell is:", opts: ["Chloroplast", "**Mitochondria**", "Vacuole", "Lysosome"] },
    { q: "Which instrument is used to see microscopic organisms?", opts: ["Telescope", "Periscope", "**Microscope**", "Stethoscope"] },
    { q: "The male reproductive part of a flower is the:", opts: ["Pistil", "**Stamen**", "Petal", "Sepal"] },
    { q: "Which deficiency cause Scurvy?", opts: ["Vitamin A", "Vitamin B1", "**Vitamin C**", "Vitamin D"] },
    { q: "The 'Master Gland' of the endocrine system is:", opts: ["Thyroid", "Adrenal", "**Pituitary**", "Pancreas"] },
    { q: "Which of the following is NOT a kingdom of life?", opts: ["Monera", "Protista", "Fungi", "**Mammalia**"] },
    { q: "The protein that carries oxygen in the blood is:", opts: ["Insulin", "**Hemoglobin**", "Antibody", "Collagen"] },
    { q: "The process of maintaining a stable internal environment is:", opts: ["Evolution", "**Homeostasis**", "Adaptation", "Succession"] },
    { q: "Which of the following is a decomposer?", opts: ["Eagle", "Snake", "**Bacteria**", "Rabbit"] },
    { q: "The long extension of a neuron that carries impulses is:", opts: ["Dendrite", "**Axon**", "Synapse", "Cell body"] },
    { q: "Which part of the leaf regulates gas exchange?", opts: ["Xylem", "Phloem", "**Stomata**", "Cuticle"] },
    { q: "The first person to observe 'cells' under a microscope was:", opts: ["Anton van Leeuwenhoek", "**Robert Hooke**", "Rudolf Virchow", "Theodor Schwann"] },
    { q: "Which organelle is often called the 'suicide bag' of the cell?", opts: ["Ribosome", "Centrosome", "**Lysosome**", "Nucleolus"] },
    { q: "A relationship where both organisms benefit is called:", opts: ["Parasitism", "Commensalism", "**Mutualism**", "Competition"] },
    { q: "Which nitrogenous base is found in RNA but not in DNA?", opts: ["Thymine", "Adenine", "**Uracil**", "Cytosine"] },
    { q: "The functional unit of heredity is:", opts: ["DNA", "**Gene**", "Nucleotide", "Protein"] },
    { q: "Which structure prevents food from entering the windpipe?", opts: ["Pharynx", "**Epiglottis**", "Esophagus", "Uvula"] },
    { q: "The study of fungi is called:", opts: ["Phycology", "**Mycology**", "Virology", "Bacteriology"] },
    { q: "Which of the following is a non-communicable disease?", opts: ["Flu", "Typhoid", "**Diabetes**", "Tuberculosis"] },
    { q: "The largest organ of the human body is the:", opts: ["Liver", "Brain", "**Skin**", "Small Intestine"] },
    { q: "Which process results in two identical daughter cells?", opts: ["Meiosis", "**Mitosis**", "Fertilization", "Pollination"] },
    { q: "The target for the Ethiopian Coders program you joined is:", opts: ["Web Design", "**Ethical Hacker**", "Data Science", "AI"] }
    // { q: "ጥያቄ", opts: ["A", "B", "C", "D"] },
];

// --- 2011 E.C ---
QUESTIONS_DB.Natural.Biology["2011"] = [{ q: "Which branch of biology deals with the study of heredity?", opts: ["Ecology", "**Genetics**", "Taxonomy", "Cytology"] },
    { q: "The basic structural unit of all living organisms is the:", opts: ["Tissue", "Organ", "**Cell**", "System"] },
    { q: "Which organelle is known as the powerhouse of the cell?", opts: ["Nucleus", "**Mitochondria**", "Ribosome", "Chloroplast"] },
    { q: "The process by which cells divide to produce gametes is:", opts: ["Mitosis", "**Meiosis**", "Fission", "Budding"] },
    { q: "Which of the following is a function of the liver?", opts: ["Insulin production", "**Bile production**", "Urine storage", "Oxygen transport"] },
    { q: "The kingdom that includes multicellular decomposers is:", opts: ["Plantae", "Animalia", "**Fungi**", "Protista"] },
    { q: "Which gas is released as a byproduct of photosynthesis?", opts: ["Carbon dioxide", "**Oxygen**", "Nitrogen", "Methane"] },
    { q: "The heart chamber that pumps blood to the entire body is the:", opts: ["Right atrium", "Left atrium", "Right ventricle", "**Left ventricle**"] },
    { q: "A permanent change in the DNA sequence is called a:", opts: ["Selection", "Adaptation", "**Mutation**", "Evolution"] },
    { q: "Which vitamin deficiency leads to Rickets?", opts: ["Vitamin A", "Vitamin C", "**Vitamin D**", "Vitamin K"] },
    { q: "The movement of molecules from an area of high to low concentration is:", opts: ["**Diffusion**", "Osmosis", "Active transport", "Phagocytosis"] },
    { q: "Which of the following is an abiotic factor in an ecosystem?", opts: ["Bacteria", "Plants", "**Temperature**", "Animals"] },
    { q: "The main site of lipid synthesis in the cell is the:", opts: ["Rough ER", "**Smooth ER**", "Lysosome", "Nucleus"] },
    { q: "In humans, fertilization usually occurs in the:", opts: ["Uterus", "**Fallopian tube**", "Ovary", "Cervix"] },
    { q: "Which scientist is known as the father of modern genetics?", opts: ["Charles Darwin", "**Gregor Mendel**", "Louis Pasteur", "Robert Koch"] },
    { q: "The part of the flower that develops into a fruit is the:", opts: ["Stigma", "Style", "**Ovary**", "Ovule"] },
    { q: "Which blood cells are responsible for carrying oxygen?", opts: ["**Red blood cells**", "White blood cells", "Platelets", "Plasma"] },
    { q: "The process of maintaining a stable internal environment is:", opts: ["Metabolism", "**Homeostasis**", "Excretion", "Irritability"] },
    { q: "Which sugar is found in DNA?", opts: ["Ribose", "**Deoxyribose**", "Glucose", "Fructose"] },
    { q: "The smallest unit of an element that maintains its properties is the:", opts: ["Molecule", "Compound", "**Atom**", "Cell"] },
    { q: "Which organ is responsible for filtering waste from the blood?", opts: ["Heart", "**Kidney**", "Lungs", "Stomach"] },
    { q: "The structural carbohydrate found in plant cell walls is:", opts: ["Glycogen", "Starch", "**Cellulose**", "Chitin"] },
    { q: "Which hormone is produced by the pancreas to lower blood glucose?", opts: ["Glucagon", "**Insulin**", "Adrenaline", "Thyroxine"] },
    { q: "The first stage of cellular respiration is:", opts: ["Krebs cycle", "Electron transport", "**Glycolysis**", "Fermentation"] },
    { q: "Which of the following is a primary producer?", opts: ["Cow", "Lion", "**Grass**", "Eagle"] },
    { q: "The study of the relationship between organisms and their environment is:", opts: ["**Ecology**", "Anatomy", "Physiology", "Embryology"] },
    { q: "Which part of the human eye contains light-sensitive cells?", opts: ["Cornea", "Iris", "**Retina**", "Lens"] },
    { q: "Bacteria reproduce asexually by a process called:", opts: ["Budding", "**Binary fission**", "Sporulation", "Fragmentation"] },
    { q: "The enzyme found in saliva that breaks down starch is:", opts: ["Pepsin", "Lipase", "**Amylase**", "Maltase"] },
    { q: "Which of the following is a non-vascular plant?", opts: ["Fern", "Pine", "**Moss**", "Rose"] },
    { q: "The total number of ATP molecules produced in aerobic respiration is:", opts: ["2", "4", "**36-38**", "100"] },
    { q: "Which type of RNA carries the genetic code to the ribosome?", opts: ["tRNA", "rRNA", "**mRNA**", "snRNA"] },
    { q: "The physical appearance of an organism is its:", opts: ["Genotype", "**Phenotype**", "Allele", "Locus"] },
    { q: "Which of the following is a vector for malaria?", opts: ["Housefly", "**Female Anopheles mosquito**", "Tsetse fly", "Rat"] },
    { q: "The main organ for gas exchange in fish is the:", opts: ["Skin", "Lungs", "**Gills**", "Trachea"] },
    { q: "Which law states that alleles segregate during gamete formation?", opts: ["Law of Dominance", "**Law of Segregation**", "Law of Independent Assortment", "Law of Linkage"] },
    { q: "The protective outer layer of a leaf is the:", opts: ["Mesophyll", "**Epidermis**", "Xylem", "Phloem"] },
    { q: "Which of the following is a viral disease?", opts: ["Tuberculosis", "Syphilis", "**Hepatitis B**", "Anthrax"] },
    { q: "The junction between two neurons is called a:", opts: ["Dendrite", "Axon", "**Synapse**", "Node"] },
    { q: "Which process creates identical copies of DNA?", opts: ["Transcription", "Translation", "**Replication**", "Splicing"] },
    { q: "The theory of evolution by natural selection was proposed by:", opts: ["Lamarck", "**Charles Darwin**", "Wallace", "Mendel"] },
    { q: "Which organelle is responsible for intracellular digestion?", opts: ["Ribosome", "Vacuole", "**Lysosome**", "Peroxisome"] },
    { q: "The process of converting atmospheric nitrogen into a usable form is:", opts: ["Denitrification", "**Nitrogen fixation**", "Nitrification", "Ammonification"] },
    { q: "Which part of the brain is responsible for high-level thinking?", opts: ["Cerebellum", "**Cerebrum**", "Medulla", "Hypothalamus"] },
    { q: "Plants that lose their leaves annually are called:", opts: ["Evergreen", "**Deciduous**", "Annuals", "Perennials"] },
    { q: "The blood vessel that carries deoxygenated blood to the lungs is the:", opts: ["Aorta", "Vena cava", "**Pulmonary artery**", "Pulmonary vein"] },
    { q: "Which nitrogenous base is NOT found in DNA?", opts: ["Adenine", "Thymine", "Guanine", "**Uracil**"] },
    { q: "The structural unit of the nervous system is the:", opts: ["Nephron", "**Neuron**", "Alveolus", "Myofibril"] },
    { q: "Which of the following is a polysaccharide stored in animals?", opts: ["Starch", "Cellulose", "**Glycogen**", "Sucrose"] },
    { q: "The removal of metabolic waste from the body is:", opts: ["Defecation", "**Excretion**", "Secretion", "Digestion"] },
    { q: "Which kingdom includes organisms that can live in extreme environments?", opts: ["**Archaebacteria**", "Eubacteria", "Protista", "Fungi"] },
    { q: "The type of bond that holds amino acids together in a protein is:", opts: ["Ionic bond", "Hydrogen bond", "**Peptide bond**", "Glycosidic bond"] },
    { q: "Which organ stores bile until it is needed for digestion?", opts: ["Liver", "Pancreas", "**Gallbladder**", "Stomach"] },
    { q: "The study of cells is known as:", opts: ["Histology", "**Cytology**", "Genetics", "Microbiology"] },
    { q: "Which of the following is a renewable resource?", opts: ["Coal", "Oil", "**Solar energy**", "Natural gas"] },
    { q: "The light-dependent reactions of photosynthesis occur in the:", opts: ["Stroma", "**Thylakoid membrane**", "Cytoplasm", "Mitochondria"] },
    { q: "In humans, the sex of the offspring is determined by the:", opts: ["Mother", "**Father**", "Both parents", "Environment"] },
    { q: "Which of the following is a greenhouse gas?", opts: ["Oxygen", "Nitrogen", "**Carbon dioxide**", "Argon"] },
    { q: "The process by which plants lose water vapor through their leaves is:", opts: ["Evaporation", "**Transpiration**", "Guttation", "Respiration"] },
    { q: "Which part of the skeleton protects the brain?", opts: ["Ribcage", "Pelvis", "**Skull**", "Vertebrae"] },
    { q: "An organism that eats both plants and animals is an:", opts: ["Herbivore", "Carnivore", "**Omnivore**", "Detritivore"] },
    { q: "Which enzyme breaks down proteins in the stomach?", opts: ["Amylase", "**Pepsin**", "Lipase", "Trypsin"] },
    { q: "The genetic material of a virus is wrapped in a protein coat called a:", opts: ["Envelope", "**Capsid**", "Cell wall", "Nucleus"] },
    { q: "Which of the following is a function of the skeletal system?", opts: ["Digestion", "Hormone production", "**Blood cell formation**", "Nerve conduction"] },
    { q: "The movement of water through a semi-permeable membrane is:", opts: ["Diffusion", "**Osmosis**", "Active transport", "Endocytosis"] },
    { q: "Which hormone is responsible for the 'fight or flight' response?", opts: ["Insulin", "Thyroxine", "**Adrenaline**", "Estrogen"] },
    { q: "The most specific level of biological classification is:", opts: ["Kingdom", "Phylum", "Genus", "**Species**"] },
    { q: "Which of the following is a characteristic of enzymes?", opts: ["Consumed in reactions", "**Highly specific**", "Slow down reactions", "Made of lipids"] },
    { q: "The part of the eye that controls the amount of light entering is the:", opts: ["Retina", "**Iris**", "Lens", "Sclera"] },
    { q: "Which vitamin is essential for blood clotting?", opts: ["Vitamin A", "Vitamin C", "Vitamin E", "**Vitamin K**"] },
    { q: "The production of offspring without the fusion of gametes is:", opts: ["Sexual reproduction", "**Asexual reproduction**", "Fertilization", "Meiosis"] },
    { q: "Which of the following is a monocot plant?", opts: ["Bean", "Pea", "**Maize**", "Mango"] },
    { q: "The site of protein synthesis in the cell is the:", opts: ["Nucleus", "Lysosome", "**Ribosome**", "Vacuole"] },
    { q: "Which of the following is a major cause of global warming?", opts: ["Planting trees", "**Deforestation**", "Recycling", "Using bicycles"] },
    { q: "The oxygen-carrying protein in muscle cells is:", opts: ["Hemoglobin", "**Myoglobin**", "Actin", "Myosin"] },
    { q: "Which organelle handles the packaging of proteins?", opts: ["Rough ER", "**Golgi apparatus**", "Smooth ER", "Nucleolus"] },
    { q: "The number of chromosomes in a human egg cell is:", opts: ["46", "**23**", "22", "48"] },
    { q: "Which of the following is a fungal disease in humans?", opts: ["Cholera", "Influenza", "**Athlete's foot**", "Meningitis"] },
    { q: "The energy-releasing process that occurs in the absence of oxygen is:", opts: ["Aerobic respiration", "**Anaerobic respiration**", "Photosynthesis", "Digestion"] },
    { q: "Which part of the brain controls breathing and heart rate?", opts: ["Cerebrum", "Cerebellum", "**Medulla oblongata**", "Thalamus"] },
    { q: "The process by which organisms produce more of their own kind is:", opts: ["Growth", "**Reproduction**", "Development", "Metabolism"] },
    { q: "Which of the following is an example of a reflex action?", opts: ["Reading", "Walking", "**Blinking**", "Talking"] },
    { q: "The scientific name of humans is:", opts: ["Homo erectus", "**Homo sapiens**", "Homo habilis", "Pan troglodytes"] },
    { q: "Which of the following is NOT a characteristic of life?", opts: ["Growth", "Reproduction", "**Inorganic composition**", "Response to stimuli"] },
    { q: "The cell theory states that all cells come from:", opts: ["Non-living matter", "Spontaneous generation", "**Pre-existing cells**", "Outer space"] },
    { q: "Which organelle is found in plant cells but NOT in animal cells?", opts: ["Nucleus", "Mitochondria", "**Cell wall**", "Ribosome"] },
    { q: "The fluid part of the blood is called:", opts: ["Serum", "**Plasma**", "Hemoglobin", "Lymph"] },
    { q: "Which type of joint is found in the human shoulder?", opts: ["Hinge joint", "**Ball and socket joint**", "Pivot joint", "Fixed joint"] },
    { q: "The process of programmed cell death is known as:", opts: ["Necrosis", "**Apoptosis**", "Mitosis", "Meiosis"] },
    { q: "Which of the following is a pioneer species in primary succession?", opts: ["Grass", "Shrubs", "**Lichens**", "Trees"] },
    { q: "The hormone that regulates the sleep-wake cycle is:", opts: ["Insulin", "Cortisol", "**Melatonin**", "Oxytocin"] },
    { q: "Which of the following is a fossil fuel?", opts: ["Wood", "Water", "**Coal**", "Wind"] },
    { q: "The enzyme that joins DNA fragments is:", opts: ["Polymerase", "Helicase", "**Ligase**", "Protease"] },
    { q: "Which part of the ear converts sound vibrations into nerve impulses?", opts: ["Ear canal", "Eardrum", "Ossicles", "**Cochlea**"] },
    { q: "The study of tissues is called:", opts: ["Cytology", "**Histology**", "Anatomy", "Ecology"] },
    { q: "Which of the following is an example of a vestigial organ in humans?", opts: ["Heart", "Lungs", "**Appendix**", "Kidney"] },
    { q: "The process of taking food into the body is:", opts: ["Digestion", "**Ingestion**", "Absorption", "Assimilation"] },
    { q: "Which gas is primarily responsible for the depletion of the ozone layer?", opts: ["CO2", "Methane", "**CFCs**", "Nitrous oxide"] },
    { q: "The functional unit of the human lung is the:", opts: ["Bronchus", "Trachea", "**Alveolus**", "Diaphragm"] },
    { q: "Which of the following is a warm-blooded animal?", opts: ["Snake", "Frog", "**Eagle**", "Shark"] }
    
];

// --- 2012 E.C ---
QUESTIONS_DB.Natural.Biology["2012"] = [{ q: "Which of the following is the correct order of biological organization?", opts: ["Cell-Organ-Tissue-System", "**Cell-Tissue-Organ-System**", "Tissue-Cell-System-Organ", "Organ-System-Cell-Tissue"] },
    { q: "The scientist who first used the term 'cell' was:", opts: ["Leeuwenhoek", "**Robert Hooke**", "Schleiden", "Schwann"] },
    { q: "Which organelle is responsible for photosynthesis?", opts: ["Mitochondria", "**Chloroplast**", "Ribosome", "Vacuole"] },
    { q: "A cell that lacks a true nucleus is called:", opts: ["Eukaryotic", "**Prokaryotic**", "Multicellular", "Autotrophic"] },
    { q: "The 'Fluid Mosaic Model' describes the structure of:", opts: ["Nucleus", "**Cell membrane**", "Cytoplasm", "Cell wall"] },
    { q: "Which process moves substances against the concentration gradient?", opts: ["Diffusion", "Osmosis", "**Active transport**", "Facilitated diffusion"] },
    { q: "Enzymes are biologically classified as:", opts: ["Lipids", "**Proteins**", "Carbohydrates", "Nucleic acids"] },
    { q: "The site of attachment for spindle fibers during cell division is the:", opts: ["Centriole", "**Centromere**", "Nucleolus", "Cytoplasm"] },
    { q: "Which phase of mitosis involves the separation of sister chromatids?", opts: ["Prophase", "Metaphase", "**Anaphase**", "Telophase"] },
    { q: "The end product of glycolysis is:", opts: ["Glucose", "**Pyruvate**", "Lactic acid", "Acetyl-CoA"] },
    { q: "Which of the following is a product of fermentation in yeast?", opts: ["Lactic acid", "**Ethanol and CO2**", "Oxygen", "Glucose"] },
    { q: "How many daughter cells are produced at the end of meiosis?", opts: ["Two", "**Four**", "Eight", "One"] },
    { q: "The bond between two nitrogenous bases in DNA is a:", opts: ["Peptide bond", "Ionic bond", "**Hydrogen bond**", "Covalent bond"] },
    { q: "Which RNA molecule carries amino acids to the ribosome?", opts: ["mRNA", "**tRNA**", "rRNA", "snRNA"] },
    { q: "A cross between two heterozygous parents (Aa x Aa) results in what phenotypic ratio?", opts: ["1:1", "**3:1**", "9:3:3:1", "1:2:1"] },
    { q: "The genetic disorder caused by an extra copy of chromosome 21 is:", opts: ["Turner syndrome", "**Down syndrome**", "Klinefelter syndrome", "Albinism"] },
    { q: "Which of the following is an example of continuous variation?", opts: ["Blood group", "**Human height**", "Sex", "Eye color"] },
    { q: "The process of decoding mRNA into a polypeptide chain is:", opts: ["Transcription", "**Translation**", "Replication", "Transformation"] },
    { q: "Which of the following is a biotic factor?", opts: ["Soil pH", "Rainfall", "**Predation**", "Wind speed"] },
    { q: "Organisms that can produce their own food are called:", opts: ["Heterotrophs", "**Autotrophs**", "Saprotrophs", "Decomposers"] },
    { q: "In an energy pyramid, which level has the most energy?", opts: ["**Producers**", "Primary consumers", "Secondary consumers", "Tertiary consumers"] },
    { q: "A relationship where one organism benefits and the other is harmed is:", opts: ["Mutualism", "Commensalism", "**Parasitism**", "Symbiosis"] },
    { q: "The sequence of changes in a community over time is called:", opts: ["Evolution", "**Succession**", "Adaptation", "Homeostasis"] },
    { q: "Which of the following is a non-renewable resource?", opts: ["Forests", "Water", "**Petroleum**", "Wildlife"] },
    { q: "The main cause of the 'Greenhouse Effect' is the increase of:", opts: ["Oxygen", "**Carbon dioxide**", "Nitrogen", "Helium"] },
    { q: "Which of the following is an example of an amphibian?", opts: ["Lizard", "**Toad**", "Snake", "Turtle"] },
    { q: "The respiratory organ of an earthworm is the:", opts: ["Lungs", "Gills", "Trachea", "**Moist skin**"] },
    { q: "Which part of the digestive system absorbs most of the nutrients?", opts: ["Stomach", "**Small intestine**", "Large intestine", "Esophagus"] },
    { q: "The valve between the right atrium and right ventricle is the:", opts: ["Bicuspid", "**Tricuspid**", "Aortic", "Pulmonary"] },
    { q: "Which component of blood is responsible for clotting?", opts: ["RBCs", "WBCs", "**Platelets**", "Plasma"] },
    { q: "The structural unit of a muscle fiber is the:", opts: ["Neuron", "**Sarcomere**", "Nephron", "Osteon"] },
    { q: "Which hormone increases during an emergency ('Fight or Flight')?", opts: ["Insulin", "Thyroxine", "**Adrenaline**", "Estrogen"] },
    { q: "The part of the brain that maintains body posture is the:", opts: ["Cerebrum", "**Cerebellum**", "Medulla", "Thalamus"] },
    { q: "Which of the following is a chemical defense in plants?", opts: ["Thorns", "Waxy cuticle", "**Nicotine**", "Bark"] },
    { q: "The process of egg release from the ovary is called:", opts: ["Menstruation", "**Ovulation**", "Fertilization", "Implantation"] },
    { q: "Which disease is caused by a protozoan?", opts: ["AIDS", "Tuberculosis", "**Malaria**", "Influenza"] },
    { q: "The study of fossils is called:", opts: ["Ecology", "Genetics", "**Paleontology**", "Anatomy"] },
    { q: "According to Darwin, evolution occurs through:", opts: ["Use and disuse", "**Natural selection**", "Acquired characteristics", "Sudden mutation"] },
    { q: "Which of the following is a function of the lymphatic system?", opts: ["Oxygen transport", "**Fat absorption**", "Digestion", "Heat production"] },
    { q: "The 'lock and key' hypothesis explains the action of:", opts: ["Hormones", "**Enzymes**", "Antibodies", "Genes"] },
    { q: "Which vitamin is needed for good night vision?", opts: ["**Vitamin A**", "Vitamin B", "Vitamin C", "Vitamin D"] },
    { q: "A solution with a lower solute concentration than the cell is:", opts: ["Hypertonic", "**Hypotonic**", "Isotonic", "Saturated"] },
    { q: "Which organelle synthesizes steroids and lipids?", opts: ["Rough ER", "**Smooth ER**", "Golgi", "Lysosome"] },
    { q: "The energy-rich molecule produced during light reactions is:", opts: ["Glucose", "Starch", "**ATP**", "Pyruvate"] },
    { q: "During which phase of the cell cycle is DNA replicated?", opts: ["G1 phase", "**S phase**", "G2 phase", "M phase"] },
    { q: "The exchange of genetic material between non-sister chromatids is:", opts: ["Mutation", "**Crossing over**", "Segregation", "Linkage"] },
    { q: "How many autosomes are in a normal human somatic cell?", opts: ["46", "23", "**44**", "2"] },
    { q: "A gene that hides the expression of another gene is:", opts: ["Recessive", "**Dominant**", "Co-dominant", "Linked"] },
    { q: "Which base replaces Thymine in RNA?", opts: ["Adenine", "Guanine", "Cytosine", "**Uracil**"] },
    { q: "The use of living organisms to clean up polluted environments is:", opts: ["Bio-mining", "**Bioremediation**", "Fermentation", "Cloning"] },
    { q: "Which of the following is a density-dependent factor?", opts: ["Flood", "Fire", "**Disease**", "Drought"] },
    { q: "The first trophic level in any ecosystem is always:", opts: ["**Producers**", "Herbivores", "Carnivores", "Decomposers"] },
    { q: "In commensalism, the second organism (the host) is:", opts: ["Benefited", "Harmed", "**Unaffected**", "Killed"] },
    { q: "The final stable community in a succession is the:", opts: ["Pioneer community", "**Climax community**", "Seral stage", "Biotic community"] },
    { q: "Which pollutant causes acid rain?", opts: ["CO2", "**Sulfur dioxide**", "CFCs", "Oxygen"] },
    { q: "The ozone layer protects life from:", opts: ["Infrared rays", "**Ultraviolet rays**", "X-rays", "Microwaves"] },
    { q: "Which animal has a three-chambered heart?", opts: ["Fish", "**Frog**", "Bird", "Human"] },
    { q: "Bile is stored in the:", opts: ["Liver", "Pancreas", "**Gallbladder**", "Stomach"] },
    { q: "The functional unit of the human kidney is the:", opts: ["Neuron", "**Nephron**", "Alveolus", "Ureter"] },
    { q: "Which blood vessel carries blood away from the heart?", opts: ["Vein", "**Artery**", "Capillary", "Venule"] },
    { q: "The maintenance of constant body temperature is:", opts: ["Osmoregulation", "**Thermoregulation**", "Excretion", "Digestion"] },
    { q: "Which part of the brain controls voluntary actions?", opts: ["**Cerebrum**", "Cerebellum", "Medulla", "Spinal cord"] },
    { q: "The long extension of a nerve cell is the:", opts: ["Dendrite", "**Axon**", "Cell body", "Synapse"] },
    { q: "Plants move towards light due to:", opts: ["Geotropism", "**Phototropism**", "Hydrotropism", "Thigmotropism"] },
    { q: "Which gland is known as the 'master gland'?", opts: ["Thyroid", "Adrenal", "**Pituitary**", "Pancreas"] },
    { q: "Which hormone is responsible for male secondary sex traits?", opts: ["Estrogen", "Progesterone", "**Testosterone**", "Insulin"] },
    { q: "The primary site of gas exchange in humans is the:", opts: ["Bronchi", "Trachea", "**Alveoli**", "Nose"] },
    { q: "A disease that can be passed from animals to humans is:", opts: ["Genetic", "**Zoonotic**", "Deficiency", "Congenital"] },
    { q: "The wings of a bird and the wings of a butterfly are:", opts: ["Homologous", "**Analogous**", "Vestigial", "Identical"] },
    { q: "Which of the following is a primary consumer?", opts: ["Lion", "Hawk", "**Rabbit**", "Tree"] },
    { q: "The building blocks of nucleic acids are:", opts: ["Amino acids", "Monosaccharides", "**Nucleotides**", "Fatty acids"] },
    { q: "Which organelle is called the 'suicide bag'?", opts: ["Ribosome", "**Lysosome**", "Vacuole", "Nucleus"] },
    { q: "The process of engulfing solid particles by a cell is:", opts: ["Pinocytosis", "**Phagocytosis**", "Exocytosis", "Osmosis"] },
    { q: "The CO2 acceptor in the Calvin cycle is:", opts: ["PGA", "G3P", "**RuBP**", "Rubisco"] },
    { q: "A protein that acts as a biological catalyst is an:", opts: ["Antibody", "Hormone", "**Enzyme**", "Vitamin"] },
    { q: "During prophase, the chromatin condenses into:", opts: ["Genes", "**Chromosomes**", "RNA", "Proteins"] },
    { q: "The division of the cytoplasm is called:", opts: ["Mitosis", "Meiosis", "**Cytokinesis**", "Karyokinesis"] },
    { q: "How many ATP molecules are used during glycolysis?", opts: ["**2**", "4", "36", "38"] },
    { q: "An organism with two different alleles for a trait is:", opts: ["Homozygous", "**Heterozygous**", "Haploid", "Diploid"] },
    { q: "The sugar found in RNA is:", opts: ["Deoxyribose", "**Ribose**", "Glucose", "Sucrose"] },
    { q: "The technology used to make copies of DNA is:", opts: ["Cloning", "**PCR**", "Fermentation", "Hybridization"] },
    { q: "Which of the following is a scavenger?", opts: ["Lion", "**Hyena**", "Zebra", "Cow"] },
    { q: "The role an organism plays in its environment is its:", opts: ["Habitat", "**Niche**", "Ecosystem", "Biome"] },
    { q: "Which relationship is (+, 0)?", opts: ["Mutualism", "**Commensalism**", "Parasitism", "Competition"] },
    { q: "Carbon enters the biotic part of the ecosystem through:", opts: ["Respiration", "**Photosynthesis**", "Burning", "Decomposition"] },
    { q: "Water pollution caused by excess nutrients is:", opts: ["Acidification", "**Eutrophication**", "Salination", "Bioaccumulation"] },
    { q: "Which of the following is a vertebrate?", opts: ["Spider", "Insects", "**Snake**", "Earthworm"] },
    { q: "The enzyme that digests fats is:", opts: ["Amylase", "Pepsin", "**Lipase**", "Trypsin"] },
    { q: "The pacemaker of the heart is the:", opts: ["**SA node**", "AV node", "Bundle of His", "Purkinje fibers"] },
    { q: "Which gas is carried primarily by plasma as bicarbonate?", opts: ["Oxygen", "**Carbon dioxide**", "Nitrogen", "Carbon monoxide"] },
    { q: "The hormone that lowers blood calcium levels is:", opts: ["Parathyroid hormone", "**Calcitonin**", "Thyroxine", "Insulin"] },
    { q: "The gap between two neurons is the:", opts: ["Axon", "Dendrite", "**Synaptic cleft**", "Myelin"] },
    { q: "The sensory layer of the heart is the:", opts: ["Epicardium", "Myocardium", "**Endocardium**", "Pericardium"] },
    { q: "Which part of the brain controls thirst and hunger?", opts: ["**Hypothalamus**", "Thalamus", "Cerebrum", "Medulla"] },
    { q: "The male gamete in flowering plants is found in:", opts: ["Ovary", "**Pollen grain**", "Stigma", "Petal"] },
    { q: "Which of the following is a sexually transmitted disease?", opts: ["Malaria", "**Syphilis**", "Cholera", "Typhoid"] },
    { q: "The process of a species becoming extinct is:", opts: ["Natural selection", "Adaptation", "**Extinction**", "Speciation"] },
    { q: "Which tool is used to measure the rate of transpiration?", opts: ["Barometer", "**Potometer**", "Hygrometer", "Thermometer"] },
    { q: "The most abundant gas in the atmosphere is:", opts: ["Oxygen", "**Nitrogen**", "Carbon dioxide", "Hydrogen"] },
    
];

// --- 2013 E.C ---
QUESTIONS_DB.Natural.Biology["2013"] = [{ q: "Which of the following is the largest taxonomic group?", opts: ["Class", "Order", "**Phylum**", "Family"] },
    { q: "The primary function of the cell wall in plants is to:", opts: ["Store food", "Control transport", "**Provide structural support**", "Synthesize proteins"] },
    { q: "Which organelle contains its own DNA and ribosomes?", opts: ["Golgi body", "**Mitochondria**", "Lysosome", "Endoplasmic reticulum"] },
    { q: "The double helix structure of DNA was proposed by:", opts: ["Mendel", "Darwin", "**Watson and Crick**", "Pasteur"] },
    { q: "Which of the following is an example of a polysaccharide?", opts: ["Glucose", "Sucrose", "Fructose", "**Starch**"] },
    { q: "The process of cell drinking is known as:", opts: ["Phagocytosis", "**Pinocytosis**", "Exocytosis", "Diffusion"] },
    { q: "Which enzyme breaks down hydrogen peroxide in cells?", opts: ["Amylase", "**Catalase**", "Lipase", "Pepsin"] },
    { q: "The movement of ions against a concentration gradient requires:", opts: ["Osmosis", "Diffusion", "**ATP energy**", "Gravity"] },
    { q: "In which stage of mitosis do chromosomes become visible?", opts: ["**Prophase**", "Metaphase", "Anaphase", "Telophase"] },
    { q: "The cross-over of homologous chromosomes occurs during:", opts: ["Mitosis", "**Meiosis I**", "Meiosis II", "Binary fission"] },
    { q: "Which molecule acts as the final electron acceptor in aerobic respiration?", opts: ["Glucose", "NAD+", "**Oxygen**", "Water"] },
    { q: "The pigment that captures light energy in plants is:", opts: ["Hemoglobin", "**Chlorophyll**", "Melanin", "Carotene"] },
    { q: "A codon consists of how many nucleotides?", opts: ["One", "Two", "**Three**", "Four"] },
    { q: "The sequence of amino acids in a protein is its:", opts: ["**Primary structure**", "Secondary structure", "Tertiary structure", "Quaternary structure"] },
    { q: "Which of the following is a sex-linked trait in humans?", opts: ["Blood type", "**Color blindness**", "Height", "Skin color"] },
    { q: "The sum total of all chemical reactions in an organism is:", opts: ["Anabolism", "Catabolism", "**Metabolism**", "Homeostasis"] },
    { q: "Which of the following is a greenhouse gas?", opts: ["Nitrogen", "Oxygen", "**Methane**", "Argon"] },
    { q: "The study of the internal structure of organisms is:", opts: ["Physiology", "Ecology", "**Anatomy**", "Genetics"] },
    { q: "Which biome is characterized by permafrost?", opts: ["Desert", "**Tundra**", "Savanna", "Tropical rainforest"] },
    { q: "The first organism in a food chain is always a:", opts: ["**Producer**", "Herbivore", "Carnivore", "Decomposer"] },
    { q: "Which of the following is a density-independent factor?", opts: ["Competition", "Disease", "**Volcanic eruption**", "Predation"] },
    { q: "The functional unit of the human gas exchange system is the:", opts: ["Bronchus", "**Alveolus**", "Trachea", "Diaphragm"] },
    { q: "Which blood vessel has the thinnest walls?", opts: ["Artery", "Vein", "**Capillary**", "Arteriole"] },
    { q: "The hormone that stimulates the 'milk let-down' reflex is:", opts: ["Progesterone", "Estrogen", "**Oxytocin**", "Prolactin"] },
    { q: "Which part of the brain is responsible for memory and learning?", opts: ["**Cerebrum**", "Cerebellum", "Medulla", "Pons"] },
    { q: "The liquid medium of the blood is:", opts: ["Serum", "**Plasma**", "Lymph", "Platelets"] },
    { q: "Which of the following is a nitrogen-fixing bacterium?", opts: ["E. coli", "**Rhizobium**", "Streptococcus", "Salmonella"] },
    { q: "The process by which DNA makes a copy of itself is:", opts: ["Transcription", "Translation", "**Replication**", "Mutation"] },
    { q: "Which type of selection favors average individuals in a population?", opts: ["Directional", "**Stabilizing**", "Disruptive", "Artificial"] },
    { q: "The backbone of DNA is made of sugar and:", opts: ["Nitrogen base", "**Phosphate**", "Amino acid", "Lipid"] },
    { q: "Which of the following is a major constituent of the exoskeleton of insects?", opts: ["Cellulose", "**Chitin**", "Starch", "Glycogen"] },
    { q: "The site of translation in a cell is the:", opts: ["Nucleus", "**Ribosome**", "Lysosome", "Vacuole"] },
    { q: "Which of the following is a non-communicable disease?", opts: ["Cholera", "Malaria", "**Cancer**", "Tuberculosis"] },
    { q: "The maintainance of water balance in the body is:", opts: ["Thermoregulation", "**Osmoregulation**", "Excretion", "Digestion"] },
    { q: "Which vitamin is necessary for the absorption of calcium?", opts: ["Vitamin A", "Vitamin C", "**Vitamin D**", "Vitamin E"] },
    { q: "The male part of the flower is called the:", opts: ["Carpel", "**Stamen**", "Petal", "Sepal"] },
    { q: "Which of the following is a C4 plant?", opts: ["Rice", "Wheat", "**Maize**", "Potato"] },
    { q: "The simplest level of life is the:", opts: ["**Cell**", "Tissue", "Organ", "Organism"] },
    { q: "Which hormone is known as the pregnancy hormone?", opts: ["Estrogen", "**Progesterone**", "Testosterone", "Insulin"] },
    { q: "The process of converting glucose into energy without oxygen is:", opts: ["Aerobic respiration", "**Fermentation**", "Photosynthesis", "Nitrogen fixation"] },
    { q: "Which of the following is a parasitic plant?", opts: ["Fern", "Moss", "**Dodder**", "Orchid"] },
    { q: "The structural unit of the kidney is the:", opts: ["Neuron", "**Nephron**", "Ureter", "Bladder"] },
    { q: "Which part of the nervous system consists of the brain and spinal cord?", opts: ["Peripheral", "**Central**", "Autonomic", "Somatic"] },
    { q: "The protein that makes up hair and nails is:", opts: ["Collagen", "Elastin", "**Keratin**", "Hemoglobin"] },
    { q: "Which of the following is a saturated fat?", opts: ["Olive oil", "**Butter**", "Sunflower oil", "Fish oil"] },
    { q: "The universal energy currency of the cell is:", opts: ["DNA", "RNA", "**ATP**", "NADH"] },
    { q: "Which scientist discovered the ABO blood groups?", opts: ["Darwin", "Mendel", "**Karl Landsteiner**", "Pasteur"] },
    { q: "The opening in the leaf for gas exchange is the:", opts: ["Lenticel", "**Stoma**", "Cuticle", "Xylem"] },
    { q: "Which of the following is a reptile?", opts: ["Frog", "Salamander", "**Crocodile**", "Toad"] },
    { q: "The hormone that regulates the basal metabolic rate is:", opts: ["Insulin", "**Thyroxine**", "Adrenaline", "Glucagon"] },
    { q: "Which of the following is a feature of wind-pollinated flowers?", opts: ["Bright colors", "Scent", "**Large amounts of pollen**", "Nectar"] },
    { q: "The long-term state of an ecosystem is:", opts: ["Succession", "**Climax community**", "Niche", "Habitat"] },
    { q: "Which organelle is responsible for lipid synthesis?", opts: ["Rough ER", "**Smooth ER**", "Golgi", "Ribosome"] },
    { q: "The change in a population's gene pool over time is:", opts: ["**Evolution**", "Mutation", "Adaptation", "Selection"] },
    { q: "Which of the following is an enzyme that digests lipids?", opts: ["Protease", "Amylase", "**Lipase**", "Cellulase"] },
    { q: "The storage form of glucose in plants is:", opts: ["Glycogen", "**Starch**", "Cellulose", "Chitin"] },
    { q: "Which of the following is a prokaryote?", opts: ["Fungi", "Algae", "**Cyanobacteria**", "Protozoa"] },
    { q: "The movement of sucrose in the phloem is called:", opts: ["Transpiration", "**Translocation**", "Transformation", "Translation"] },
    { q: "Which part of the heart receives deoxygenated blood from the body?", opts: ["Left atrium", "**Right atrium**", "Left ventricle", "Right ventricle"] },
    { q: "The chemical used to test for the presence of starch is:", opts: ["Benedict's", "**Iodine**", "Biuret", "Ethanol"] },
    { q: "Which of the following is a source of genetic variation?", opts: ["Mitosis", "**Mutation**", "Cloning", "Budding"] },
    { q: "The largest part of the human brain is the:", opts: ["**Cerebrum**", "Cerebellum", "Brainstem", "Thalamus"] },
    { q: "Which gas is used by plants during photosynthesis?", opts: ["Oxygen", "**Carbon dioxide**", "Nitrogen", "Hydrogen"] },
    { q: "The interaction where both species benefit is:", opts: ["**Mutualism**", "Commensalism", "Parasitism", "Competition"] },
    { q: "Which of the following is a monocot trait?", opts: ["Taproot", "Net-like veins", "**Parallel veins**", "Two cotyledons"] },
    { q: "The enzyme that unzips the DNA double helix is:", opts: ["Polymerase", "**Helicase**", "Ligase", "Amylase"] },
    { q: "Which of the following is a flightless bird?", opts: ["Eagle", "Sparrow", "**Ostrich**", "Hawk"] },
    { q: "The fluid that protects the fetus in the uterus is:", opts: ["Plasma", "Lymph", "**Amniotic fluid**", "Bile"] },
    { q: "Which of the following is an autotroph?", opts: ["Fungi", "Animal", "**Algae**", "Virus"] },
    { q: "The building blocks of proteins are:", opts: ["Nucleotides", "**Amino acids**", "Fatty acids", "Glucose"] },
    { q: "Which of the following is a viral disease?", opts: ["Cholera", "**Influenza**", "Tetanus", "Syphilis"] },
    { q: "The structural unit of the compact bone is the:", opts: ["Nephron", "Neuron", "**Osteon**", "Sarcomere"] },
    { q: "Which hormone decreases blood sugar levels?", opts: ["Glucagon", "Adrenaline", "**Insulin**", "Thyroxine"] },
    { q: "The study of insects is called:", opts: ["Ornithology", "**Entomology**", "Herpetology", "Ichthyology"] },
    { q: "Which of the following is a primary consumer?", opts: ["Lion", "**Cow**", "Wolf", "Grass"] },
    { q: "The process of maintaining a stable internal temperature is:", opts: ["**Thermoregulation**", "Osmoregulation", "Excretion", "Digestion"] },
    { q: "Which of the following is a characteristic of all living things?", opts: ["Movement", "**Reproduction**", "Photosynthesis", "Lungs"] },
    { q: "The part of the ear responsible for balance is the:", opts: ["Cochlea", "Eardrum", "**Semicircular canals**", "Ossicles"] },
    { q: "Which of the following is a renewable resource?", opts: ["Coal", "Natural gas", "**Water**", "Nuclear energy"] },
    { q: "The base pair rule states that Cytosine always pairs with:", opts: ["Adenine", "**Guanine**", "Thymine", "Uracil"] },
    { q: "Which of the following is a function of platelets?", opts: ["Oxygen transport", "Immunity", "**Blood clotting**", "Nutrient storage"] },
    { q: "The first stage of cellular respiration is:", opts: ["Krebs cycle", "**Glycolysis**", "Electron transport", "Fermentation"] },
    { q: "Which of the following is an example of a reflex action?", opts: ["Writing", "Walking", "**Knee-jerk**", "Reading"] },
    { q: "The sugar found in DNA is:", opts: ["Ribose", "**Deoxyribose**", "Glucose", "Galactose"] },
    { q: "Which of the following is a decomposer?", opts: ["Grass", "Rabbit", "**Mushroom**", "Snake"] },
    { q: "The theory of use and disuse was proposed by:", opts: ["Darwin", "**Lamarck**", "Mendel", "Linnaeus"] },
    { q: "Which of the following is a characteristic of enzymes?", opts: ["Consumed in reactions", "**Lower activation energy**", "Work at any pH", "Are lipids"] },
    { q: "The process of egg formation is called:", opts: ["Spermatogenesis", "**Oogenesis**", "Fertilization", "Cleavage"] },
    { q: "Which of the following is a primary producer?", opts: ["Zebra", "Lion", "**Tree**", "Fungi"] },
    { q: "The part of the eye that regulates light intensity is the:", opts: ["Retina", "**Iris**", "Lens", "Cornea"] },
    { q: "Which of the following is a function of the skeletal system?", opts: ["Nerve impulse", "**Support and protection**", "Heat generation", "Excretion"] },
    { q: "The study of fungi is called:", opts: ["Phycology", "**Mycology**", "Virology", "Bacteriology"] },
    { q: "Which of the following is a vestigial organ in humans?", opts: ["Heart", "Liver", "**Tailbone**", "Stomach"] },
    { q: "The hormone that causes the ripening of fruits is:", opts: ["Auxin", "Gibberellin", "**Ethylene**", "Cytokinin"] },
    { q: "Which of the following is a mammal that lays eggs?", opts: ["Kangaroo", "Whale", "**Platypus**", "Bat"] },
    { q: "The functional unit of the human liver is the:", opts: ["Nephron", "Neuron", "**Lobule**", "Alveolus"] },
    { q: "Which gas makes up about 78% of the Earth's atmosphere?", opts: ["Oxygen", "**Nitrogen**", "Argon", "Carbon dioxide"] },
    { q: "The phase of the cell cycle where the cell grows is:", opts: ["**Interphase**", "Prophase", "Anaphase", "Metaphase"] },
    { q: "Which of the following is an inherited disease?", opts: ["Cholera", "Malaria", "**Sickle cell anemia**", "Typhoid"] },
    { q: "Which of the following is a component of a nucleotide?", opts: ["Amino acid", "Fatty acid", "**Phosphate group**", "Glycerol"] }
    
];

// --- 2014 E.C ---
QUESTIONS_DB.Natural.Biology["2014"] = [{ q: "Which of the following is the smallest unit of life capable of independent existence?", opts: ["Tissue", "Organ", "**Cell**", "Organelle"] },
    { q: "The chemical substance that makes up the majority of the plasma membrane is:", opts: ["Protein", "**Phospholipid**", "Cholesterol", "Carbohydrate"] },
    { q: "Which cell organelle is responsible for generating most of the cell's ATP?", opts: ["Chloroplast", "Ribosome", "**Mitochondria**", "Lysosome"] },
    { q: "The process by which DNA is copied into mRNA is called:", opts: ["Translation", "**Transcription**", "Replication", "Transformation"] },
    { q: "Which of the following base pairs is found in DNA?", opts: ["A-U", "**G-C**", "T-U", "C-A"] },
    { q: "An organism that obtains energy by consuming other organisms is a:", opts: ["Producer", "**Heterotroph**", "Autotroph", "Phototroph"] },
    { q: "Enzymes increase the rate of a chemical reaction by:", opts: ["Increasing temperature", "**Lowering activation energy**", "Consuming reactants", "Changing equilibrium"] },
    { q: "The movement of water across a selectively permeable membrane is:", opts: ["Diffusion", "**Osmosis**", "Active transport", "Facilitated diffusion"] },
    { q: "During which phase of mitosis do the chromosomes align at the equator?", opts: ["Prophase", "**Metaphase**", "Anaphase", "Telophase"] },
    { q: "Which of the following is a product of aerobic respiration?", opts: ["Ethanol", "Lactic acid", "**Carbon dioxide and water**", "Glucose"] },
    { q: "The genetic material of a prokaryotic cell is located in the:", opts: ["Nucleus", "**Nucleoid**", "Nucleolus", "Capsid"] },
    { q: "Which of the following is a function of the Golgi apparatus?", opts: ["Protein synthesis", "**Packaging and secretion**", "DNA replication", "Lipid digestion"] },
    { q: "The ratio of phenotypes in a dihybrid cross (AaBb x AaBb) is:", opts: ["3:1", "1:2:1", "**9:3:3:1**", "1:1:1:1"] },
    { q: "A human male inherits his X chromosome from his:", opts: ["Father", "**Mother**", "Both parents", "Grandfather"] },
    { q: "Which of the following is an example of a vestigial structure in humans?", opts: ["Heart", "Lungs", "**Appendix**", "Kidneys"] },
    { q: "The main structural component of fungal cell walls is:", opts: ["Cellulose", "**Chitin**", "Peptidoglycan", "Starch"] },
    { q: "Which hormone is responsible for lowering blood glucose levels?", opts: ["Glucagon", "**Insulin**", "Adrenaline", "Thyroxine"] },
    { q: "The exchange of gases in the human lungs occurs in the:", opts: ["Bronchi", "Trachea", "**Alveoli**", "Pharynx"] },
    { q: "Which of the following is a characteristic of a virus?", opts: ["Growth", "Metabolism", "**Genetic material (DNA or RNA)**", "Cellular structure"] },
    { q: "The primary source of energy for almost all life on Earth is:", opts: ["Geothermal", "**Sunlight**", "Chemical", "Nuclear"] },
    { q: "Which of the following is a primary consumer?", opts: ["Lion", "**Zebra**", "Grass", "Fungi"] },
    { q: "The interaction where one organism benefits and the other is unaffected is:", opts: ["Mutualism", "**Commensalism**", "Parasitism", "Competition"] },
    { q: "Which vitamin is synthesized by bacteria in the human large intestine?", opts: ["Vitamin A", "Vitamin C", "**Vitamin K**", "Vitamin D"] },
    { q: "The structural unit of the human nervous system is the:", opts: ["Nephron", "**Neuron**", "Axon", "Synapse"] },
    { q: "Which blood vessel carries oxygenated blood to the heart from the lungs?", opts: ["Aorta", "Pulmonary artery", "**Pulmonary vein**", "Vena cava"] },
    { q: "The process by which plants lose water through their leaves is:", opts: ["Evaporation", "Guttation", "**Transpiration**", "Respiration"] },
    { q: "Which of the following is a non-communicable disease?", opts: ["Tuberculosis", "Malaria", "**Diabetes**", "Influenza"] },
    { q: "The theory of natural selection was primarily developed by:", opts: ["Lamarck", "**Charles Darwin**", "Gregor Mendel", "Louis Pasteur"] },
    { q: "Which part of the brain controls balance and posture?", opts: ["Cerebrum", "**Cerebellum**", "Medulla oblongata", "Thalamus"] },
    { q: "The first stage of cellular respiration, occurring in the cytoplasm, is:", opts: ["Krebs cycle", "**Glycolysis**", "Electron transport chain", "Fermentation"] },
    { q: "Which type of RNA brings amino acids to the ribosome?", opts: ["mRNA", "**tRNA**", "rRNA", "snRNA"] },
    { q: "In a DNA molecule, Adenine (A) always pairs with:", opts: ["Guanine (G)", "Cytosine (C)", "**Thymine (T)**", "Uracil (U)"] },
    { q: "Which of the following is a biotic factor in an ecosystem?", opts: ["Sunlight", "Water", "**Bacteria**", "Soil"] },
    { q: "The functional unit of the human kidney is the:", opts: ["Neuron", "**Nephron**", "Ureter", "Bladder"] },
    { q: "Which of the following is a steroid hormone?", opts: ["Insulin", "Growth hormone", "**Testosterone**", "Adrenaline"] },
    { q: "The study of the relationship between organisms and their environment is:", opts: ["Genetics", "**Ecology**", "Evolution", "Taxonomy"] },
    { q: "Which of the following organisms is a decomposer?", opts: ["Green plant", "Rabbit", "**Fungi**", "Eagle"] },
    { q: "The genetic disorder characterized by the inability of blood to clot is:", opts: ["Sickle cell anemia", "**Hemophilia**", "Cystic fibrosis", "Thalassemia"] },
    { q: "Which of the following is a characteristic of enzymes?", opts: ["They are consumed in the reaction", "**They are highly specific**", "They work only at high temperatures", "They are made of carbohydrates"] },
    { q: "The process of programmed cell death is called:", opts: ["Necrosis", "**Apoptosis**", "Mitosis", "Meiosis"] },
    { q: "Which gas is the most significant contributor to the greenhouse effect?", opts: ["Nitrogen", "Oxygen", "**Carbon dioxide**", "Argon"] },
    { q: "The part of the flower that receives pollen grains is the:", opts: ["Anther", "**Stigma**", "Ovary", "Petal"] },
    { q: "Which of the following is a prokaryotic organism?", opts: ["Yeast", "Amoeba", "**Cyanobacteria**", "Mushroom"] },
    { q: "The largest organ of the human body is the:", opts: ["Liver", "Brain", "**Skin**", "Lungs"] },
    { q: "Which type of selection favors both extreme phenotypes in a population?", opts: ["Directional", "Stabilizing", "**Disruptive**", "Artificial"] },
    { q: "The storage form of energy in animal cells is:", opts: ["Starch", "Cellulose", "**Glycogenglycogen**", "Chitin"] },
    { q: "Which of the following is a viral disease?", opts: ["Cholera", "Typhoid", "**AIDS**", "Syphilis"] },
    { q: "The structural unit of bone is the:", opts: ["Neuron", "Sarcomere", "**Osteon**", "Nephron"] },
    { q: "Which part of the eye contains the photoreceptor cells?", opts: ["Cornea", "Iris", "**Retina**", "Lens"] },
    { q: "The hormone that regulates the sleep-wake cycle is:", opts: ["Insulin", "Thyroxine", "**Melatonin**", "Estrogen"] },
    { q: "Which of the following is a renewable resource?", opts: ["Coal", "Natural gas", "**Forests**", "Petroleum"] },
    { q: "The process by which liquid water changes into water vapor is:", opts: ["Condensation", "**Evaporation**", "Precipitation", "Infiltration"] },
    { q: "Which of the following is a function of red blood cells?", opts: ["Immunity", "Blood clotting", "**Oxygen transport**", "Hormone transport"] },
    { q: "The basic unit of classification in biology is:", opts: ["Kingdom", "Genus", "**Species**", "Phylum"] },
    { q: "Which of the following is a property of water?", opts: ["Low specific heat", "**High surface tension**", "Non-polar", "Less dense than air"] },
    { q: "The enzyme found in the stomach that digests proteins is:", opts: ["Amylase", "**Pepsin**", "Lipase", "Trypsin"] },
    { q: "Which of the following is a flightless bird?", opts: ["Eagle", "Hawk", "**Penguin**", "Sparrow"] },
    { q: "The site of aerobic respiration in the cell is the:", opts: ["Ribosome", "Chloroplast", "**Mitochondria**", "Nucleus"] },
    { q: "Which of the following is a component of a nucleotide?", opts: ["Amino acid", "**Phosphate group**", "Fatty acid", "Glycerol"] },
    { q: "The maintenance of a stable internal environment is called:", opts: ["Metabolism", "Evolution", "**Homeostasis**", "Growth"] },
    { q: "Which of the following is a greenhouse gas?", opts: ["Oxygen", "Nitrogen", "**Methane**", "Argon"] },
    { q: "The process of egg formation in females is:", opts: ["Spermatogenesis", "**Oogenesis**", "Fertilization", "Cleavage"] },
    { q: "Which of the following is a primary producer?", opts: ["Grasshopper", "Bird", "**Algae**", "Snake"] },
    { q: "The part of the leaf where most photosynthesis occurs is the:", opts: ["Epidermis", "**Mesophyll**", "Xylem", "Phloem"] },
    { q: "Which of the following is a function of white blood cells?", opts: ["Oxygen transport", "Blood clotting", "**Fighting infections**", "Nutrient transport"] },
    { q: "The hormone produced by the adrenal glands during stress is:", opts: ["Insulin", "Thyroxine", "**Adrenaline**", "Estrogen"] },
    { q: "Which of the following is a monocotyledonous plant?", opts: ["Bean", "Pea", "**Wheat**", "Mango"] },
    { q: "The genetic makeup of an organism is its:", opts: ["Phenotype", "**Genotype**", "Allele", "Mutation"] },
    { q: "Which of the following is a fungal disease?", opts: ["Malaria", "Influenza", "**Ringworm**", "Cholera"] },
    { q: "The movement of a plant part in response to gravity is:", opts: ["Phototropism", "**Geotropism**", "Hydrotropism", "Thigmotropism"] },
    { q: "Which of the following is a function of the liver?", opts: ["Urine production", "**Detoxification**", "Digestion of starch", "Pumping blood"] },
    { q: "The gas used by plants during photosynthesis is:", opts: ["Oxygen", "**Carbon dioxide**", "Nitrogen", "Argon"] },
    { q: "Which of the following is an example of a reflex action?", opts: ["Reading", "Walking", "**Knee-jerk**", "Talking"] },
    { q: "The sugar found in RNA is:", opts: ["Deoxyribose", "**Ribose**", "Glucose", "Fructose"] },
    { q: "Which of the following is a characteristic of all living things?", opts: ["Movement", "**Growth**", "Photosynthesis", "Lungs"] },
    { q: "The phase of the cell cycle where DNA is replicated is:", opts: ["G1 phase", "**S phase**", "G2 phase", "M phase"] },
    { q: "Which of the following is a primary consumer?", opts: ["Hawk", "Snake", "**Cow**", "Lion"] },
    { q: "The part of the eye that controls the amount of light entering is the:", opts: ["Retina", "**Iris**", "Lens", "Cornea"] },
    { q: "Which of the following is a function of the skeletal system?", opts: ["Nerve impulse", "**Support and protection**", "Heat generation", "Excretion"] },
    { q: "The study of heredity and variation is:", opts: ["Ecology", "**Genetics**", "Evolution", "Taxonomy"] },
    { q: "Which of the following is a vestigial organ in humans?", opts: ["Heart", "Liver", "**Tailbone**", "Stomach"] },
    { q: "The hormone that causes the ripening of fruits is:", opts: ["Auxin", "Gibberellin", "**Ethylene**", "Cytokinin"] },
    { q: "Which of the following is a mammal?", opts: ["Shark", "Frog", "**Dolphin**", "Turtle"] },
    { q: "The functional unit of the human liver is the:", opts: ["Nephron", "Neuron", "**Lobule**", "Alveolus"] },
    { q: "Which gas makes up about 21% of the Earth's atmosphere?", opts: ["Nitrogen", "**Oxygen**", "Argon", "Carbon dioxide"] },
    { q: "The phase of the cell cycle where the cell divides is:", opts: ["Interphase", "Prophase", "Anaphase", "**M phase**"] },
    { q: "Which of the following is an inherited trait?", opts: ["Language", "Scars", "**Blood type**", "Knowledge"] },
    { q: "Which of the following is a component of a cell membrane?", opts: ["Starch", "Glycogen", "**Proteins**", "Cellulose"] },
    { q: "The process by which green plants make food is:", opts: ["Respiration", "**Photosynthesis**", "Digestion", "Excretion"] },
    { q: "Which organelle is called the 'suicide bag'?", opts: ["Ribosome", "**Lysosome**", "Vacuole", "Nucleus"] },
    { q: "The building blocks of nucleic acids are:", opts: ["Amino acids", "Monosaccharides", "**Nucleotides**", "Fatty acids"] },
    { q: "Which of the following is a primary consumer?", opts: ["Lion", "Hawk", "**Rabbit**", "Tree"] },
    { q: "The role an organism plays in its environment is its:", opts: ["Habitat", "**Niche**", "Ecosystem", "Biome"] },
    { q: "Which relationship is (+, +)?", opts: ["**Mutualism**", "Commensalism", "Parasitism", "Competition"] },
    { q: "Carbon enters the biotic part of the ecosystem through:", opts: ["Respiration", "**Photosynthesis**", "Burning", "Decomposition"] },
    { q: "The enzyme that digests fats is:", opts: ["Amylase", "Pepsin", "**Lipase**", "Trypsin"] },
    { q: "The pacemaker of the heart is the:", opts: ["**SA node**", "AV node", "Bundle of His", "Purkinje fibers"] },
    { q: "Which gas is carried primarily by red blood cells?", opts: ["**Oxygen**", "Carbon dioxide", "Nitrogen", "Carbon monoxide"] },
    { q: "The hormone that increases heart rate is:", opts: ["Insulin", "Thyroxine", "**Adrenaline**", "Estrogen"] },
    { q: "The study of tissues is called:", opts: ["Cytology", "**Histology**", "Anatomy", "Ecology"] }
    
];

// --- 2015 E.C ---
QUESTIONS_DB.Natural.Biology["2015"] = [{ q: "Which of the following is a characteristic of all living organisms?", opts: ["Locomotion", "**Respiration**", "Photosynthesis", "Multicellularity"] },
    { q: "The scientist who proposed that all plants are made of cells was:", opts: ["Robert Hooke", "**Matthias Schleiden**", "Theodor Schwann", "Rudolf Virchow"] },
    { q: "Which cell organelle is known as the 'protein factory'?", opts: ["Nucleus", "Mitochondria", "**Ribosome**", "Lysosome"] },
    { q: "The movement of substances from low to high concentration using energy is:", opts: ["Diffusion", "Osmosis", "**Active transport**", "Facilitated diffusion"] },
    { q: "Which of the following is a double-membrane bound organelle?", opts: ["Ribosome", "Lysosome", "**Chloroplast**", "Endoplasmic reticulum"] },
    { q: "The phase of the cell cycle where organelles are duplicated is:", opts: ["**G1 phase**", "S phase", "G2 phase", "M phase"] },
    { q: "Which enzyme is responsible for breaking down starch into maltose?", opts: ["Pepsin", "Lipase", "**Amylase**", "Trypsin"] },
    { q: "The net gain of ATP during fermentation of one glucose molecule is:", opts: ["**2 ATP**", "4 ATP", "36 ATP", "38 ATP"] },
    { q: "Which of the following is a byproduct of anaerobic respiration in humans?", opts: ["Ethanol", "**Lactic acid**", "Oxygen", "Glucose"] },
    { q: "The process of crossing over occurs during which stage of meiosis?", opts: ["Prophase II", "**Prophase I**", "Metaphase I", "Anaphase I"] },
    { q: "Which base is found in RNA but absent in DNA?", opts: ["Thymine", "Adenine", "**Uracil**", "Guanine"] },
    { q: "The process of synthesizing mRNA from a DNA template is:", opts: ["Translation", "**Transcription**", "Replication", "Transformation"] },
    { q: "In a monohybrid cross, the phenotypic ratio of the F2 generation is:", opts: ["1:2:1", "**3:1**", "9:3:3:1", "1:1"] },
    { q: "The genetic disorder caused by the presence of an extra X chromosome in males (XXY) is:", opts: ["Down syndrome", "Turner syndrome", "**Klinefelter syndrome**", "Albinism"] },
    { q: "Which of the following is an example of an analogous structure?", opts: ["Human arm and whale flipper", "**Bird wing and insect wing**", "Bat wing and horse leg", "Appendix in humans"] },
    { q: "The primary function of the large intestine is:", opts: ["Protein digestion", "**Water absorption**", "Fat emulsification", "Starch breakdown"] },
    { q: "Which blood vessel carries deoxygenated blood from the heart to the lungs?", opts: ["Aorta", "Vena cava", "**Pulmonary artery**", "Pulmonary vein"] },
    { q: "The structural unit of the human kidney is the:", opts: ["Neuron", "**Nephron**", "Ureter", "Alveolus"] },
    { q: "Which hormone is responsible for the development of female secondary sex characteristics?", opts: ["Testosterone", "Progesterone", "**Estrogen**", "Insulin"] },
    { q: "The part of the brain that controls involuntary actions like breathing is the:", opts: ["Cerebrum", "Cerebellum", "**Medulla oblongata**", "Thalamus"] },
    { q: "Which of the following is a primary consumer in a food chain?", opts: ["Green plant", "**Caterpillar**", "Snake", "Hawk"] },
    { q: "The relationship between a lion and a zebra is an example of:", opts: ["Mutualism", "Commensalism", "**Predation**", "Parasitism"] },
    { q: "Which gas is mainly responsible for the depletion of the ozone layer?", opts: ["Carbon dioxide", "Methane", "**Chlorofluorocarbons (CFCs)**", "Nitrogen"] },
    { q: "The process by which an ecosystem gradually changes over time is:", opts: ["Evolution", "**Succession**", "Adaptation", "Selection"] },
    { q: "Which of the following is a non-renewable energy source?", opts: ["Solar", "Wind", "**Coal**", "Biomass"] },
    { q: "The functional unit of the human lungs where gas exchange occurs is:", opts: ["Bronchi", "Trachea", "**Alveoli**", "Pharynx"] },
    { q: "Which type of blood cell is involved in blood clotting?", opts: ["Red blood cell", "White blood cell", "**Platelet**", "Plasma cell"] },
    { q: "The hormone that regulates the amount of water reabsorbed by the kidneys is:", opts: ["Insulin", "Thyroxine", "**ADH (Antidiuretic Hormone)**", "Adrenaline"] },
    { q: "Which of the following is a characteristic of prokaryotic cells?", opts: ["Have a nucleus", "**Lack membrane-bound organelles**", "Have linear DNA", "Are always multicellular"] },
    { q: "The sequence of three bases on tRNA that pairs with an mRNA codon is the:", opts: ["Codon", "**Anticodon**", "Triplet", "Gene"] },
    { q: "Which of the following is a viral disease?", opts: ["Tuberculosis", "Cholera", "**Measles**", "Typhoid"] },
    { q: "The plant tissue responsible for transporting water and minerals is:", opts: ["Phloem", "**Xylem**", "Parenchyma", "Collenchyma"] },
    { q: "Which of the following is a Mendelian law of inheritance?", opts: ["Law of Use and Disuse", "**Law of Independent Assortment**", "Law of Natural Selection", "Cell Theory"] },
    { q: "The total energy stored in an ecosystem at a particular trophic level is:", opts: ["**Biomass**", "Biodiversity", "Bioremediation", "Biosphere"] },
    { q: "Which organelle is responsible for the detoxification of drugs and poisons?", opts: ["Rough ER", "**Smooth ER**", "Golgi apparatus", "Ribosome"] },
    { q: "The process by which green plants release water vapor into the atmosphere is:", opts: ["Photosynthesis", "**Transpiration**", "Respiration", "Inbibition"] },
    { q: "Which of the following is a primary producer?", opts: ["Fungi", "Earthworm", "**Phytoplankton**", "Zooplankton"] },
    { q: "The division of the cell nucleus is called:", opts: ["Cytokinesis", "**Karyokinesis**", "Apoptosis", "Necrosis"] },
    { q: "Which hormone is produced by the adrenal medulla during stress?", opts: ["Thyroxine", "**Adrenaline**", "Insulin", "Estrogen"] },
    { q: "The site of the Krebs cycle in the cell is the:", opts: ["Cytoplasm", "**Mitochondrial matrix**", "Thylakoid", "Ribosome"] },
    { q: "Which of the following is a polysaccharide found in animal livers?", opts: ["Starch", "Cellulose", "**Glycogen**", "Chitin"] },
    { q: "The study of the naming and classification of organisms is:", opts: ["Ecology", "**Taxonomy**", "Genetics", "Anatomy"] },
    { q: "Which nitrogenous base pairs with Guanine in DNA?", opts: ["Adenine", "Thymine", "**Cytosine**", "Uracil"] },
    { q: "The genetic makeup of an organism for a specific trait is its:", opts: ["Phenotype", "**Genotype**", "Allele", "Mutation"] },
    { q: "Which of the following is a function of the lymphatic system?", opts: ["Oxygen transport", "**Immunity**", "Pumping blood", "Starch digestion"] },
    { q: "The process of maintaining a stable internal environment is:", opts: ["Metabolism", "**Homeostasis**", "Growth", "Evolution"] },
    { q: "Which vitamin is essential for the health of the skin and eyes?", opts: ["**Vitamin A**", "Vitamin C", "Vitamin D", "Vitamin K"] },
    { q: "The first organism to colonize a bare rock is called a:", opts: ["Climax species", "**Pioneer species**", "Secondary species", "Parasite"] },
    { q: "Which of the following is a density-dependent limiting factor?", opts: ["Flood", "Forest fire", "**Competition**", "Earthquake"] },
    { q: "The enzyme that joins Okazaki fragments during DNA replication is:", opts: ["Helicase", "Polymerase", "**Ligase**", "Amylase"] },
    { q: "Which organelle is called the 'suicide bag' of the cell?", opts: ["Ribosome", "**Lysosome**", "Vacuole", "Nucleus"] },
    { q: "The gas used by organisms during aerobic respiration is:", opts: ["Carbon dioxide", "**Oxygen**", "Nitrogen", "Argon"] },
    { q: "Which part of the flower develops into a seed after fertilization?", opts: ["Ovary", "**Ovule**", "Stigma", "Anther"] },
    { q: "The structural unit of the human nervous system is the:", opts: ["Nephron", "**Neuron**", "Axon", "Synapse"] },
    { q: "Which of the following is a characteristic of mammals?", opts: ["Lay eggs", "**Possess mammary glands**", "Have scales", "Are cold-blooded"] },
    { q: "The process by which DNA makes an exact copy of itself is:", opts: ["Transcription", "Translation", "**Replication**", "Translocation"] },
    { q: "Which hormone increases blood glucose levels?", opts: ["Insulin", "**Glucagon**", "Thyroxine", "Oxytocin"] },
    { q: "The interaction where one species benefits and the other is harmed is:", opts: ["Mutualism", "Commensalism", "**Parasitism**", "Neutralism"] },
    { q: "Which of the following is a function of the skeletal system?", opts: ["Digestion", "**Production of blood cells**", "Nerve conduction", "Hormone secretion"] },
    { q: "The change in the heritable traits of a population over generations is:", opts: ["Mutation", "Selection", "**Evolution**", "Adaptation"] },
    { q: "Which gas is the most abundant in the Earth's atmosphere?", opts: ["Oxygen", "**Nitrogen**", "Carbon dioxide", "Argon"] },
    { q: "The study of tissues is called:", opts: ["Cytology", "**Histology**", "Microbiology", "Ecology"] },
    { q: "Which of the following is a primary consumer?", opts: ["Lion", "**Sheep**", "Green plant", "Eagle"] },
    { q: "The part of the eye that controls the diameter of the pupil is the:", opts: ["Retina", "Lens", "**Iris**", "Cornea"] },
    { q: "Which of the following is a non-communicable disease?", opts: ["Flu", "Malaria", "**Hypertension**", "Tuberculosis"] },
    { q: "The movement of a plant part in response to light is:", opts: ["Geotropism", "**Phototropism**", "Hydrotropism", "Chemotropism"] },
    { q: "Which of the following is an enzyme that digests proteins in the stomach?", opts: ["Amylase", "**Pepsin**", "Lipase", "Trypsin"] },
    { q: "The hormone that causes fruit ripening is:", opts: ["Auxin", "Cytokinin", "**Ethylene**", "Abscisic acid"] },
    { q: "Which of the following is a vertebrate?", opts: ["Snail", "Earthworm", "**Snake**", "Spider"] },
    { q: "The storage form of energy in plants is:", opts: ["Glycogen", "**Starch**", "Glucose", "Chitin"] },
    { q: "Which organelle is responsible for packaging proteins?", opts: ["Ribosome", "Nucleus", "**Golgi apparatus**", "Lysosome"] },
    { q: "The building blocks of nucleic acids are:", opts: ["Amino acids", "**Nucleotides**", "Fatty acids", "Glucose"] },
    { q: "Which of the following is a greenhouse gas?", opts: ["Oxygen", "Nitrogen", "**Carbon dioxide**", "Argon"] },
    { q: "The process of egg release from the ovary is:", opts: ["Menstruation", "**Ovulation**", "Fertilization", "Implantation"] },
    { q: "Which of the following is a primary producer?", opts: ["Grasshopper", "Bird", "**Algae**", "Fungi"] },
    { q: "The part of the leaf where gas exchange occurs is the:", opts: ["Xylem", "Phloem", "**Stomata**", "Cuticle"] },
    { q: "Which of the following is a function of white blood cells?", opts: ["Oxygen transport", "Blood clotting", "**Defense against pathogens**", "Heat regulation"] },
    { q: "The hormone that regulates the sleep-wake cycle is:", opts: ["Insulin", "**Melatonin**", "Thyroxine", "Estrogen"] },
    { q: "Which of the following is a monocot plant?", opts: ["Bean", "Mango", "**Maize**", "Pea"] },
    { q: "The genetic disorder characterized by the inability of blood to clot is:", opts: ["Sickle cell anemia", "Thalassemia", "**Hemophilia**", "Cystic fibrosis"] },
    { q: "Which of the following is a fungal disease?", opts: ["AIDS", "Cholera", "**Athlete's foot**", "Influenza"] },
    { q: "The process by which organisms produce offspring is:", opts: ["Growth", "**Reproduction**", "Development", "Metabolism"] },
    { q: "Which of the following is a renewable resource?", opts: ["Oil", "Natural gas", "**Water**", "Coal"] },
    { q: "The site of protein synthesis in a cell is the:", opts: ["Nucleus", "**Ribosome**", "Vacuole", "Mitochondria"] },
    { q: "Which of the following is a characteristic of all mammals?", opts: ["Lay eggs", "**Have hair or fur**", "Are cold-blooded", "Breath through gills"] },
    { q: "The process of programmed cell death is called:", opts: ["Necrosis", "**Apoptosis**", "Mitosis", "Meiosis"] },
    { q: "Which of the following is a primary consumer?", opts: ["Hawk", "Snake", "**Rabbit**", "Lion"] },
    { q: "The part of the eye that focus light on the retina is the:", opts: ["Iris", "Pupil", "**Lens**", "Cornea"] },
    { q: "Which of the following is an inherited trait?", opts: ["Scars", "Knowledge", "**Eye color**", "Muscle strength"] },
    { q: "The study of heredity and variation is:", opts: ["Ecology", "**Genetics**", "Evolution", "Taxonomy"] },
    { q: "Which of the following is a vestigial organ in humans?", opts: ["Heart", "Liver", "**Wisdom teeth**", "Stomach"] },
    { q: "The hormone produced by the pancreas to lower blood sugar is:", opts: ["Glucagon", "Adrenaline", "**Insulin**", "Thyroxine"] },
    { q: "Which of the following is a mammal that lives in water?", opts: ["Shark", "Tuna", "**Whale**", "Octopus"] },
    { q: "The functional unit of the human liver is the:", opts: ["Nephron", "Neuron", "**Liver lobule**", "Alveolus"] },
    { q: "Which gas is primarily responsible for global warming?", opts: ["Oxygen", "**Carbon dioxide**", "Nitrogen", "Helium"] },
    { q: "The phase of the cell cycle where DNA is replicated is:", opts: ["G1 phase", "**S phase**", "G2 phase", "M phase"] },
    { q: "Which of the following is an example of a decomposer?", opts: ["Green plant", "Cow", "**Mushroom**", "Tiger"] },
    { q: "The first step in the scientific method is:", opts: ["Hypothesis", "**Observation**", "Experiment", "Conclusion"] },
    { q: "Which of the following is a component of DNA?", opts: ["Amino acid", "Fatty acid", "**Deoxyribose sugar**", "Glycerol"] },
    { q: "The maintainance of constant body temperature is:", opts: ["Osmoregulation", "**Thermoregulation**", "Excretion", "Homeostasis"] }
    
];

// --- 2016 E.C ---
QUESTIONS_DB.Natural.Biology["2016"] = [{ q: "Which of the following is a key component of the cell theory?", opts: ["All cells have a nucleus", "**All living things are composed of cells**", "Cells form spontaneously", "Microbes are not cells"] },
    { q: "The movement of molecules from high to low concentration through a carrier protein is:", opts: ["Simple diffusion", "Osmosis", "**Facilitated diffusion**", "Active transport"] },
    { q: "Which organelle is responsible for synthesizing ribosomal RNA (rRNA)?", opts: ["Cytoplasm", "**Nucleolus**", "Golgi body", "Smooth ER"] },
    { q: "The fluid-filled space inside the chloroplast is called the:", opts: ["Grana", "Thylakoid", "**Stroma**", "Matrix"] },
    { q: "Which molecule provides the direct energy for muscle contraction?", opts: ["Glucose", "Glycogen", "**ATP**", "Creatine"] },
    { q: "The process of splitting a glucose molecule into two pyruvate molecules is:", opts: ["Krebs cycle", "Electron transport", "**Glycolysis**", "Fermentation"] },
    { q: "Which enzyme unzips the DNA double helix during replication?", opts: ["DNA polymerase", "**Helicase**", "Ligase", "RNA primase"] },
    { q: "The genetic code is described as 'degenerate' because:", opts: ["It changes over time", "It is universal", "**Multiple codons can code for one amino acid**", "It contains introns"] },
    { q: "A human cell containing 22 autosomes and a Y chromosome is a:", opts: ["Somatic cell", "Female gamete", "**Male gamete**", "Zygote"] },
    { q: "Which stage of meiosis involves the separation of homologous chromosomes?", opts: ["Anaphase II", "**Anaphase I**", "Metaphase I", "Prophase I"] },
    { q: "If a plant with red flowers (RR) is crossed with white flowers (rr), and all offspring are pink, this is:", opts: ["Dominance", "**Incomplete dominance**", "Codominance", "Linkage"] },
    { q: "Which of the following is a primary lymphoid organ?", opts: ["Spleen", "Lymph nodes", "**Bone marrow**", "Tonsils"] },
    { q: "The part of the flower that produces pollen is the:", opts: ["Stigma", "**Anther**", "Style", "Ovary"] },
    { q: "Which hormone is primarily responsible for the 'ripening' of fruits?", opts: ["Auxin", "Gibberellin", "**Ethylene**", "Abscisic acid"] },
    { q: "The transition of a community from bare rock to a forest is:", opts: ["Secondary succession", "**Primary succession**", "Evolution", "Eutrophication"] },
    { q: "Which of the following is an example of a density-independent limiting factor?", opts: ["Competition", "Predation", "**Flood**", "Parasitism"] },
    { q: "The sequence of energy transfer from one organism to another is a:", opts: ["Food web", "**Food chain**", "Trophic level", "Pyramid"] },
    { q: "Which gas is produced during the process of photosynthesis?", opts: ["Carbon dioxide", "**Oxygen**", "Nitrogen", "Methane"] },
    { q: "The structural unit of the human liver is the:", opts: ["Nephron", "Neuron", "**Hepatic lobule**", "Alveolus"] },
    { q: "Which valve prevents the backflow of blood from the left ventricle to the left atrium?", opts: ["Tricuspid", "**Bicuspid (Mitral)**", "Aortic", "Pulmonary"] },
    { q: "The gaseous exchange in insects occurs through a system of:", opts: ["Gills", "Lungs", "**Tracheae**", "Skin"] },
    { q: "Which part of the brain is the main center for homeostasis and hunger?", opts: ["Cerebrum", "Cerebellum", "**Hypothalamus**", "Medulla"] },
    { q: "The functional unit of contraction in a skeletal muscle is the:", opts: ["Myofibril", "**Sarcomere**", "Muscle fiber", "Actin"] },
    { q: "Which of the following is a lipid-soluble vitamin?", opts: ["Vitamin B1", "Vitamin C", "**Vitamin D**", "Vitamin B12"] },
    { q: "The process by which an embryo implants into the uterine wall is:", opts: ["Fertilization", "Ovulation", "**Implantation**", "Gastrulation"] },
    { q: "Which of the following is a bacterial disease?", opts: ["Influenza", "Malaria", "**Tuberculosis**", "AIDS"] },
    { q: "The theory that acquired characteristics can be inherited was proposed by:", opts: ["Darwin", "**Lamarck**", "Wallace", "Mendel"] },
    { q: "Which of the following is a vertebrate with a two-chambered heart?", opts: ["**Fish**", "Frog", "Lizard", "Bird"] },
    { q: "The enzyme that digests proteins in the small intestine is:", opts: ["Pepsin", "Amylase", "**Trypsin**", "Lipase"] },
    { q: "Which of the following is an abiotic component of an ecosystem?", opts: ["Fungi", "Bacteria", "**Soil pH**", "Plants"] },
    { q: "The storage form of carbohydrate in fungi is:", opts: ["Starch", "Cellulose", "**Glycogen**", "Chitin"] },
    { q: "Which organelle contains digestive enzymes to break down waste?", opts: ["Ribosome", "**Lysosome**", "Vacuole", "Golgi"] },
    { q: "The stage of the cell cycle where the cell performs its normal functions is:", opts: ["Mitosis", "S phase", "**G1 phase**", "Cytokinesis"] },
    { q: "Which hormone stimulates the production of red blood cells?", opts: ["Insulin", "**Erythropoietin**", "Adrenaline", "Thyroxine"] },
    { q: "The bond that connects two amino acids is a:", opts: ["Hydrogen bond", "Ionic bond", "**Peptide bond**", "Glycosidic bond"] },
    { q: "Which of the following is a C3 plant?", opts: ["Maize", "Sugarcane", "**Wheat**", "Sorghum"] },
    { q: "The non-coding sequences within a eukaryotic gene are called:", opts: ["Exons", "**Introns**", "Codons", "Promoters"] },
    { q: "Which part of the human ear is responsible for maintaining balance?", opts: ["Cochlea", "Eardrum", "**Semicircular canals**", "Ossicles"] },
    { q: "The process of water movement through a plant and its evaporation from leaves is:", opts: ["Osmosis", "**Transpiration**", "Translocation", "Respiration"] },
    { q: "Which kingdom includes organisms that are all multicellular heterotrophs without cell walls?", opts: ["Fungi", "Plantae", "**Animalia**", "Protista"] },
    { q: "The relationship where both organisms benefit is:", opts: ["Commensalism", "Parasitism", "**Mutualism**", "Competition"] },
    { q: "Which of the following is a greenhouse gas?", opts: ["Oxygen", "Nitrogen", "**Water vapor**", "Argon"] },
    { q: "The functional unit of the human kidney is the:", opts: ["Neuron", "**Nephron**", "Nephrite", "Ureter"] },
    { q: "Which enzyme is used in PCR to amplify DNA?", opts: ["DNA Ligase", "RNA Polymerase", "**Taq Polymerase**", "Helicase"] },
    { q: "The breakdown of glucose in the absence of oxygen produces:", opts: ["CO2 and H2O", "**Lactic acid or Ethanol**", "Pyruvate only", "Oxygen"] },
    { q: "Which of the following is a characteristic of an ideal respiratory surface?", opts: ["Thick walls", "**Large surface area**", "Dry surface", "Small blood supply"] },
    { q: "The hormone that maintains the lining of the uterus during pregnancy is:", opts: ["Estrogen", "**Progesterone**", "FSH", "LH"] },
    { q: "Which of the following is a primary consumer?", opts: ["Lion", "**Rabbit**", "Grass", "Eagle"] },
    { q: "The building blocks of DNA are:", opts: ["Amino acids", "**Nucleotides**", "Fatty acids", "Monosaccharides"] },
    { q: "Which organelle is called the 'powerhouse of the cell'?", opts: ["Nucleus", "Ribosome", "**Mitochondria**", "Chloroplast"] },
    { q: "The study of fossils is called:", opts: ["Ecology", "Genetics", "**Paleontology**", "Anatomy"] },
    { q: "Which of the following is a function of the lymphatic system?", opts: ["Oxygen transport", "**Defense against disease**", "Digestion of proteins", "Heat production"] },
    { q: "The movement of a plant in response to touch is:", opts: ["Phototropism", "Geotropism", "**Thigmotropism**", "Hydrotropism"] },
    { q: "Which part of the leaf is the primary site of photosynthesis?", opts: ["Epidermis", "**Palisade mesophyll**", "Spongy mesophyll", "Vascular bundle"] },
    { q: "The ratio of phenotypes in the F2 generation of a dihybrid cross is:", opts: ["3:1", "1:2:1", "**9:3:3:1**", "1:1"] },
    { q: "Which of the following is a viral disease?", opts: ["Cholera", "Typhoid", "**Rabies**", "Tetanus"] },
    { q: "The process of programmed cell death is:", opts: ["Necrosis", "**Apoptosis**", "Lysis", "Phagocytosis"] },
    { q: "Which hormone is responsible for the 'fight or flight' response?", opts: ["Insulin", "Thyroxine", "**Adrenaline**", "Estrogen"] },
    { q: "The first stage of aerobic respiration is:", opts: ["Krebs cycle", "Electron transport", "**Glycolysis**", "Fermentation"] },
    { q: "Which of the following is a renewable energy source?", opts: ["Coal", "Oil", "**Geothermal**", "Natural gas"] },
    { q: "The scientist who discovered the structure of DNA (with Crick) was:", opts: ["Mendel", "Darwin", "**Watson**", "Pasteur"] },
    { q: "Which type of RNA brings amino acids to the ribosome?", opts: ["mRNA", "**tRNA**", "rRNA", "snRNA"] },
    { q: "The physical appearance of an organism is its:", opts: ["Genotype", "**Phenotype**", "Allele", "Locus"] },
    { q: "Which of the following is a function of red blood cells?", opts: ["Clotting", "Immunity", "**Oxygen transport**", "Hormone production"] },
    { q: "The structural unit of the nervous system is the:", opts: ["Nephron", "**Neuron**", "Axon", "Dendrite"] },
    { q: "Which of the following is a monocot plant?", opts: ["Bean", "**Grass**", "Mango", "Pea"] },
    { q: "The process of making mRNA from DNA is:", opts: ["Translation", "**Transcription**", "Replication", "Inversion"] },
    { q: "Which of the following is a scavenger?", opts: ["Lion", "**Vulture**", "Cow", "Rabbit"] },
    { q: "The role an organism plays in its habitat is its:", opts: ["Biome", "Ecosystem", "**Niche**", "Community"] },
    { q: "Which relationship is (+, -)?", opts: ["Mutualism", "Commensalism", "**Parasitism**", "Competition"] },
    { q: "The most abundant gas in the atmosphere is:", opts: ["Oxygen", "**Nitrogen**", "Carbon dioxide", "Argon"] },
    { q: "Which part of the brain controls voluntary movement?", opts: ["**Cerebrum**", "Cerebellum", "Medulla", "Thalamus"] },
    { q: "The process by which plants make food is:", opts: ["Respiration", "**Photosynthesis**", "Digestion", "Absorption"] },
    { q: "Which enzyme digests fats?", opts: ["Amylase", "Pepsin", "**Lipase**", "Trypsin"] },
    { q: "The pacemaker of the heart is the:", opts: ["**SA node**", "AV node", "Bundle of His", "Ventricle"] },
    { q: "Which gas is used for respiration?", opts: ["Carbon dioxide", "**Oxygen**", "Nitrogen", "Hydrogen"] },
    { q: "The hormone that regulates blood sugar is:", opts: ["Adrenaline", "**Insulin**", "Thyroxine", "Estrogen"] },
    { q: "The study of insects is:", opts: ["Ornithology", "**Entomology**", "Herpetology", "Botany"] },
    { q: "Which of the following is a primary consumer?", opts: ["Lion", "**Zebra**", "Grass", "Hawk"] },
    { q: "The process of maintaining internal stability is:", opts: ["Metabolism", "**Homeostasis**", "Growth", "Evolution"] },
    { q: "The part of the eye that focus light is the:", opts: ["Iris", "Retina", "**Lens**", "Pupil"] },
    { q: "Which of the following is a renewable resource?", opts: ["Coal", "Gas", "**Sunlight**", "Iron"] },
    { q: "The study of heredity is:", opts: ["Ecology", "**Genetics**", "Anatomy", "Physiology"] },
    { q: "Which of the following is a vestigial organ?", opts: ["Heart", "Lungs", "**Appendix**", "Kidney"] },
    { q: "Which gas is primarily responsible for global warming?", opts: ["Oxygen", "**Carbon dioxide**", "Nitrogen", "Argon"] },
    { q: "The phase where DNA is replicated is:", opts: ["G1", "**S phase**", "G2", "M phase"] },
    { q: "Which of the following is a decomposer?", opts: ["Grass", "Cow", "**Bacteria**", "Tiger"] },
    { q: "The unit of classification is:", opts: ["Kingdom", "Class", "**Species**", "Genus"] },
    { q: "Which organelle is the site of protein synthesis?", opts: ["Nucleus", "**Ribosome**", "Vacuole", "Mitochondria"] },
    { q: "The hormone for fruit ripening is:", opts: ["Auxin", "Cytokinin", "**Ethylene**", "Gibberellin"] },
    { q: "Which of the following is a mammal?", opts: ["Shark", "Frog", "**Bat**", "Snake"] },
    { q: "The sugar in DNA is:", opts: ["Ribose", "**Deoxyribose**", "Glucose", "Fructose"] },
    { q: "Which of the following is an inherited trait?", opts: ["Scar", "Language", "**Blood group**", "Muscle size"] },
    { q: "The process of cell division for growth is:", opts: ["Meiosis", "**Mitosis**", "Fertilization", "Budding"] },
    { q: "Which of the following is a fungal disease?", opts: ["Flu", "Cholera", "**Ringworm**", "Malaria"] },
    { q: "The part of the heart that pumps blood to the body is:", opts: ["Right atrium", "Right ventricle", "Left atrium", "**Left ventricle**"] },
    { q: "Which component of blood carries oxygen?", opts: ["Plasma", "White cells", "**Hemoglobin**", "Platelets"] },
    { q: "The energy-releasing process in cells is:", opts: ["Photosynthesis", "**Respiration**", "Digestion", "Excretion"] },
    { q: "Which of the following is a vertebrate?", opts: ["Spider", "Snail", "**Bird**", "Earthworm"] },
    { q: "The study of the environment is:", opts: ["Genetics", "**Ecology**", "Anatomy", "Botany"] }
    
];

// --- 2017 E.C ---
QUESTIONS_DB.Natural.Biology["2017"] = [{ q: "Which of the following is a primary function of the smooth endoplasmic reticulum?", opts: ["Protein synthesis", "**Lipid synthesis**", "Genetic storage", "ATP production"] },
    { q: "The movement of water out of a cell placed in a hypertonic solution is:", opts: ["Diffusion", "**Osmosis**", "Active transport", "Endocytosis"] },
    { q: "Which organelle is responsible for capturing solar energy in plant cells?", opts: ["Mitochondria", "**Chloroplast**", "Ribosome", "Vacuole"] },
    { q: "The structure that regulates the entry and exit of materials in a cell is the:", opts: ["Cell wall", "**Plasma membrane**", "Nuclear envelope", "Cytoplasm"] },
    { q: "During which stage of the cell cycle is DNA synthesized?", opts: ["G1 phase", "**S phase**", "G2 phase", "M phase"] },
    { q: "The enzyme that facilitates the addition of nucleotides during DNA replication is:", opts: ["Helicase", "**DNA polymerase**", "Ligase", "Amylase"] },
    { q: "Which of the following is an example of a prokaryotic organism?", opts: ["Yeast", "Amoeba", "**Bacteria**", "Mushroom"] },
    { q: "The process of converting glucose into two molecules of pyruvate is:", opts: ["Krebs cycle", "Electron transport", "**Glycolysis**", "Fermentation"] },
    { q: "Which molecule is known as the 'universal energy currency'?", opts: ["DNA", "RNA", "**ATP**", "Glucose"] },
    { q: "In meiosis, the number of chromosomes in the daughter cells is:", opts: ["Doubled", "Maintained", "**Halved**", "Tripled"] },
    { q: "Which of the following is a nitrogenous base found only in RNA?", opts: ["Adenine", "Thymine", "**Uracil**", "Cytosine"] },
    { q: "The physical expression of a gene is called the:", opts: ["Genotype", "**Phenotype**", "Allele", "Locus"] },
    { q: "Which of the following describes an organism with two identical alleles for a trait?", opts: ["Heterozygous", "**Homozygous**", "Haploid", "Diploid"] },
    { q: "The theory of evolution by natural selection was proposed by:", opts: ["Lamarck", "Mendel", "**Darwin**", "Pasteur"] },
    { q: "Which of the following is a biotic factor in an ecosystem?", opts: ["Temperature", "Rainfall", "**Predators**", "Soil minerals"] },
    { q: "The position of an organism in a food chain is its:", opts: ["Habitat", "Niche", "**Trophic level**", "Biome"] },
    { q: "Which of the following is a primary producer?", opts: ["Grasshopper", "Snake", "**Green plant**", "Fungi"] },
    { q: "The relationship where both organisms benefit is called:", opts: ["Commensalism", "Parasitism", "**Mutualism**", "Competition"] },
    { q: "Which gas is primarily released during aerobic respiration?", opts: ["Oxygen", "**Carbon dioxide**", "Nitrogen", "Methane"] },
    { q: "The main site of gas exchange in humans is the:", opts: ["Bronchi", "Trachea", "**Alveoli**", "Pharynx"] },
    { q: "Which blood vessel carries oxygenated blood away from the heart?", opts: ["Vein", "**Artery**", "Capillary", "Venule"] },
    { q: "The functional unit of the human nervous system is the:", opts: ["Nephron", "**Neuron**", "Axon", "Dendrite"] },
    { q: "Which hormone regulates the 'fight or flight' response?", opts: ["Insulin", "Thyroxine", "**Adrenaline**", "Estrogen"] },
    { q: "The part of the brain responsible for higher mental activities like reasoning is the:", opts: ["**Cerebrum**", "Cerebellum", "Medulla", "Thalamus"] },
    { q: "Which of the following is a non-renewable resource?", opts: ["Solar energy", "Wind power", "**Petroleum**", "Biomass"] },
    { q: "The increase in the Earth's average temperature due to greenhouse gases is:", opts: ["Acid rain", "**Global warming**", "Ozone depletion", "Eutrophication"] },
    { q: "Which vitamin is essential for blood clotting?", opts: ["Vitamin A", "Vitamin C", "Vitamin D", "**Vitamin K**"] },
    { q: "The process of maintaining a stable internal environment is:", opts: ["Metabolism", "**Homeostasis**", "Excretion", "Adaptation"] },
    { q: "Which of the following is a viral disease?", opts: ["Tuberculosis", "Cholera", "**Hepatitis**", "Syphilis"] },
    { q: "The enzyme that unzips the DNA double helix is:", opts: ["Polymerase", "**Helicase**", "Ligase", "Protease"] },
    { q: "Which of the following is a characteristic of enzymes?", opts: ["Consumed in reactions", "**Highly specific**", "Made of lipids", "Slow down reactions"] },
    { q: "The genetic material of a virus is enclosed in a protein coat called a:", opts: ["Cell wall", "**Capsid**", "Envelope", "Nucleus"] },
    { q: "Which of the following is a primary consumer?", opts: ["Lion", "**Rabbit**", "Grass", "Eagle"] },
    { q: "The process by which plants lose water vapor through stomata is:", opts: ["Evaporation", "**Transpiration**", "Guttation", "Respiration"] },
    { q: "Which part of the eye is sensitive to light?", opts: ["Cornea", "Lens", "**Retina**", "Iris"] },
    { q: "The study of heredity and variation is known as:", opts: ["Ecology", "**Genetics**", "Taxonomy", "Physiology"] },
    { q: "Which of the following is a polysaccharide stored in plants?", opts: ["Glycogen", "**Starch**", "Cellulose", "Chitin"] },
    { q: "The structural unit of bone is the:", opts: ["Neuron", "Sarcomere", "**Osteon**", "Nephron"] },
    { q: "Which of the following is a function of the liver?", opts: ["Urine storage", "**Bile production**", "Insulin secretion", "Oxygen transport"] },
    { q: "The phase of mitosis where chromosomes align at the center is:", opts: ["Prophase", "**Metaphase**", "Anaphase", "Telophase"] },
    { q: "Which type of RNA carries the genetic code from DNA to the ribosome?", opts: ["tRNA", "rRNA", "**mRNA**", "snRNA"] },
    { q: "An organism that breaks down dead organic matter is a:", opts: ["Producer", "Herbivore", "Carnivore", "**Decomposer**"] },
    { q: "Which gas is used by plants during photosynthesis?", opts: ["Oxygen", "**Carbon dioxide**", "Nitrogen", "Hydrogen"] },
    { q: "The hormone that lowers blood sugar levels is:", opts: ["Glucagon", "Adrenaline", "**Insulin**", "Thyroxine"] },
    { q: "Which of the following is a vertebrate with a three-chambered heart?", opts: ["Fish", "**Frog**", "Bird", "Human"] },
    { q: "The maintenance of water balance in the body is:", opts: ["Thermoregulation", "**Osmoregulation**", "Excretion", "Digestion"] },
    { q: "Which part of the flower develops into a fruit?", opts: ["Stigma", "Anther", "**Ovary**", "Petal"] },
    { q: "The science of classifying organisms is:", opts: ["Genetics", "**Taxonomy**", "Ecology", "Anatomy"] },
    { q: "Which of the following is a renewable resource?", opts: ["Coal", "Oil", "**Sunlight**", "Natural gas"] },
    { q: "The sequence of three bases on mRNA is called a:", opts: ["Anticodon", "**Codon**", "Gene", "Allele"] },
    { q: "Which organelle is responsible for intracellular digestion?", opts: ["Ribosome", "**Lysosome**", "Vacuole", "Golgi"] },
    { q: "The process of cell division for gamete production is:", opts: ["Mitosis", "**Meiosis**", "Binary fission", "Budding"] },
    { q: "Which of the following is a function of white blood cells?", opts: ["Oxygen transport", "Clotting", "**Immunity**", "Nutrient transport"] },
    { q: "The site of protein synthesis is the:", opts: ["Nucleus", "**Ribosome**", "Lysosome", "Mitochondria"] },
    { q: "Which hormone is responsible for male secondary sex traits?", opts: ["Estrogen", "Progesterone", "**Testosterone**", "Insulin"] },
    { q: "The study of tissues is:", opts: ["Cytology", "**Histology**", "Ecology", "Microbiology"] },
    { q: "Which of the following is a monocot plant?", opts: ["Bean", "Pea", "**Corn**", "Mango"] },
    { q: "The movement of sucrose through phloem is called:", opts: ["Transpiration", "**Translocation**", "Diffusion", "Osmosis"] },
    { q: "Which valve is located between the right atrium and right ventricle?", opts: ["Bicuspid", "**Tricuspid**", "Aortic", "Pulmonary"] },
    { q: "The end product of protein digestion is:", opts: ["Glucose", "Fatty acids", "**Amino acids**", "Glycerol"] },
    { q: "Which part of the ear contains the organ of Corti?", opts: ["Eardrum", "Ossicles", "**Cochlea**", "Pinna"] },
    { q: "The process of DNA replication is said to be:", opts: ["Conservative", "**Semi-conservative**", "Dispersive", "Random"] },
    { q: "Which of the following is a scavenger?", opts: ["Lion", "**Hyena**", "Zebra", "Cow"] },
    { q: "The role an organism plays in its community is its:", opts: ["Habitat", "**Niche**", "Biome", "Ecosystem"] },
    { q: "Which relationship is (+, 0)?", opts: ["Mutualism", "**Commensalism**", "Parasitism", "Competition"] },
    { q: "The most abundant gas in the atmosphere is:", opts: ["Oxygen", "**Nitrogen**", "Carbon dioxide", "Argon"] },
    { q: "Which part of the brain controls balance?", opts: ["Cerebrum", "**Cerebellum**", "Medulla", "Thalamus"] },
    { q: "Which enzyme is found in human saliva?", opts: ["Pepsin", "Lipase", "**Amylase**", "Trypsin"] },
    { q: "The building blocks of proteins are:", opts: ["Nucleotides", "**Amino acids**", "Monosaccharides", "Lipids"] },
    { q: "Which gas is primarily responsible for the ozone hole?", opts: ["CO2", "Methane", "**CFCs**", "Nitrous oxide"] },
    { q: "The phase of the cell cycle where cytoplasm divides is:", opts: ["Mitosis", "Meiosis", "**Cytokinesis**", "Interphase"] },
    { q: "Which of the following is a primary consumer?", opts: ["Hawk", "Snake", "**Grasshopper**", "Lion"] },
    { q: "The part of the eye that focus light is the:", opts: ["Iris", "Pupil", "**Lens**", "Retina"] },
    { q: "Which of the following is an inherited trait?", opts: ["Scar", "Language", "**Blood type**", "Skill"] },
    { q: "The study of the environment is:", opts: ["Genetics", "**Ecology**", "Anatomy", "Physiology"] },
    { q: "Which of the following is a vestigial organ in humans?", opts: ["Heart", "Lungs", "**Appendix**", "Kidney"] },
    { q: "Which hormone is produced by the pancreas to raise blood sugar?", opts: ["Insulin", "**Glucagon**", "Thyroxine", "Adrenaline"] },
    { q: "The functional unit of the human lung is the:", opts: ["Bronchi", "Trachea", "**Alveolus**", "Diaphragm"] },
    { q: "Which gas makes up about 21% of the atmosphere?", opts: ["Nitrogen", "**Oxygen**", "Argon", "Carbon dioxide"] },
    { q: "The phase where chromosomes separate is:", opts: ["Prophase", "Metaphase", "**Anaphase**", "Telophase"] },
    { q: "Which of the following is a decomposer?", opts: ["Grass", "Rabbit", "**Bacteria**", "Tiger"] },
    { q: "The unit of life is the:", opts: ["Atom", "Molecule", "**Cell**", "Tissue"] },
    { q: "Which organelle is the site of aerobic respiration?", opts: ["Ribosome", "Chloroplast", "**Mitochondria**", "Nucleus"] },
    { q: "Which of the following is a function of the skeleton?", opts: ["Digestion", "**Protection of organs**", "Excretion", "Nerve impulse"] },
    { q: "The sugar found in DNA is:", opts: ["Ribose", "**Deoxyribose**", "Glucose", "Fructose"] },
    { q: "Which of the following is a mammal?", opts: ["Shark", "Frog", "**Whale**", "Snake"] },
    { q: "The hormone for fruit ripening is:", opts: ["Auxin", "Cytokinin", "**Ethylene**", "Gibberellin"] },
    { q: "The process of making food using light is:", opts: ["Respiration", "**Photosynthesis**", "Digestion", "Absorption"] },
    { q: "Which component of blood is responsible for clotting?", opts: ["RBC", "WBC", "**Platelets**", "Plasma"] },
    { q: "The study of heredity is:", opts: ["Ecology", "**Genetics**", "Anatomy", "Botany"] },
    { q: "Which of the following is a vertebrate?", opts: ["Spider", "Snail", "**Snake**", "Earthworm"] },
    { q: "The energy currency of the cell is:", opts: ["DNA", "RNA", "**ATP**", "Glucose"] },
    { q: "Which gas is used for aerobic respiration?", opts: ["Carbon dioxide", "**Oxygen**", "Nitrogen", "Methane"] },
    { q: "The hormone that regulates metabolism is:", opts: ["Insulin", "**Thyroxine**", "Adrenaline", "Estrogen"] },
    { q: "The study of fossils is:", opts: ["Ecology", "Genetics", "**Paleontology**", "Anatomy"] },
    { q: "Which of the following is a primary consumer?", opts: ["Lion", "**Cow**", "Grass", "Eagle"] },
    { q: "The maintainance of internal stability is:", opts: ["Metabolism", "**Homeostasis**", "Growth", "Evolution"] },
    { q: "Which of the following is a fungal disease?", opts: ["Flu", "Cholera", "**Athlete's foot**", "Malaria"] },
    { q: "The process of cell division for growth is:", opts: ["Meiosis", "**Mitosis**", "Fertilization", "Budding"] },
    { q: "The part of the eye that controls light intensity is the:", opts: ["Retina", "Lens", "**Iris**", "Cornea"] }
    
];
