// 2017 Chemistry First Round Model Exam - Full 80 Questions
QUESTIONS_DB.ModelExams.Natural["Chemistry"] = {
    "Model_2017_Round_1": [
        { "q": "Which of the following is a physical property of matter?", "opts": ["Flammability", "Reactivity with water", "Solubility in acids", "**Density**"] },
        { "q": "The fundamental particle of an element that retains its chemical properties is:", "opts": ["Molecule", "**Atom**", "Proton", "Neutron"] },
        { "q": "According to Dalton’s atomic theory, atoms of the same element are:", "opts": ["Different in mass", "**Identical in size, mass and chemical properties**", "Divisible into smaller particles", "Able to be created during chemical reactions"] },
        { "q": "Which subatomic particle has a negative charge?", "opts": ["Proton", "Neutron", "**Electron**", "Nucleus"] },
        { "q": "The atomic number of an element is determined by the number of:", "opts": ["Neutrons", "**Protons**", "Electrons", "Protons and Neutrons"] },
        { "q": "Isotopes are atoms of the same element with different numbers of:", "opts": ["Protons", "Electrons", "**Neutrons**", "Positrons"] },
        { "q": "Which region of the electromagnetic spectrum has the highest energy?", "opts": ["Radio waves", "Infrared", "Visible light", "**Gamma rays**"] },
        { "q": "The principle that states no two electrons in an atom can have the same four quantum numbers is:", "opts": ["Aufbau principle", "Hund's rule", "**Pauli exclusion principle**", "Heisenberg uncertainty principle"] },
        { "q": "The maximum number of electrons that can occupy the 3d subshell is:", "opts": ["2", "6", "**10**", "14"] },
        { "q": "Which group of elements is known as the Halogens?", "opts": ["Group 1", "Group 2", "Group 16", "**Group 17**"] },
        { "q": "The energy required to remove an electron from a gaseous atom is called:", "opts": ["Electronegativity", "Electron affinity", "**Ionization energy**", "Lattice energy"] },
        { "q": "Which of the following elements has the highest electronegativity?", "opts": ["Lithium", "Carbon", "Oxygen", "**Fluorine**"] },
        { "q": "A chemical bond formed by the sharing of electrons is called:", "opts": ["Ionic bond", "**Covalent bond**", "Metallic bond", "Hydrogen bond"] },
        { "q": "Which molecule contains a double covalent bond?", "opts": ["H2", "Cl2", "**O2**", "N2"] },
        { "q": "The geometry of a methane (CH4) molecule is:", "opts": ["Linear", "Bent", "Trigonal planar", "**Tetrahedral**"] },
        { "q": "Which of the following is a polar molecule?", "opts": ["CO2", "CH4", "**H2O**", "BF3"] },
        { "q": "The SI unit for the amount of substance is:", "opts": ["Gram", "Liter", "**Mole**", "Pascal"] },
        { "q": "What is the molar mass of Water (H2O)? (H=1, O=16)", "opts": ["10 g/mol", "16 g/mol", "**18 g/mol**", "20 g/mol"] },
        { "q": "A solution with a pH of 3 is considered:", "opts": ["**Strongly acidic**", "Weakly acidic", "Neutral", "Basic"] },
        { "q": "In the reaction: Zn + CuSO4 -> ZnSO4 + Cu, Zinc is:", "opts": ["Oxidized", "Reduced", "**The reducing agent**", "The oxidizing agent"] },
        { "q": "The standard state of temperature and pressure (STP) is:", "opts": ["0°C and 2 atm", "**0°C and 1 atm**", "25°C and 1 atm", "100°C and 1 atm"] },
        { "q": "Which law states that the volume of a gas is inversely proportional to its pressure at constant temperature?", "opts": ["Charles's Law", "**Boyle's Law**", "Avogadro's Law", "Gay-Lussac's Law"] },
        { "q": "The process of a solid changing directly into a gas is called:", "opts": ["Melting", "Evaporation", "**Sublimation**", "Condensation"] },
        { "q": "A catalyst increases the rate of a reaction by:", "opts": ["Increasing the temperature", "Increasing the concentration", "**Lowering the activation energy**", "Changing the equilibrium constant"] },
        { "q": "Which of the following is an endothermic process?", "opts": ["Combustion of wood", "Freezing of water", "**Melting of ice**", "Neutralization reaction"] },
        { "q": "The main component of natural gas is:", "opts": ["Ethane", "Propane", "**Methane**", "Butane"] },
        { "q": "Which functional group is present in alcohols?", "opts": ["-COOH", "-CHO", "**-OH**", "-NH2"] },
        { "q": "The common name for Ethanoic acid is:", "opts": ["Formic acid", "**Acetic acid**", "Butyric acid", "Propionic acid"] },
        { "q": "Which of the following is a characteristic of transition metals?", "opts": ["Low melting points", "Fixed oxidation states", "**Formation of colored compounds**", "Low density"] },
        { "q": "The most abundant element in the Earth's atmosphere is:", "opts": ["Oxygen", "**Nitrogen**", "Argon", "Carbon dioxide"] },
        { "q": "Which gas is responsible for the 'rotten egg' smell?", "opts": ["CO2", "NH3", "**H2S**", "SO2"] },
        { "q": "Hard water contains high concentrations of:", "opts": ["Sodium and Potassium ions", "**Calcium and Magnesium ions**", "Iron and Copper ions", "Chloride and Sulfate ions"] },
        { "q": "The process used to separate components of crude oil is:", "opts": ["Filtration", "Crystallization", "**Fractional distillation**", "Chromatography"] },
        { "q": "Which of the following is a greenhouse gas?", "opts": ["Nitrogen", "Oxygen", "**Methane**", "Argon"] },
        { "q": "The oxidation number of Oxygen in H2O2 is:", "opts": ["-2", "**-1**", "0", "+1"] },
        { "q": "A substance that can act as both an acid and a base is:", "opts": ["Neutral", "**Amphoteric**", "Indicator", "Buffer"] },
        { "q": "The study of carbon-containing compounds is called:", "opts": ["Inorganic chemistry", "Physical chemistry", "**Organic chemistry**", "Analytical chemistry"] },
        { "q": "The simplest alkene is:", "opts": ["Methane", "**Ethene**", "Ethyne", "Propene"] },
        { "q": "Which type of reaction occurs when an acid reacts with a base?", "opts": ["Addition", "Substitution", "**Neutralization**", "Redox"] },
        { "q": "The concentration of a solution expressed in moles of solute per liter of solution is:", "opts": ["Molality", "**Molarity**", "Normality", "Mole fraction"] },
        { "q": "Which of the following is an example of a colloid?", "opts": ["Salt water", "Sugar solution", "**Milk**", "Air"] },
        { "q": "The movement of solvent molecules through a semi-permeable membrane is:", "opts": ["Diffusion", "**Osmosis**", "Effusion", "Transmutation"] },
        { "q": "In an electrochemical cell, oxidation occurs at the:", "opts": ["**Anode**", "Cathode", "Salt bridge", "Electrolyte"] },
        { "q": "Which metal is used as a sacrificial anode to prevent rusting of iron?", "opts": ["Copper", "Silver", "Gold", "**Magnesium**"] },
        { "q": "The monomer of PVC is:", "opts": ["Ethene", "Propene", "**Vinyl chloride**", "Styrene"] },
        { "q": "Which of the following is a natural polymer?", "opts": ["Nylon", "Polythene", "**Starch**", "Bakelite"] },
        { "q": "The primary source of energy in the sun is:", "opts": ["Chemical combustion", "Nuclear fission", "**Nuclear fusion**", "Radioactive decay"] },
        { "q": "Which radioactive particle has the highest penetrating power?", "opts": ["Alpha", "Beta", "**Gamma**", "Neutron"] },
        { "q": "The time required for half of a radioactive sample to decay is:", "opts": ["Lifetime", "**Half-life**", "Decay constant", "Mean life"] },
        { "q": "Which law states that energy cannot be created or destroyed?", "opts": ["**First law of thermodynamics**", "Second law of thermodynamics", "Hess's law", "Le Chatelier's principle"] },
        { "q": "The entropy of a perfectly crystalline substance at absolute zero is:", "opts": ["Maximum", "Constant", "**Zero**", "Infinite"] },
        { "q": "Which of the following is a saturated hydrocarbon?", "opts": ["Ethene", "Ethyne", "**Ethane**", "Benzene"] },
        { "q": "The bond angle in a water molecule is approximately:", "opts": ["180°", "120°", "109.5°", "**104.5°**"] },
        { "q": "Which force is responsible for the high boiling point of water?", "opts": ["Ionic bonds", "Dipole-dipole forces", "**Hydrogen bonding**", "London dispersion forces"] },
        { "q": "The acid found in lemons is:", "opts": ["Lactic acid", "Acetic acid", "**Citric acid**", "Tartaric acid"] },
        { "q": "What is the pH of a 0.01 M HCl solution?", "opts": ["1", "**2**", "3", "4"] },
        { "q": "Which of the following salts will form a basic solution in water?", "opts": ["NaCl", "NH4Cl", "**CH3COONa**", "KNO3"] },
        { "q": "The electrolysis of brine (NaCl solution) produces:", "opts": ["H2 and O2", "**Cl2, H2 and NaOH**", "Na and Cl2", "HCl and O2"] },
        { "q": "Which indicator turns pink in basic solutions?", "opts": ["Methyl orange", "Litmus", "**Phenolphthalein**", "Bromothymol blue"] },
        { "q": "The process of extracting a metal from its ore is called:", "opts": ["Calcination", "Roasting", "**Metallurgy**", "Smelting"] },
        { "q": "The main ore of Aluminum is:", "opts": ["Hematite", "Magnetite", "**Bauxite**", "Galena"] },
        { "q": "Which allotrope of carbon is used as a lubricant?", "opts": ["Diamond", "**Graphite**", "Fullerene", "Coke"] },
        { "q": "The gas produced when reactive metals react with acids is:", "opts": ["Oxygen", "Carbon dioxide", "**Hydrogen**", "Nitrogen"] },
        { "q": "Which of the following is a strong base?", "opts": ["NH3", "Al(OH)3", "**KOH**", "Mg(OH)2"] },
        { "q": "The percentage of Nitrogen in Urea [CO(NH2)2] is approximately:", "opts": ["20%", "35%", "**46%**", "60%"] },
        { "q": "Which functional group is characteristic of ketones?", "opts": ["-OH", "-COOH", "**>C=O**", "-CHO"] },
        { "q": "The reaction: CH4 + Cl2 -> CH3Cl + HCl is an example of:", "opts": ["Addition", "**Substitution**", "Elimination", "Polymerization"] },
        { "q": "Which of the following is used as an antacid?", "opts": ["NaOH", "HCl", "**Mg(OH)2**", "H2SO4"] },
        { "q": "The catalyst used in the Haber process is:", "opts": ["Vanadium pentoxide", "Platinum", "**Iron**", "Nickel"] },
        { "q": "What is the shape of a PCl5 molecule?", "opts": ["Octahedral", "**Trigonal bipyramidal**", "Square planar", "Tetrahedral"] },
        { "q": "Which of the following is an intensive property?", "opts": ["Mass", "Volume", "**Temperature**", "Internal energy"] },
        { "q": "The units for the rate constant of a first-order reaction are:", "opts": ["M/s", "M^-1 s^-1", "**s^-1**", "M^2/s"] },
        { "q": "Which principle explains the shift in equilibrium when conditions change?", "opts": ["Hund's rule", "Aufbau principle", "**Le Chatelier's principle**", "Graham's law"] },
        { "q": "The gas law constant (R) has a value of approximately:", "opts": ["6.022", "9.81", "**0.0821**", "3.14"] },
        { "q": "Which element is essential for all organic compounds?", "opts": ["Oxygen", "Nitrogen", "**Carbon**", "Hydrogen"] },
        { "q": "Which region of electromagnetic spectrum is capable of inducing electron transition with the greatest energy?", "opts": ["Orange", "Red", "**Violet**", "Green"] },
        { "q": "What is the wavelength of the yellow sodium emission, which has a frequency of 5.09 x 10^14 s^-1? (C = 3 x 10^8 m/s)", "opts": ["400nm", "**589nm**", "670nm", "890nm"] },
        { "q": "The charge-carriers in metallic conduction are:", "opts": ["Anions only", "Cations and anions", "**Delocalized electrons**", "All of the above"] },
        { "q": "Which of the following ions is difficult to oxidized?", "opts": ["**Na+**", "Ag+", "H+", "Fe+3"] },
        { "q": "Which one of the following metals is unreactive with acid or water?", "opts": ["Lead", "Zinc", "Sodium", "**Copper**"] }
    ]
};
