// 2017 Economics First Round Model Exam - Full 80 Questions
if (!QUESTIONS_DB.ModelExams) QUESTIONS_DB.ModelExams = { "Natural": {}, "Social": {} };

QUESTIONS_DB.ModelExams.Social["Economics"] = {
    "Model_2017_Round_1": [
        { "q": "Which of the following is a microeconomic topic?", "opts": ["The inflation rate", "**The price of a specific brand of shoes**", "The national unemployment rate", "Total output of the economy"] },
        { "q": "The fundamental economic problem that all societies face is:", "opts": ["Inflation", "Unemployment", "**Scarcity**", "Poverty"] },
        { "q": "The law of demand states that, other things being equal:", "opts": ["As price increases, demand increases", "**As price increases, quantity demanded decreases**", "As income increases, demand decreases", "As price decreases, quantity demanded decreases"] },
        { "q": "A shift in the demand curve to the right could be caused by:", "opts": ["A decrease in consumer income", "**An increase in the price of a substitute good**", "A decrease in the price of a complement good", "A change in consumer tastes away from the product"] },
        { "q": "If the price elasticity of demand is greater than 1, the demand is said to be:", "opts": ["Inelastic", "**Elastic**", "Unitary elastic", "Perfectly inelastic"] },
        { "q": "The total utility a consumer derives from consuming a good is maximized when marginal utility is:", "opts": ["Positive", "Negative", "**Zero**", "At its maximum"] },
        { "q": "In a perfectly competitive market, firms are:", "opts": ["Price makers", "**Price takers**", "Monopolists", "Oligopolists"] },
        { "q": "Which of the following is an example of a fixed cost?", "opts": ["Raw materials", "Electricity usage for production", "**Rent for the factory building**", "Wages for hourly workers"] },
        { "q": "The Gross Domestic Product (GDP) measures:", "opts": ["The total wealth of a nation", "**The total market value of all final goods and services produced within a country**", "The total income received by citizens living abroad", "The difference between exports and imports"] },
        { "q": "Inflation is defined as:", "opts": ["A one-time increase in the price of a specific good", "**A sustained increase in the general price level of goods and services**", "A decrease in the purchasing power of money due to low supply", "The increase in the unemployment rate"] },
        { "q": "The 'Command Economy' is characterized by:", "opts": ["Private ownership of resources", "**Government control and central planning**", "Decisions based on tradition", "Price determined by market forces"] },
        { "q": "The opportunity cost of a choice is:", "opts": ["The monetary cost only", "**The value of the next best alternative foregone**", "The total cost of all alternatives", "The time spent making the decision"] },
        { "q": "Which of the following would cause a movement along the supply curve?", "opts": ["A change in technology", "**A change in the price of the good itself**", "A change in the cost of inputs", "A change in the number of sellers"] },
        { "q": "If demand is perfectly inelastic, the demand curve is:", "opts": ["Horizontal", "**Vertical**", "Downward sloping", "Upward sloping"] },
        { "q": "The short run is a period of time in which:", "opts": ["All inputs are variable", "**At least one input is fixed**", "Technology is constantly changing", "Firms can easily enter or exit the market"] },
        { "q": "Monopoly is a market structure with:", "opts": ["Many small firms", "**A single seller of a product with no close substitutes**", "A few large firms dominating the market", "Two firms competing intensely"] },
        { "q": "Externalities occur when:", "opts": ["The market reaches equilibrium", "**A third party is affected by a transaction they are not part of**", "Government imposes taxes", "Prices are too high for consumers"] },
        { "q": "The 'Invisible Hand' concept was introduced by:", "opts": ["John Maynard Keynes", "Karl Marx", "**Adam Smith**", "David Ricardo"] },
        { "q": "Real GDP is adjusted for:", "opts": ["Taxes", "Depreciation", "**Inflation**", "Population growth"] },
        { "q": "A budget deficit occurs when:", "opts": ["Tax revenues exceed government spending", "**Government spending exceeds tax revenues**", "Exports exceed imports", "The money supply increases rapidly"] },
        { "q": "The primary goal of a firm is assumed to be:", "opts": ["Maximizing sales", "Maximizing market share", "**Maximizing profit**", "Minimizing costs"] },
        { "q": "Which type of unemployment occurs during a recession?", "opts": ["Frictional", "Structural", "**Cyclical**", "Seasonal"] },
        { "q": "The Law of Diminishing Marginal Returns applies when:", "opts": ["All inputs are increased", "**One input is increased while others remain fixed**", "Technology improves", "The scale of production decreases"] },
        { "q": "A price ceiling set below the equilibrium price results in:", "opts": ["A surplus", "**A shortage**", "No change in the market", "A decrease in demand"] },
        { "q": "Comparative advantage is the basis for:", "opts": ["Protectionism", "**International trade**", "Monopoly power", "Central planning"] },
        { "q": "Fiscal policy involves changes in:", "opts": ["Interest rates", "Money supply", "**Government spending and taxation**", "Exchange rates"] },
        { "q": "The Malthusian theory of population suggests that:", "opts": ["Population grows arithmetically", "**Population grows geometrically while food supply grows arithmetically**", "Food supply will always exceed population growth", "Technology will solve all resource problems"] },
        { "q": "In the circular flow model, households:", "opts": ["Produce goods and services", "**Own the factors of production and consume goods**", "Set market prices", "Regulate the banking system"] },
        { "q": "An inferior good is one for which demand:", "opts": ["Increases as income increases", "**Decreases as income increases**", "Is unrelated to income", "Is perfectly elastic"] },
        { "q": "Oligopoly is characterized by:", "opts": ["One firm", "Many small firms", "**A few large, interdependent firms**", "Free entry and exit"] },
        { "q": "Which of the following is a component of Aggregate Demand?", "opts": ["Wages", "**Investment spending**", "The money supply", "The labor force"] },
        { "q": "A production possibility curve (PPC) that is a straight line indicates:", "opts": ["Increasing opportunity costs", "**Constant opportunity costs**", "Decreasing opportunity costs", "Zero opportunity costs"] },
        { "q": "The substitution effect explains why:", "opts": ["People buy more of a good when their income rises", "**People buy more of a relatively cheaper good instead of a more expensive one**", "Firms produce more when prices rise", "Technology reduces costs"] },
        { "q": "Cartels are most commonly found in which market structure?", "opts": ["Perfect competition", "Monopolistic competition", "**Oligopoly**", "Monopoly"] },
        { "q": "Monetary policy is controlled by:", "opts": ["The Parliament", "The Ministry of Finance", "**The Central Bank**", "Commercial Banks"] },
        { "q": "The Gini coefficient is used to measure:", "opts": ["Economic growth", "Inflation", "**Income inequality**", "Unemployment"] },
        { "q": "Which of the following is a non-renewable resource?", "opts": ["Solar energy", "Timber", "**Petroleum**", "Fish"] },
        { "q": "What happens to the equilibrium price if demand increases and supply remains constant?", "opts": ["Price decreases", "**Price increases**", "Price remains same", "Quantity decreases"] },
        { "q": "The 'Laffer Curve' shows the relationship between:", "opts": ["Inflation and unemployment", "**Tax rates and tax revenue**", "Interest rates and investment", "GDP and population"] },
        { "q": "A pure public good is characterized by:", "opts": ["Excludability and rivalry", "**Non-excludability and non-rivalry**", "Low production costs", "Government ownership only"] },
        { "q": "Normal profit occurs when:", "opts": ["Total revenue > Total cost", "**Total revenue = Total cost (including implicit costs)**", "Total revenue < Total cost", "Marginal revenue is zero"] },
        { "q": "The 'Paradox of Thrift' suggests that:", "opts": ["Saving is always good for the economy", "**Attempts to increase saving can lead to a fall in total income**", "Spending leads to poverty", "Interest rates determine saving"] },
        { "q": "Expansionary monetary policy aims to:", "opts": ["Reduce inflation", "**Increase aggregate demand and economic growth**", "Increase taxes", "Reduce government spending"] },
        { "q": "Balance of Trade is the difference between:", "opts": ["Taxes and spending", "**Value of merchandise exports and imports**", "Foreign aid and debt", "Capital inflow and outflow"] },
        { "q": "In the production function, 'K' usually represents:", "opts": ["Knowledge", "**Capital**", "Labor", "Land"] },
        { "q": "Hyperinflation is usually caused by:", "opts": ["Excessive saving", "**Excessive growth in the money supply**", "High tax rates", "Strong labor unions"] },
        { "q": "Economic growth is best measured by the change in:", "opts": ["Nominal GDP", "**Real GDP per capita**", "The stock market index", "The population size"] },
        { "q": "A quota is a:", "opts": ["Tax on imports", "**Physical limit on the quantity of a good that can be imported**", "Subsidy to exporters", "Form of currency devaluation"] },
        { "q": "The 'Menu Costs' of inflation refer to:", "opts": ["The cost of food", "**The costs firms face when changing their prices**", "The cost of printing money", "The loss of interest income"] },
        { "q": "In a Lorenz curve, a 45-degree line represents:", "opts": ["Total inequality", "**Perfect equality**", "The poverty line", "Average income"] },
        { "q": "Structural unemployment is caused by:", "opts": ["Short-term job searches", "**Mismatches between worker skills and job requirements**", "Economic downturns", "Voluntary resignations"] },
        { "q": "Price discrimination involves:", "opts": ["Selling different products at the same price", "**Selling the same product to different customers at different prices**", "Illegal trade practices", "Setting prices below cost"] },
        { "q": "The 'Prebisch-Singer Hypothesis' relates to:", "opts": ["The growth of population", "**The declining terms of trade for primary commodity exporters**", "The causes of hyperinflation", "The benefits of globalization"] },
        { "q": "A regressive tax is one where:", "opts": ["Higher earners pay a higher percentage", "**Lower earners pay a higher percentage of their income**", "Everyone pays the same fixed amount", "The tax rate is zero"] },
        { "q": "Capitalism is primarily based on:", "opts": ["Social welfare", "**Private property and market competition**", "Government planning", "Cooperative ownership"] },
        { "q": "The Human Development Index (HDI) includes:", "opts": ["Only GDP", "**Life expectancy, education, and per capita income**", "Infrastructure and technology", "Military strength"] },
        { "q": "Consumer surplus is the difference between:", "opts": ["What consumers pay and what they save", "**What consumers are willing to pay and what they actually pay**", "Total utility and marginal utility", "Income and expenditure"] },
        { "q": "Supply-side economics emphasizes:", "opts": ["Increasing government spending", "**Reducing taxes and regulations to stimulate production**", "Controlling the money supply", "Increasing the minimum wage"] },
        { "q": "Which of the following is a 'Transfer Payment'?", "opts": ["Wages paid to soldiers", "**Social security benefits**", "Payment for office supplies", "Interest on a business loan"] },
        { "q": "The 'World Trade Organization' (WTO) focuses on:", "opts": ["Providing loans for development", "**Promoting free trade and resolving trade disputes**", "Regulating global migration", "Setting global exchange rates"] },
        { "q": "Multiplier effect means:", "opts": ["Spending leads to less income", "**An initial change in spending leads to a larger final change in GDP**", "Prices double every year", "Population outpaces food"] },
        { "q": "The 'Free Rider Problem' is associated with:", "opts": ["Private goods", "**Public goods**", "Inferior goods", "Giffen goods"] },
        { "q": "Absolute advantage means a country can produce a good:", "opts": ["At a lower opportunity cost", "**Using fewer resources than another country**", "In greater variety", "Only for domestic consumption"] },
        { "q": "STP in economics (in some contexts) refers to:", "opts": ["Standard Trade Policy", "Social Tax Program", "**Social Time Preference**", "Structural Trade Price"] },
        { "q": "Engel’s Law states that as income rises:", "opts": ["People spend more on luxury", "**The proportion of income spent on food falls**", "Saving becomes impossible", "Demand for all goods increases"] },
        { "q": "Dumping in international trade refers to:", "opts": ["Environmental pollution", "**Selling products in a foreign market at below cost or domestic price**", "Excessive importing", "Currency manipulation"] },
        { "q": "The 'Okun’s Law' describes the relationship between:", "opts": ["Inflation and interest rates", "**Unemployment and GDP growth**", "Exports and imports", "Taxes and consumption"] },
        { "q": "A 'Natural Monopoly' arises when:", "opts": ["The government grants a patent", "**One firm can supply the entire market at a lower cost than multiple firms**", "A firm owns all natural resources", "A firm uses aggressive advertising"] },
        { "q": "Appreciation of a currency makes:", "opts": ["Exports cheaper", "**Imports cheaper and exports more expensive**", "Tourism increase", "Domestic prices rise"] },
        { "q": "The 'Sustainability' concept in economics focuses on:", "opts": ["Maximizing current profit", "**Meeting current needs without compromising future generations**", "Ending all use of natural resources", "Rapid industrialization at any cost"] },
        { "q": "Marginal Cost is defined as:", "opts": ["Total cost divided by quantity", "**The change in total cost from producing one additional unit**", "Variable cost per unit", "Fixed cost minus variable cost"] },
        { "q": "Deflation is characterized by:", "opts": ["Rising prices", "**Falling general price levels**", "Increasing money supply", "High economic growth"] },
        { "q": "The 'Giffen Good' is a unique case where:", "opts": ["Demand is perfectly elastic", "**Demand increases as price increases**", "Supply is vertical", "Utility is negative"] },
        { "q": "Deadweight loss refers to:", "opts": ["The cost of production", "**The loss of economic efficiency due to market distortions like taxes**", "Bankruptcy of a firm", "Unsold inventory"] },
        { "q": "Economic Rent is:", "opts": ["The price paid for a house", "**Payment to a factor of production above its opportunity cost**", "Government tax on land", "Interest on capital"] },
        { "q": "The 'Green GDP' accounts for:", "opts": ["Agricultural output only", "**Environmental degradation and resource depletion**", "Growth in renewable energy sectors", "Forestry industry profits"] },
        { "q": "Protective tariffs are intended to:", "opts": ["Increase global trade", "**Protect domestic industries from foreign competition**", "Reduce government revenue", "Lower consumer prices"] },
        { "q": "A 'Black Market' typically arises due to:", "opts": ["High demand", "**Price controls (ceilings or floors)**", "Low supply", "Too much competition"] },
        { "q": "The 'Phillips Curve' shows the trade-off between:", "opts": ["Taxation and spending", "**Inflation and unemployment**", "Growth and environment", "Saving and investment"] },
        { "q": "What does the 'Porter Hypothesis' suggest about environmental regulations?", "opts": ["They always hurt economy", "**Stringent regulations can trigger innovation and competitiveness**", "They have no effect", "They only work in rich countries"] }
    ]
};
