// english.js - Common Subject English (2010 - 2017)
QUESTIONS_DB.Common.English["2010"] = [{ q: "If I _______ enough money, I would buy a new car.", opts: ["have", "**had**", "will have", "would have"] },
    { q: "She has been working here _______ 2015.", opts: ["for", "**since**", "at", "by"] },
    { q: "He is the man _______ daughter won the competition.", opts: ["who", "whom", "**whose**", "which"] },
    { q: "Neither the students nor the teacher _______ present yesterday.", opts: ["are", "were", "**was**", "is"] },
    { q: "I look forward to _______ you soon.", opts: ["see", "seen", "saw", "**seeing**"] },
    { q: "By the time we arrived, the film _______.", opts: ["starts", "has started", "**had started**", "was starting"] },
    { q: "The climate in Ethiopia is _______ than in England.", opts: ["hot", "hottest", "**hotter**", "more hot"] },
    { q: "You _______ smoke in the hospital; it is forbidden.", opts: ["don't have to", "**mustn't**", "shouldn't", "needn't"] },
    { q: "He speaks English very _______.", opts: ["good", "**well**", "best", "better"] },
    { q: "I wish I _______ more for the exam last week.", opts: ["study", "studied", "**had studied**", "have studied"] },
    { q: "The house _______ in 1990.", opts: ["build", "built", "**was built**", "is built"] },
    { q: "_______ having a headache, she went to work.", opts: ["Because", "Although", "**Despite**", "However"] },
    { q: "I am not used to _______ early in the morning.", opts: ["get up", "got up", "**getting up**", "gets up"] },
    { q: "This is the most _______ book I have ever read.", opts: ["interest", "interested", "**interesting**", "interestingly"] },
    { q: "If you _______ water, it boils.", opts: ["**heat**", "heated", "will heat", "would heat"] },
    { q: "She went to the market _______ buy some vegetables.", opts: ["for", "so", "**to**", "because"] },
    { q: "Would you mind _______ the window?", opts: ["open", "opened", "to open", "**opening**"] },
    { q: "He asked me where _______.", opts: ["do I live", "did I live", "**I lived**", "I live"] },
    { q: "The luggage is _______ heavy for me to carry alone.", opts: ["enough", "**too**", "very", "so"] },
    { q: "I prefer coffee _______ tea.", opts: ["than", "**to**", "from", "for"] },
    { q: "She is _______ at mathematics than her brother.", opts: ["good", "best", "**better**", "well"] },
    { q: "They _______ each other for ten years.", opts: ["know", "are knowing", "**have known**", "have been knowing"] },
    { q: "Unless you _______ hard, you will fail.", opts: ["**study**", "don't study", "studied", "will study"] },
    { q: "The cat is hiding _______ the table.", opts: ["on", "at", "**under**", "between"] },
    { q: "I don't know _______ key it is.", opts: ["who", "**whose**", "which", "whom"] },
    { q: "She _______ her homework before she went out.", opts: ["finish", "finishes", "**had finished**", "was finishing"] },
    { q: "Could you tell me how _______ to the station?", opts: ["get", "getting", "I get", "**to get**"] },
    { q: "Wait here _______ I come back.", opts: ["**until**", "since", "during", "while"] },
    { q: "The man _______ stole the bag was caught.", opts: ["which", "whom", "**who**", "whose"] },
    { q: "He is _______ honest person.", opts: ["a", "**an**", "the", "some"] },
    { q: "She is capable _______ passing the exam.", opts: ["to", "**of**", "for", "with"] },
    { q: "We avoided _______ through the city center.", opts: ["drive", "to drive", "**driving**", "driven"] },
    { q: "Hardly _______ I reached the station when the train left.", opts: ["did", "**had**", "was", "have"] },
    { q: "I'll call you as soon as I _______ home.", opts: ["**get**", "will get", "got", "am getting"] },
    { q: "This car is _______ than that one.", opts: ["expensive", "more expensive", "**the most expensive**", "as expensive"] },
    { q: "He has _______ friends in the city.", opts: ["much", "**a few**", "a little", "any"] },
    { q: "The work _______ finished by next Friday.", opts: ["is", "was", "**will be**", "has been"] },
    { q: "Stop _______ that noise!", opts: ["make", "to make", "**making**", "made"] },
    { q: "He succeeded _______ winning the prize.", opts: ["on", "**in**", "at", "with"] },
    { q: "If it rains, we _______ the match.", opts: ["cancel", "**will cancel**", "would cancel", "cancelled"] },
    { q: "I _______ my keys. Have you seen them?", opts: ["**have lost**", "lost", "had lost", "lose"] },
    { q: "The coffee is _______ hot to drink.", opts: ["so", "enough", "**too**", "much"] },
    { q: "_______ she was tired, she finished the report.", opts: ["Because", "**Although**", "Since", "Despite"] },
    { q: "Who is responsible _______ this mess?", opts: ["to", "with", "**for**", "at"] },
    { q: "I suggested _______ to the cinema.", opts: ["go", "to go", "**going**", "went"] },
    { q: "She _______ in this city for five years now.", opts: ["lives", "lived", "**has been living**", "is living"] },
    { q: "He _______ to be a doctor since he was a child.", opts: ["wants", "wanted", "**has wanted**", "is wanting"] },
    { q: "You _______ better see a doctor.", opts: ["should", "**had**", "would", "could"] },
    { q: "The bridge _______ repaired at the moment.", opts: ["is", "was", "**is being**", "has been"] },
    { q: "None of the information _______ correct.", opts: ["are", "**is**", "were", "been"] },
    { q: "He was accused _______ stealing the money.", opts: ["for", "with", "**of**", "to"] },
    { q: "We are interested _______ learning Japanese.", opts: ["on", "**in**", "at", "for"] },
    { q: "I _______ him since last Monday.", opts: ["didn't see", "don't see", "**haven't seen**", "am not seeing"] },
    { q: "The book _______ I bought yesterday is very good.", opts: ["who", "whom", "**which**", "whose"] },
    { q: "He is rich; _______, he is not happy.", opts: ["so", "because", "**however**", "therefore"] },
    { q: "Please turn _______ the lights before you leave.", opts: ["**off**", "on", "down", "up"] },
    { q: "You don't need to hurry; we have _______ time.", opts: ["many", "few", "**plenty of**", "a little"] },
    { q: "They _______ their dinner when the lights went out.", opts: ["eat", "ate", "**were eating**", "have eaten"] },
    { q: "I ______ rather stay at home than go out tonight.", opts: ["should", "**would**", "could", "had"] },
    { q: "The teacher made the students _______ the essay again.", opts: ["write", "**to write**", "writing", "wrote"] },
    { q: "She is the _______ girl in the class.", opts: ["tall", "taller", "**tallest**", "most tall"] },
    { q: "We need _______ more information before we decide.", opts: ["an", "many", "**some**", "a"] },
    { q: "He arrived _______ the airport at 10 PM.", opts: ["in", "**at**", "to", "on"] },
    { q: "I don't think it _______ rain tomorrow.", opts: ["**will**", "is", "was", "has"] },
    { q: "My father _______ me to work harder.", opts: ["suggested", "said", "**told**", "ordered"] },
    { q: "It is _______ today than it was yesterday.", opts: ["cold", "coldest", "**colder**", "more cold"] },
    { q: "Neither of the two books _______ interesting.", opts: ["are", "**is**", "were", "been"] },
    { q: "You should avoid _______ too much junk food.", opts: ["eat", "to eat", "**eating**", "ate"] },
    { q: "The news _______ very shocking.", opts: ["are", "**is**", "were", "been"] },
    { q: "He is looking _______ a new job.", opts: ["**for**", "at", "after", "to"] },
    { q: "I _______ my homework yet.", opts: ["didn't finish", "**haven't finished**", "don't finish", "hadn't finished"] },
    { q: "She _______ play the piano very well.", opts: ["**can**", "may", "must", "might"] },
    { q: "The test was _______ difficult that I couldn't pass it.", opts: ["too", "very", "**so**", "much"] },
    { q: "He has _______ money than I do.", opts: ["few", "fewer", "**less**", "least"] },
    { q: "She is good _______ swimming.", opts: ["in", "**at**", "for", "with"] },
    { q: "We _______ basketball every Saturday.", opts: ["**play**", "playing", "played", "are playing"] },
    { q: "The police _______ investigating the crime.", opts: ["is", "**are**", "was", "has been"] },
    { q: "I'll wait for you _______ the bus stop.", opts: ["in", "on", "**at**", "to"] },
    { q: "He usually _______ to school by bus.", opts: ["go", "**goes**", "going", "gone"] },
    { q: "This is the _______ film I have ever seen.", opts: ["bad", "worse", "**worst**", "baddest"] },
    { q: "They _______ for three hours before they found the road.", opts: ["walk", "walked", "**had been walking**", "were walking"] },
    { q: "You _______ take an umbrella; it might rain.", opts: ["**should**", "must", "can", "need"] },
    { q: "She is looking forward to _______ her family.", opts: ["see", "seen", "**seeing**", "saw"] },
    { q: "The room was _______ with smoke.", opts: ["fill", "filling", "**filled**", "full"] },
    { q: "He _______ to work yesterday because he was sick.", opts: ["didn't go", "doesn't go", "won't go", "**hasn't gone**"] },
    { q: "This is _______ house I told you about.", opts: ["a", "an", "**the**", "some"] },
    { q: "The water was _______ cold to swim in.", opts: ["so", "enough", "**too**", "very"] },
    { q: "I would like _______ a cup of tea.", opts: ["have", "**to have**", "having", "had"] },
    { q: "He is _______ oldest in the family.", opts: ["a", "an", "**the**", "one"] },
    { q: "I _______ my breakfast when the phone rang.", opts: ["eat", "ate", "**was eating**", "have eaten"] },
    { q: "The boy _______ sits next to me is very clever.", opts: ["which", "whom", "**who**", "whose"] },
    { q: "You _______ pay now; you can pay later.", opts: ["mustn't", "**needn't**", "shouldn't", "can't"] },
    { q: "She is as _______ as her mother.", opts: ["**beautiful**", "more beautiful", "most beautiful", "beauty"] },
    { q: "They are _______ for the exam.", opts: ["study", "**studying**", "studies", "studied"] },
    { q: "I _______ him for a long time.", opts: ["know", "am knowing", "**have known**", "knows"] },
    { q: "The students _______ their exams next week.", opts: ["take", "**will take**", "took", "have taken"] },
    { q: "He is interested _______ music.", opts: ["on", "at", "**in**", "for"] },
    { q: "This is the book _______ I was looking for.", opts: ["who", "whom", "**that**", "whose"] },
    { q: "I _______ go to the party if I'm not busy.", opts: ["**might**", "must", "should", "will"] },
    { q: "She _______ been crying all morning.", opts: ["is", "was", "**has**", "had"] }];
QUESTIONS_DB.Common.English["2011"] = [{ q: "I _______ my homework when my friend called me.", opts: ["finish", "finished", "**was finishing**", "have finished"] },
    { q: "She is the woman _______ son won the national lottery.", opts: ["who", "whom", "**whose**", "which"] },
    { q: "If I _______ you, I would take the medical advice.", opts: ["am", "was", "**were**", "had been"] },
    { q: "We have lived in this house _______ ten years.", opts: ["since", "**for**", "during", "at"] },
    { q: "Hardly _______ the room when the phone started ringing.", opts: ["I entered", "**had I entered**", "I had entered", "did I enter"] },
    { q: "The cake _______ by my mother yesterday.", opts: ["makes", "made", "**was made**", "is made"] },
    { q: "I look forward to _______ you at the graduation ceremony.", opts: ["see", "saw", "**seeing**", "to see"] },
    { q: "He is _______ honest man I have ever met.", opts: ["a", "**the**", "an", "most"] },
    { q: "You _______ smoke in the gas station; it is dangerous.", opts: ["shouldn't", "don't have to", "**mustn't**", "needn't"] },
    { q: "They _______ their lunch before the guest arrived.", opts: ["eat", "ate", "**had eaten**", "were eating"] },
    { q: "I prefer watching football _______ playing it.", opts: ["than", "**to**", "from", "for"] },
    { q: "The more you study, _______ you will become.", opts: ["smart", "smartest", "**the smarter**", "more smart"] },
    { q: "He succeeded _______ passing the driving test.", opts: ["on", "at", "**in**", "with"] },
    { q: "Neither the players nor the coach _______ happy with the result.", opts: ["are", "**was**", "were", "be"] },
    { q: "I wish I _______ more money last month.", opts: ["have", "had", "**had had**", "would have"] },
    { q: "She went to the library _______ she could study in peace.", opts: ["to", "**so that**", "because", "in order to"] },
    { q: "The luggage is _______ heavy for the child to lift.", opts: ["so", "enough", "**too**", "very"] },
    { q: "I am not used to _______ in a crowded city.", opts: ["live", "lived", "**living**", "lives"] },
    { q: "By the time the sun sets, we _______ our work.", opts: ["finish", "will finish", "**will have finished**", "finished"] },
    { q: "He asked me what _______.", opts: ["was my name", "is my name", "**my name was**", "my name is"] },
    { q: "She is capable _______ solving the most difficult problems.", opts: ["to", "**of**", "for", "in"] },
    { q: "_______ being very tired, he continued to work.", opts: ["Although", "Because", "**In spite of**", "However"] },
    { q: "I don't know _______ coat this is.", opts: ["who", "**whose**", "which", "whom"] },
    { q: "They _______ each other since they were children.", opts: ["know", "are knowing", "**have known**", "knew"] },
    { q: "Wait here _______ I return.", opts: ["**until**", "since", "while", "during"] },
    { q: "He is _______ interesting person to talk to.", opts: ["a", "**an**", "the", "some"] },
    { q: "We avoided _______ the busy street during rush hour.", opts: ["cross", "to cross", "**crossing**", "crossed"] },
    { q: "I'll call you as soon as the plane _______.", opts: ["**lands**", "will land", "landed", "is landing"] },
    { q: "This exam is _______ than the one we took last month.", opts: ["easy", "**easier**", "easiest", "more easy"] },
    { q: "He has _______ experience in this field.", opts: ["many", "**little**", "few", "any"] },
    { q: "The report _______ sent to the manager tomorrow.", opts: ["is", "was", "**will be**", "has been"] },
    { q: "Stop _______ that loud noise!", opts: ["make", "to make", "**making**", "made"] },
    { q: "If you _______ early, you will catch the bus.", opts: ["**wake up**", "woke up", "will wake up", "would wake up"] },
    { q: "I _______ my wallet. Can you help me find it?", opts: ["**have lost**", "lost", "had lost", "lose"] },
    { q: "The tea is _______ hot to drink right now.", opts: ["so", "enough", "**too**", "very"] },
    { q: "Who is responsible _______ organizing the party?", opts: ["to", "with", "**for**", "at"] },
    { q: "She _______ in the garden for two hours now.", opts: ["is working", "worked", "**has been working**", "works"] },
    { q: "You _______ better see a dentist for that toothache.", opts: ["should", "**had**", "would", "could"] },
    { q: "The road _______ repaired at the moment.", opts: ["is", "was", "**is being**", "has been"] },
    { q: "None of the water _______ fit for drinking.", opts: ["are", "**is**", "were", "been"] },
    { q: "He was accused _______ breaking the law.", opts: ["for", "with", "**of**", "to"] },
    { q: "We are interested _______ visiting the historical sites.", opts: ["on", "**in**", "at", "for"] },
    { q: "I _______ him since the conference last year.", opts: ["didn't see", "don't see", "**haven't seen**", "am not seeing"] },
    { q: "The car _______ he bought is very expensive.", opts: ["who", "whom", "**which**", "whose"] },
    { q: "Please turn _______ the radio; it's too loud.", opts: ["**down**", "on", "up", "to"] },
    { q: "You don't need to worry; we have _______ time.", opts: ["many", "few", "**plenty of**", "a little"] },
    { q: "They _______ their homework when the power went out.", opts: ["do", "did", "**were doing**", "have done"] },
    { q: "I _______ rather stay home than go to the party.", opts: ["should", "**would**", "could", "had"] },
    { q: "The teacher made him _______ the entire chapter.", opts: ["read", "**to read**", "reading", "readed"] },
    { q: "She is the _______ student in the class.", opts: ["bright", "brighter", "**brightest**", "most bright"] },
    { q: "We need _______ salt for the soup.", opts: ["an", "many", "**some**", "a"] },
    { q: "He arrived _______ the station just in time.", opts: ["in", "**at**", "to", "on"] },
    { q: "I don't think it _______ snow this winter.", opts: ["**will**", "is", "was", "has"] },
    { q: "My mother _______ me to clean my room.", opts: ["suggested", "said", "**told**", "ordered"] },
    { q: "It is _______ today than it was yesterday.", opts: ["windy", "windiest", "**windier**", "more windy"] },
    { q: "Neither of the candidates _______ qualified for the job.", opts: ["are", "**is**", "were", "been"] },
    { q: "You should avoid _______ late for meetings.", opts: ["be", "to be", "**being**", "been"] },
    { q: "The news about the accident _______ very sad.", opts: ["are", "**is**", "were", "been"] },
    { q: "He is looking _______ his lost keys.", opts: ["**for**", "at", "after", "to"] },
    { q: "I _______ my project yet.", opts: ["didn't finish", "**haven't finished**", "don't finish", "hadn't finished"] },
    { q: "She _______ speak three languages fluently.", opts: ["**can**", "may", "must", "might"] },
    { q: "The mountain was _______ high that we couldn't climb it.", opts: ["too", "very", "**so**", "much"] },
    { q: "She has _______ books than her sister.", opts: ["few", "**fewer**", "less", "least"] },
    { q: "She is good _______ playing the violin.", opts: ["in", "**at**", "for", "with"] },
    { q: "We _______ to the gym every morning.", opts: ["**go**", "going", "gone", "are going"] },
    { q: "The police _______ searching for the suspect.", opts: ["is", "**are**", "was", "has been"] },
    { q: "I'll meet you _______ the entrance of the mall.", opts: ["in", "on", "**at**", "to"] },
    { q: "He usually _______ his coffee without sugar.", opts: ["drink", "**drinks**", "drinking", "drunk"] },
    { q: "This is the _______ day of my life.", opts: ["happy", "happier", "**happiest**", "most happy"] },
    { q: "They _______ for an hour before the rain started.", opts: ["run", "ran", "**had been running**", "were running"] },
    { q: "You _______ take your coat; it's cold outside.", opts: ["**should**", "must", "can", "need"] },
    { q: "The hall was _______ with people.", opts: ["crowd", "crowding", "**crowded**", "full"] },
    { q: "He _______ to the party because he wasn't invited.", opts: ["didn't go", "doesn't go", "won't go", "**hasn't gone**"] },
    { q: "This is _______ book I was telling you about.", opts: ["a", "an", "**the**", "some"] },
    { q: "The room was _______ small for all of us.", opts: ["so", "enough", "**too**", "very"] },
    { q: "I would like _______ a glass of water.", opts: ["drink", "**to drink**", "drinking", "drank"] },
    { q: "He is _______ youngest person in the group.", opts: ["a", "an", "**the**", "one"] },
    { q: "I _______ a book when the lights went out.", opts: ["read", "reads", "**was reading**", "have read"] },
    { q: "The girl _______ lives next door is a doctor.", opts: ["which", "whom", "**who**", "whose"] },
    { q: "You _______ carry heavy bags; I will help you.", opts: ["mustn't", "**needn't**", "shouldn't", "can't"] },
    { q: "She is as _______ as her sister.", opts: ["**intelligent**", "more intelligent", "most intelligent", "intelligence"] },
    { q: "They are _______ for their final exams.", opts: ["prepare", "**preparing**", "prepares", "prepared"] },
    { q: "I _______ him since we graduated.", opts: ["know", "am knowing", "**have known**", "knows"] },
    { q: "The team _______ the match tomorrow.", opts: ["play", "**will play**", "played", "have played"] },
    { q: "He is interested _______ learning new things.", opts: ["on", "at", "**in**", "for"] },
    { q: "This is the house _______ my grandfather built.", opts: ["who", "whom", "**that**", "whose"] },
    { q: "I _______ go to the village if I get a holiday.", opts: ["**might**", "must", "should", "will"] },
    { q: "She _______ been working all night.", opts: ["is", "was", "**has**", "had"] },
    { q: "He is the boy _______ father is a pilot.", opts: ["who", "whom", "**whose**", "which"] },
    { q: "Neither of the answers _______ correct.", opts: ["are", "**is**", "were", "be"] },
    { q: "She was so _______ that she fell asleep in the bus.", opts: ["tire", "tiring", "**tired**", "tires"] },
    { q: "We should go home _______ it gets dark.", opts: ["after", "since", "**before**", "until"] },
    { q: "The building _______ last year.", opts: ["finish", "finished", "**was finished**", "is finishing"] },
    { q: "He is the fastest runner _______ I know.", opts: ["who", "whom", "**that**", "which"] },
    { q: "I don't have _______ money left.", opts: ["some", "**any**", "many", "few"] },
    { q: "She _______ her keys inside the car.", opts: ["leave", "left", "**has left**", "leaving"] },
    { q: "You _______ follow the rules.", opts: ["**must**", "may", "might", "could"] },
    { q: "He is _______ at English than his friend.", opts: ["good", "best", "**better**", "well"] },
    { q: "We are going _______ a trip next week.", opts: ["in", "**on**", "to", "at"] },
    { q: "The man _______ you met is my uncle.", opts: ["who", "**whom**", "whose", "which"] }];
QUESTIONS_DB.Common.English["2012"] = [{ q: "I _______ to the radio when the doorbell rang.", opts: ["listen", "listened", "**was listening**", "have listened"] },
    { q: "This is the city _______ I was born and raised.", opts: ["which", "that", "**where**", "whom"] },
    { q: "If she _______ faster, she would have won the race.", opts: ["runs", "ran", "**had run**", "would run"] },
    { q: "They have been married _______ twenty-five years.", opts: ["since", "**for**", "during", "at"] },
    { q: "Scarcely _______ the game started when it began to rain.", opts: ["did", "**had**", "was", "has"] },
    { q: "The broken window _______ by the wind last night.", opts: ["breaks", "broke", "**was broken**", "is broken"] },
    { q: "I am looking forward to _______ my exam results.", opts: ["get", "got", "**getting**", "to get"] },
    { q: "He is _______ most intelligent student in our school.", opts: ["a", "an", "**the**", "one"] },
    { q: "You _______ park here; it is a 'No Parking' zone.", opts: ["shouldn't", "don't have to", "**mustn't**", "needn't"] },
    { q: "She _______ her dinner before her friends arrived.", opts: ["eat", "ate", "**had eaten**", "was eating"] },
    { q: "I would rather study Biology _______ History.", opts: ["than", "**to**", "from", "for"] },
    { q: "The harder you work, _______ your results will be.", opts: ["good", "best", "**the better**", "more good"] },
    { q: "He is very good _______ playing the guitar.", opts: ["in", "on", "**at**", "with"] },
    { q: "Neither the principal nor the teachers _______ at the meeting.", opts: ["is", "**were**", "was", "be"] },
    { q: "I wish I _______ more time to finish the project.", opts: ["have", "has", "**had**", "would have"] },
    { q: "He went to the bank _______ get some cash.", opts: ["for", "so", "**to**", "because"] },
    { q: "The box is _______ heavy for me to lift alone.", opts: ["so", "enough", "**too**", "very"] },
    { q: "I am not used to _______ in such a cold climate.", opts: ["live", "lived", "**living**", "lives"] },
    { q: "By next year, they _______ the new bridge.", opts: ["finish", "will finish", "**will have finished**", "finished"] },
    { q: "She asked me if I _______ her a favor.", opts: ["do", "did", "**could do**", "can do"] },
    { q: "He is responsible _______ managing the finance department.", opts: ["to", "with", "**for**", "at"] },
    { q: "_______ it was raining, they went out for a walk.", opts: ["Because", "**Although**", "Despite", "However"] },
    { q: "I don't know _______ umbrella this is.", opts: ["who", "**whose**", "which", "whom"] },
    { q: "We _______ each other for a long time.", opts: ["know", "are knowing", "**have known**", "knew"] },
    { q: "Please wait here _______ the doctor is ready to see you.", opts: ["**until**", "since", "while", "during"] },
    { q: "She is _______ exceptionally talented artist.", opts: ["a", "**an**", "the", "some"] },
    { q: "They suggested _______ a taxi to the airport.", opts: ["take", "to take", "**taking**", "took"] },
    { q: "I will call you as soon as I _______ my results.", opts: ["**receive**", "will receive", "received", "am receiving"] },
    { q: "This car is _______ than my previous one.", opts: ["fast", "**faster**", "fastest", "more fast"] },
    { q: "There is _______ water left in the bottle.", opts: ["many", "**a little**", "a few", "any"] },
    { q: "The meeting _______ held in the main hall tomorrow.", opts: ["is", "was", "**will be**", "has been"] },
    { q: "I can't stand _______ in long queues.", opts: ["wait", "to wait", "**waiting**", "waited"] },
    { q: "If you _______ the truth, I will forgive you.", opts: ["**tell**", "told", "will tell", "would tell"] },
    { q: "I _______ my keys. Have you seen them anywhere?", opts: ["**have lost**", "lost", "had lost", "lose"] },
    { q: "The coffee is _______ hot that I can't drink it yet.", opts: ["too", "very", "**so**", "much"] },
    { q: "Who is in charge _______ this project?", opts: ["to", "with", "**of**", "at"] },
    { q: "She _______ for this company since 2010.", opts: ["works", "worked", "**has been working**", "is working"] },
    { q: "You _______ better finish your assignment today.", opts: ["should", "**had**", "would", "could"] },
    { q: "A new hospital _______ built in our village now.", opts: ["is", "was", "**is being**", "has been"] },
    { q: "None of the students _______ pass the difficult test.", opts: ["is", "**was**", "were", "been"] },
    { q: "He was accused _______ telling a lie.", opts: ["for", "with", "**of**", "to"] },
    { q: "We are interested _______ joining the club.", opts: ["on", "**in**", "at", "for"] },
    { q: "I _______ him since we met at the party.", opts: ["didn't see", "don't see", "**haven't seen**", "am not seeing"] },
    { q: "The movie _______ we watched last night was boring.", opts: ["who", "whom", "**which**", "whose"] },
    { q: "Please turn _______ the volume; it's too quiet.", opts: ["down", "off", "**up**", "to"] },
    { q: "Don't worry, we have _______ time before the flight.", opts: ["many", "few", "**plenty of**", "a little"] },
    { q: "They _______ their lunch when the phone rang.", opts: ["eat", "ate", "**were eating**", "have eaten"] },
    { q: "I _______ rather walk than take a bus.", opts: ["should", "**would**", "could", "had"] },
    { q: "The manager made the staff _______ overtime.", opts: ["work", "**to work**", "working", "worked"] },
    { q: "She is the _______ girl I have ever met.", opts: ["kind", "kinder", "**kindest**", "most kind"] },
    { q: "We need _______ help with these heavy boxes.", opts: ["an", "many", "**some**", "a"] },
    { q: "He arrived _______ home very late last night.", opts: ["in", "at", "to", "**(none)**"] },
    { q: "I don't think it _______ rain this afternoon.", opts: ["**will**", "is", "was", "has"] },
    { q: "My father _______ me to be careful.", opts: ["suggested", "said", "**told**", "ordered"] },
    { q: "It is _______ today than it was yesterday.", opts: ["warm", "warmest", "**warmer**", "more warm"] },
    { q: "Neither of the options _______ suitable for us.", opts: ["are", "**is**", "were", "be"] },
    { q: "You should avoid _______ late for class.", opts: ["come", "to come", "**coming**", "came"] },
    { q: "The news _______ not very encouraging.", opts: ["are", "**is**", "were", "been"] },
    { q: "He is looking _______ his glasses.", opts: ["**for**", "at", "after", "to"] },
    { q: "I _______ my breakfast yet.", opts: ["didn't have", "**haven't had**", "don't have", "hadn't had"] },
    { q: "She _______ play the violin beautifully.", opts: ["**can**", "may", "must", "might"] },
    { q: "The wall was _______ high that he couldn't jump over it.", opts: ["too", "very", "**so**", "much"] },
    { q: "He has _______ money than his brother.", opts: ["few", "fewer", "**less**", "least"] },
    { q: "She is good _______ dancing.", opts: ["in", "**at**", "for", "with"] },
    { q: "We _______ to the church every Sunday.", opts: ["**go**", "going", "gone", "are going"] },
    { q: "The police _______ patrolling the area.", opts: ["is", "**are**", "was", "has been"] },
    { q: "I'll see you _______ the afternoon.", opts: ["**in**", "on", "at", "to"] },
    { q: "He usually _______ his homework in the evening.", opts: ["do", "**does**", "doing", "done"] },
    { q: "This is the _______ day of the year.", opts: ["long", "longer", "**longest**", "most long"] },
    { q: "They _______ for two hours when they got tired.", opts: ["work", "worked", "**had been working**", "were working"] },
    { q: "You _______ wear a helmet when riding a bike.", opts: ["**should**", "may", "can", "might"] },
    { q: "The bag was _______ with old books.", opts: ["fill", "filling", "**filled**", "full"] },
    { q: "He _______ to the meeting because he was busy.", opts: ["didn't go", "doesn't go", "won't go", "**hasn't gone**"] },
    { q: "This is _______ car I bought last week.", opts: ["a", "an", "**the**", "some"] },
    { q: "The dress was _______ small for her.", opts: ["so", "enough", "**too**", "very"] },
    { q: "I would like _______ some fruit juice.", opts: ["drink", "**to drink**", "drinking", "drank"] },
    { q: "He is _______ youngest boy in the class.", opts: ["a", "an", "**the**", "one"] },
    { q: "I _______ a movie when the lights went out.", opts: ["watch", "watched", "**was watching**", "have watched"] },
    { q: "The man _______ lives next door is very friendly.", opts: ["which", "whom", "**who**", "whose"] },
    { q: "You _______ buy a ticket; I have already bought one.", opts: ["mustn't", "**needn't**", "shouldn't", "can't"] },
    { q: "She is as _______ as her sister.", opts: ["**clever**", "more clever", "most clever", "cleverly"] },
    { q: "They are _______ for their graduation.", opts: ["prepare", "**preparing**", "prepares", "prepared"] },
    { q: "I _______ him since we were in high school.", opts: ["know", "am knowing", "**have known**", "knows"] },
    { q: "The company _______ its new product next month.", opts: ["launch", "**will launch**", "launched", "has launched"] },
    { q: "He is interested _______ ancient history.", opts: ["on", "at", "**in**", "for"] },
    { q: "This is the place _______ we met for the first time.", opts: ["who", "whom", "**where**", "whose"] },
    { q: "I _______ go to the cinema tonight.", opts: ["**might**", "must", "should", "will"] },
    { q: "She _______ been sleeping since 10 PM.", opts: ["is", "was", "**has**", "had"] },
    { q: "He is the student _______ score was the highest.", opts: ["who", "whom", "**whose**", "which"] },
    { q: "Neither of the two roads _______ to the city.", opts: ["lead", "**leads**", "leading", "led"] },
    { q: "I was so _______ that I couldn't say a word.", opts: ["surprise", "surprising", "**surprised**", "surprises"] },
    { q: "We should arrive _______ the sun sets.", opts: ["after", "since", "**before**", "until"] },
    { q: "The school _______ built five years ago.", opts: ["build", "built", "**was built**", "is building"] },
    { q: "He is the best teacher _______ I have ever had.", opts: ["who", "whom", "**that**", "which"] },
    { q: "I don't have _______ bread left.", opts: ["some", "**any**", "many", "few"] },
    { q: "She _______ her keys on the table.", opts: ["leave", "left", "**has left**", "leaving"] },
    { q: "You _______ respect your parents.", opts: ["**must**", "may", "might", "could"] },
    { q: "He is _______ at Math than his brother.", opts: ["good", "best", "**better**", "well"] },
    { q: "We are going _______ a vacation next week.", opts: ["in", "**on**", "to", "at"] },
    { q: "The lady _______ you were talking to is my aunt.", opts: ["who", "**whom**", "whose", "which"] }];
QUESTIONS_DB.Common.English["2013"] = [{ q: "I _______ my keys while I was running in the park.", opts: ["lose", "lost", "**was losing**", "have lost"] },
    { q: "The teacher, _______ we all respect, is retiring this year.", opts: ["who", "**whom**", "whose", "which"] },
    { q: "If I _______ the answer, I would tell you immediately.", opts: ["know", "knows", "**knew**", "had known"] },
    { q: "She has been studying medicine _______ six years.", opts: ["since", "**for**", "during", "at"] },
    { q: "Hardly _______ the meeting started when the power went out.", opts: ["did", "was", "**had**", "has"] },
    { q: "The ancient temple _______ by thousands of tourists every year.", opts: ["visits", "visited", "**is visited**", "is visiting"] },
    { q: "I am really looking forward to _______ my old friends.", opts: ["see", "saw", "**seeing**", "to see"] },
    { q: "He is _______ most talented musician in the orchestra.", opts: ["a", "an", "**the**", "one"] },
    { q: "You _______ enter that room; it is restricted to staff only.", opts: ["shouldn't", "don't have to", "**mustn't**", "needn't"] },
    { q: "They _______ their project before the deadline arrived.", opts: ["finish", "finished", "**had finished**", "were finishing"] },
    { q: "I prefer traveling by train _______ flying.", opts: ["than", "**to**", "from", "for"] },
    { q: "The more expensive the car, _______ it is to maintain.", opts: ["costly", "costlier", "**the costlier**", "more costly"] },
    { q: "She is very good _______ solving complex puzzles.", opts: ["in", "on", "**at**", "with"] },
    { q: "Neither the players nor the captain _______ happy with the referee.", opts: ["are", "**was**", "were", "be"] },
    { q: "I wish I _______ more attention during the lecture.", opts: ["pay", "paid", "**had paid**", "have paid"] },
    { q: "He went to the store _______ buy some milk.", opts: ["for", "so", "**to**", "because"] },
    { q: "The suitcase is _______ heavy for me to carry upstairs.", opts: ["so", "enough", "**too**", "very"] },
    { q: "I am not used to _______ in a big city like New York.", opts: ["live", "lived", "**living**", "lives"] },
    { q: "By next month, the construction crew _______ the building.", opts: ["finish", "will finish", "**will have finished**", "finished"] },
    { q: "He asked me if I _______ help him with his homework.", opts: ["can", "do", "**could**", "will"] },
    { q: "She is responsible _______ organizing the annual conference.", opts: ["to", "with", "**for**", "at"] },
    { q: "_______ it was very late, he decided to finish the report.", opts: ["Because", "**Although**", "Despite", "However"] },
    { q: "I don't know _______ book this is; it was on my desk.", opts: ["who", "**whose**", "which", "whom"] },
    { q: "They _______ each other since they started university.", opts: ["know", "are knowing", "**have known**", "knew"] },
    { q: "Please wait here _______ the manager is available.", opts: ["**until**", "since", "while", "during"] },
    { q: "He is _______ extremely intelligent young man.", opts: ["a", "**an**", "the", "some"] },
    { q: "They suggested _______ a different route to avoid traffic.", opts: ["take", "to take", "**taking**", "took"] },
    { q: "I will call you as soon as the meeting _______.", opts: ["**ends**", "will end", "ended", "is ending"] },
    { q: "This task is _______ than the one we did yesterday.", opts: ["hard", "**harder**", "hardest", "more hard"] },
    { q: "There is _______ sugar left in the jar.", opts: ["many", "**a little**", "a few", "any"] },
    { q: "The results _______ announced tomorrow morning.", opts: ["is", "was", "**will be**", "has been"] },
    { q: "I can't stand _______ in such a noisy environment.", opts: ["work", "to work", "**working**", "worked"] },
    { q: "If you _______ the instructions, you won't make mistakes.", opts: ["**follow**", "followed", "will follow", "would follow"] },
    { q: "I _______ my phone. Have you seen it anywhere?", opts: ["**have lost**", "lost", "had lost", "lose"] },
    { q: "The movie was _______ long that I fell asleep.", opts: ["too", "very", "**so**", "much"] },
    { q: "Who is in charge _______ the kitchen today?", opts: ["to", "with", "**of**", "at"] },
    { q: "She _______ at this hospital for over twenty years.", opts: ["works", "worked", "**has been working**", "is working"] },
    { q: "You _______ better study hard if you want to pass.", opts: ["should", "**had**", "would", "could"] },
    { q: "A new shopping mall _______ built in the city center now.", opts: ["is", "was", "**is being**", "has been"] },
    { q: "None of the information _______ provided was useful.", opts: ["are", "**is**", "were", "been"] },
    { q: "He was accused _______ cheating during the final exam.", opts: ["for", "with", "**of**", "to"] },
    { q: "We are interested _______ joining the photography club.", opts: ["on", "**in**", "at", "for"] },
    { q: "I _______ her since the graduation party.", opts: ["didn't see", "don't see", "**haven't seen**", "am not seeing"] },
    { q: "The laptop _______ I bought yesterday is very fast.", opts: ["who", "whom", "**which**", "whose"] },
    { q: "Please turn _______ the lights when you leave.", opts: ["**off**", "on", "up", "to"] },
    { q: "Don't worry, we have _______ time before the train leaves.", opts: ["many", "few", "**plenty of**", "a little"] },
    { q: "They _______ their dinner when the guest arrived.", opts: ["eat", "ate", "**were eating**", "have eaten"] },
    { q: "I _______ rather stay at home than go to the cinema.", opts: ["should", "**would**", "could", "had"] },
    { q: "The teacher made the students _______ the poem.", opts: ["recite", "**to recite**", "reciting", "recited"] },
    { q: "She is the _______ girl in her family.", opts: ["young", "younger", "**youngest**", "most young"] },
    { q: "We need _______ help with the preparations.", opts: ["an", "many", "**some**", "a"] },
    { q: "He arrived _______ the office late this morning.", opts: ["in", "**at**", "to", "on"] },
    { q: "I don't think it _______ snow tonight.", opts: ["**will**", "is", "was", "has"] },
    { q: "My boss _______ me to finish the report by 5 PM.", opts: ["suggested", "said", "**told**", "ordered"] },
    { q: "It is _______ today than it was on Monday.", opts: ["cold", "coldest", "**colder**", "more cold"] },
    { q: "Neither of the plans _______ approved by the committee.", opts: ["are", "**is**", "were", "be"] },
    { q: "You should avoid _______ junk food for a healthy life.", opts: ["eat", "to eat", "**eating**", "ate"] },
    { q: "The news _______ quite unexpected for everyone.", opts: ["are", "**is**", "were", "been"] },
    { q: "He is looking _______ his missing cat.", opts: ["**for**", "at", "after", "to"] },
    { q: "I _______ my lunch yet.", opts: ["didn't have", "**haven't had**", "don't have", "hadn't had"] },
    { q: "She _______ play the flute very well.", opts: ["**can**", "may", "must", "might"] },
    { q: "The hill was _______ steep that we couldn't climb it.", opts: ["too", "very", "**so**", "much"] },
    { q: "He has _______ experience than his colleague.", opts: ["few", "fewer", "**less**", "least"] },
    { q: "She is good _______ painting landscapes.", opts: ["in", "**at**", "for", "with"] },
    { q: "We _______ to the park every morning for a walk.", opts: ["**go**", "going", "gone", "are going"] },
    { q: "The police _______ investigating the robbery.", opts: ["is", "**are**", "was", "has been"] },
    { q: "I'll see you _______ the evening at 7 PM.", opts: ["**in**", "on", "at", "to"] },
    { q: "He usually _______ his bed as soon as he wakes up.", opts: ["make", "**makes**", "making", "made"] },
    { q: "This is the _______ day of my life so far.", opts: ["good", "better", "**best**", "most good"] },
    { q: "They _______ for three hours when they found the spring.", opts: ["walk", "walked", "**had been walking**", "were walking"] },
    { q: "You _______ take an umbrella; it's going to rain.", opts: ["**should**", "may", "can", "might"] },
    { q: "The room was _______ with beautiful flowers.", opts: ["fill", "filling", "**filled**", "full"] },
    { q: "He _______ to the party because he was not feeling well.", opts: ["didn't go", "doesn't go", "won't go", "**hasn't gone**"] },
    { q: "This is _______ house where I used to live.", opts: ["a", "an", "**the**", "some"] },
    { q: "The shoes were _______ tight for him to wear.", opts: ["so", "enough", "**too**", "very"] },
    { q: "I would like _______ a reservation for two.", opts: ["make", "**to make**", "making", "made"] },
    { q: "He is _______ tallest man in the room.", opts: ["a", "an", "**the**", "one"] },
    { q: "I _______ a book when I heard a strange noise.", opts: ["read", "readed", "**was reading**", "have read"] },
    { q: "The man _______ sold me the car was very honest.", opts: ["which", "whom", "**who**", "whose"] },
    { q: "You _______ worry; everything will be fine.", opts: ["mustn't", "**needn't**", "shouldn't", "can't"] },
    { q: "She is as _______ as her twin sister.", opts: ["**talented**", "more talented", "most talented", "talent"] },
    { q: "They are _______ for the upcoming competition.", opts: ["train", "**training**", "trains", "trained"] },
    { q: "I _______ him for several years now.", opts: ["know", "am knowing", "**have known**", "knows"] },
    { q: "The committee _______ its final decision next week.", opts: ["make", "**will make**", "made", "has made"] },
    { q: "He is interested _______ learning how to cook.", opts: ["on", "at", "**in**", "for"] },
    { q: "This is the restaurant _______ we had our first date.", opts: ["who", "whom", "**where**", "whose"] },
    { q: "I _______ visit my grandparents this weekend.", opts: ["**might**", "must", "should", "will"] },
    { q: "She _______ been studying since early morning.", opts: ["is", "was", "**has**", "had"] },
    { q: "He is the person _______ car was stolen last night.", opts: ["who", "whom", "**whose**", "which"] },
    { q: "Neither of the shirts _______ me well.", opts: ["fit", "**fits**", "fitting", "fitted"] },
    { q: "I was so _______ when I heard the news.", opts: ["shock", "shocking", "**shocked**", "shocks"] },
    { q: "We should leave _______ the traffic gets too heavy.", opts: ["after", "since", "**before**", "until"] },
    { q: "The library _______ opened two years ago.", opts: ["is", "was", "**was opened**", "has opened"] },
    { q: "He is the kindest person _______ I have ever known.", opts: ["who", "whom", "**that**", "which"] },
    { q: "I don't have _______ time to waste.", opts: ["some", "**any**", "many", "few"] },
    { q: "She _______ her umbrella on the bus.", opts: ["leave", "left", "**has left**", "leaving"] },
    { q: "You _______ wear a seatbelt while driving.", opts: ["**must**", "may", "might", "could"] },
    { q: "He is _______ at sports than his brother.", opts: ["good", "best", "**better**", "well"] },
    { q: "We are going _______ a trip to the mountains.", opts: ["in", "**on**", "to", "at"] },
    { q: "The man _______ you saw at the bank is my boss.", opts: ["who", "**whom**", "whose", "which"] }];
QUESTIONS_DB.Common.English["2014"] = [{ q: "I _______ my lunch when the manager walked into the office.", opts: ["eat", "ate", "**was eating**", "have eaten"] },
    { q: "The woman _______ car was stolen is my English teacher.", opts: ["who", "whom", "**whose**", "which"] },
    { q: "If they _______ earlier, they wouldn't have missed the flight.", opts: ["leave", "left", "**had left**", "would leave"] },
    { q: "She has been working as a nurse _______ 2018.", opts: ["for", "**since**", "during", "at"] },
    { q: "Hardly _______ the room when everyone started cheering.", opts: ["did he enter", "**had he entered**", "he entered", "he had entered"] },
    { q: "The old bridge _______ by the government last month.", opts: ["repairs", "repaired", "**was repaired**", "is repaired"] },
    { q: "I am looking forward to _______ my family next holiday.", opts: ["visit", "visited", "**visiting**", "to visit"] },
    { q: "He is _______ most hardworking student in the class.", opts: ["a", "an", "**the**", "one"] },
    { q: "You _______ take photos here; it is strictly prohibited.", opts: ["shouldn't", "don't have to", "**mustn't**", "needn't"] },
    { q: "They _______ their dinner before the guests arrived.", opts: ["eat", "ate", "**had eaten**", "were eating"] },
    { q: "I would rather stay at home _______ go to the party.", opts: ["than", "**to**", "from", "for"] },
    { q: "The more you practice, _______ you will become at English.", opts: ["good", "best", "**the better**", "more good"] },
    { q: "She is very good _______ playing the piano.", opts: ["in", "on", "**at**", "with"] },
    { q: "Neither the players nor the coach _______ satisfied with the result.", opts: ["are", "**was**", "were", "be"] },
    { q: "I wish I _______ more time to finish the exam.", opts: ["have", "has", "**had**", "would have"] },
    { q: "He went to the store _______ buy some bread.", opts: ["for", "so", "**to**", "because"] },
    { q: "The bag is _______ heavy for the child to carry.", opts: ["so", "enough", "**too**", "very"] },
    { q: "I am not used to _______ early in the morning.", opts: ["get up", "got up", "**getting up**", "gets up"] },
    { q: "By next Friday, I _______ my assignment.", opts: ["finish", "will finish", "**will have finished**", "finished"] },
    { q: "She asked me where _______.", opts: ["do I live", "did I live", "**I lived**", "I live"] },
    { q: "He is responsible _______ cleaning the classroom.", opts: ["to", "with", "**for**", "at"] },
    { q: "_______ she was tired, she continued to study.", opts: ["Because", "**Although**", "Despite", "However"] },
    { q: "I don't know _______ pen this is.", opts: ["who", "**whose**", "which", "whom"] },
    { q: "We _______ each other for many years.", opts: ["know", "are knowing", "**have known**", "knew"] },
    { q: "Please wait here _______ I come back.", opts: ["**until**", "since", "while", "during"] },
    { q: "He is _______ honest man.", opts: ["a", "**an**", "the", "some"] },
    { q: "They suggested _______ to the cinema tonight.", opts: ["go", "to go", "**going**", "went"] },
    { q: "I will call you as soon as I _______ home.", opts: ["**get**", "will get", "got", "am getting"] },
    { q: "This exercise is _______ than the last one.", opts: ["easy", "**easier**", "easiest", "more easy"] },
    { q: "There is _______ milk left in the fridge.", opts: ["many", "**a little**", "a few", "any"] },
    { q: "The building _______ finished by next year.", opts: ["is", "was", "**will be**", "has been"] },
    { q: "I can't stand _______ in the rain.", opts: ["wait", "to wait", "**waiting**", "waited"] },
    { q: "If you _______ hard, you will pass the exam.", opts: ["**study**", "studied", "will study", "would study"] },
    { q: "I _______ my wallet. Have you seen it?", opts: ["**have lost**", "lost", "had lost", "lose"] },
    { q: "The tea was _______ hot that I couldn't drink it.", opts: ["too", "very", "**so**", "much"] },
    { q: "Who is in charge _______ the project?", opts: ["to", "with", "**of**", "at"] },
    { q: "She _______ in this school since 2015.", opts: ["works", "worked", "**has been working**", "is working"] },
    { q: "You _______ better see a doctor.", opts: ["should", "**had**", "would", "could"] },
    { q: "A new road _______ built in our town now.", opts: ["is", "was", "**is being**", "has been"] },
    { q: "None of the students _______ present today.", opts: ["are", "**is**", "were", "been"] },
    { q: "He was accused _______ stealing the money.", opts: ["for", "with", "**of**", "to"] },
    { q: "We are interested _______ learning new languages.", opts: ["on", "**in**", "at", "for"] },
    { q: "I _______ him since the graduation.", opts: ["didn't see", "don't see", "**haven't seen**", "am not seeing"] },
    { q: "The book _______ I bought is very interesting.", opts: ["who", "whom", "**which**", "whose"] },
    { q: "Please turn _______ the television.", opts: ["**off**", "on", "up", "to"] },
    { q: "Don't worry, we have _______ time.", opts: ["many", "few", "**plenty of**", "a little"] },
    { q: "They _______ their homework when the light went out.", opts: ["do", "did", "**were doing**", "have done"] },
    { q: "I _______ rather walk than take a taxi.", opts: ["should", "**would**", "could", "had"] },
    { q: "The teacher made the students _______ the lesson.", opts: ["repeat", "**to repeat**", "repeating", "repeated"] },
    { q: "She is the _______ girl in the class.", opts: ["pretty", "prettier", "**prettiest**", "most pretty"] },
    { q: "We need _______ water for the trip.", opts: ["an", "many", "**some**", "a"] },
    { q: "He arrived _______ the airport on time.", opts: ["in", "**at**", "to", "on"] },
    { q: "I don't think it _______ rain today.", opts: ["**will**", "is", "was", "has"] },
    { q: "My father _______ me to be a good person.", opts: ["suggested", "said", "**told**", "ordered"] },
    { q: "It is _______ today than it was yesterday.", opts: ["cold", "coldest", "**colder**", "more cold"] },
    { q: "Neither of the answers _______ correct.", opts: ["are", "**is**", "were", "be"] },
    { q: "You should avoid _______ late.", opts: ["come", "to come", "**coming**", "came"] },
    { q: "The news _______ very interesting.", opts: ["are", "**is**", "were", "been"] },
    { q: "He is looking _______ his keys.", opts: ["**for**", "at", "after", "to"] },
    { q: "I _______ my homework yet.", opts: ["didn't finish", "**haven't finished**", "don't finish", "hadn't finished"] },
    { q: "She _______ speak French very well.", opts: ["**can**", "may", "must", "might"] },
    { q: "The mountain was _______ high that we couldn't climb it.", opts: ["too", "very", "**so**", "much"] },
    { q: "He has _______ books than I do.", opts: ["few", "fewer", "**less**", "least"] },
    { q: "She is good _______ cooking.", opts: ["in", "**at**", "for", "with"] },
    { q: "We _______ to school every day.", opts: ["**go**", "going", "gone", "are going"] },
    { q: "The police _______ looking for the thief.", opts: ["is", "**are**", "was", "has been"] },
    { q: "I'll see you _______ the morning.", opts: ["**in**", "on", "at", "to"] },
    { q: "He usually _______ his homework in the evening.", opts: ["do", "**does**", "doing", "done"] },
    { q: "This is the _______ day of my life.", opts: ["good", "better", "**best**", "most good"] },
    { q: "They _______ for two hours when they stopped.", opts: ["walk", "walked", "**had been walking**", "were walking"] },
    { q: "You _______ take an umbrella; it's raining.", opts: ["**should**", "may", "can", "might"] },
    { q: "The room was _______ with smoke.", opts: ["fill", "filling", "**filled**", "full"] },
    { q: "He _______ to the party because he was sick.", opts: ["didn't go", "doesn't go", "won't go", "**hasn't gone**"] },
    { q: "This is _______ house I was talking about.", opts: ["a", "an", "**the**", "some"] },
    { q: "The shoes were _______ small for me.", opts: ["so", "enough", "**too**", "very"] },
    { q: "I would like _______ a cup of coffee.", opts: ["drink", "**to drink**", "drinking", "drank"] },
    { q: "He is _______ youngest child in the family.", opts: ["a", "an", "**the**", "one"] },
    { q: "I _______ a book when the phone rang.", opts: ["read", "readed", "**was reading**", "have read"] },
    { q: "The boy _______ lives next door is very smart.", opts: ["which", "whom", "**who**", "whose"] },
    { q: "You _______ worry; everything is fine.", opts: ["mustn't", "**needn't**", "shouldn't", "can't"] },
    { q: "She is as _______ as her mother.", opts: ["**beautiful**", "more beautiful", "most beautiful", "beauty"] },
    { q: "They are _______ for the exam.", opts: ["study", "**studying**", "studies", "studied"] },
    { q: "I _______ him since we were children.", opts: ["know", "am knowing", "**have known**", "knows"] },
    { q: "The students _______ their exams next week.", opts: ["take", "**will take**", "took", "have taken"] },
    { q: "He is interested _______ science.", opts: ["on", "at", "**in**", "for"] },
    { q: "This is the place _______ I was born.", opts: ["who", "whom", "**where**", "whose"] },
    { q: "I _______ visit my aunt this weekend.", opts: ["**might**", "must", "should", "will"] },
    { q: "She _______ been crying.", opts: ["is", "was", "**has**", "had"] },
    { q: "He is the man _______ son is a doctor.", opts: ["who", "whom", "**whose**", "which"] },
    { q: "Neither of the girls _______ here.", opts: ["are", "**is**", "were", "be"] },
    { q: "I was so _______ when I saw the gift.", opts: ["excite", "exciting", "**excited**", "excites"] },
    { q: "We should go _______ it rains.", opts: ["after", "since", "**before**", "until"] },
    { q: "The house _______ built ten years ago.", opts: ["build", "built", "**was built**", "is building"] },
    { q: "He is the best friend _______ I have.", opts: ["who", "whom", "**that**", "which"] },
    { q: "I don't have _______ money.", opts: ["some", "**any**", "many", "few"] },
    { q: "She _______ her keys.", opts: ["leave", "left", "**has left**", "leaving"] },
    { q: "You _______ listen to your teacher.", opts: ["**must**", "may", "might", "could"] },
    { q: "He is _______ at English than I am.", opts: ["good", "best", "**better**", "well"] },
    { q: "We are going _______ a journey.", opts: ["in", "**on**", "to", "at"] },
    { q: "The person _______ you saw is my brother.", opts: ["who", "**whom**", "whose", "which"] }];
QUESTIONS_DB.Common.English["2015"] = [{ q: "I _______ to the radio when the doorbell rang.", opts: ["listen", "listened", "**was listening**", "have listened"] },
    { q: "This is the city _______ I was born and raised.", opts: ["which", "that", "**where**", "whom"] },
    { q: "If she _______ faster, she would have won the race.", opts: ["runs", "ran", "**had run**", "would run"] },
    { q: "They have been married _______ twenty-five years.", opts: ["since", "**for**", "during", "at"] },
    { q: "Scarcely _______ the game started when it began to rain.", opts: ["did", "**had**", "was", "has"] },
    { q: "The broken window _______ by the wind last night.", opts: ["breaks", "broke", "**was broken**", "is broken"] },
    { q: "I am looking forward to _______ my exam results.", opts: ["get", "got", "**getting**", "to get"] },
    { q: "He is _______ most intelligent student in our school.", opts: ["a", "an", "**the**", "one"] },
    { q: "You _______ park here; it is a 'No Parking' zone.", opts: ["shouldn't", "don't have to", "**mustn't**", "needn't"] },
    { q: "She _______ her dinner before her friends arrived.", opts: ["eat", "ate", "**had eaten**", "was eating"] },
    { q: "I would rather study Biology _______ History.", opts: ["than", "**to**", "from", "for"] },
    { q: "The harder you work, _______ your results will be.", opts: ["good", "best", "**the better**", "more good"] },
    { q: "He is very good _______ playing the guitar.", opts: ["in", "on", "**at**", "with"] },
    { q: "Neither the principal nor the teachers _______ at the meeting.", opts: ["is", "**were**", "was", "be"] },
    { q: "I wish I _______ more time to finish the project.", opts: ["have", "has", "**had**", "would have"] },
    { q: "He went to the bank _______ get some cash.", opts: ["for", "so", "**to**", "because"] },
    { q: "The box is _______ heavy for me to lift alone.", opts: ["so", "enough", "**too**", "very"] },
    { q: "I am not used to _______ in such a cold climate.", opts: ["live", "lived", "**living**", "lives"] },
    { q: "By next year, they _______ the new bridge.", opts: ["finish", "will finish", "**will have finished**", "finished"] },
    { q: "She asked me if I _______ her a favor.", opts: ["do", "did", "**could do**", "can do"] },
    { q: "He is responsible _______ managing the finance department.", opts: ["to", "with", "**for**", "at"] },
    { q: "_______ it was raining, they went out for a walk.", opts: ["Because", "**Although**", "Despite", "However"] },
    { q: "I don't know _______ umbrella this is.", opts: ["who", "**whose**", "which", "whom"] },
    { q: "We _______ each other for a long time.", opts: ["know", "are knowing", "**have known**", "knew"] },
    { q: "Please wait here _______ the doctor is ready to see you.", opts: ["**until**", "since", "while", "during"] },
    { q: "She is _______ exceptionally talented artist.", opts: ["a", "**an**", "the", "some"] },
    { q: "They suggested _______ a taxi to the airport.", opts: ["take", "to take", "**taking**", "took"] },
    { q: "I will call you as soon as I _______ my results.", opts: ["**receive**", "will receive", "received", "am receiving"] },
    { q: "This car is _______ than my previous one.", opts: ["fast", "**faster**", "fastest", "more fast"] },
    { q: "There is _______ water left in the bottle.", opts: ["many", "**a little**", "a few", "any"] },
    { q: "The meeting _______ held in the main hall tomorrow.", opts: ["is", "was", "**will be**", "has been"] },
    { q: "I can't stand _______ in long queues.", opts: ["wait", "to wait", "**waiting**", "waited"] },
    { q: "If you _______ the truth, I will forgive you.", opts: ["**tell**", "told", "will tell", "would tell"] },
    { q: "I _______ my keys. Have you seen them anywhere?", opts: ["**have lost**", "lost", "had lost", "lose"] },
    { q: "The coffee is _______ hot that I can't drink it yet.", opts: ["too", "very", "**so**", "much"] },
    { q: "Who is in charge _______ this project?", opts: ["to", "with", "**of**", "at"] },
    { q: "She _______ for this company since 2010.", opts: ["works", "worked", "**has been working**", "is working"] },
    { q: "You _______ better finish your assignment today.", opts: ["should", "**had**", "would", "could"] },
    { q: "A new hospital _______ built in our village now.", opts: ["is", "was", "**is being**", "has been"] },
    { q: "None of the students _______ pass the difficult test.", opts: ["is", "**was**", "were", "been"] },
    { q: "He was accused _______ telling a lie.", opts: ["for", "with", "**of**", "to"] },
    { q: "We are interested _______ joining the club.", opts: ["on", "**in**", "at", "for"] },
    { q: "I _______ him since we met at the party.", opts: ["didn't see", "don't see", "**haven't seen**", "am not seeing"] },
    { q: "The movie _______ we watched last night was boring.", opts: ["who", "whom", "**which**", "whose"] },
    { q: "Please turn _______ the volume; it's too quiet.", opts: ["down", "off", "**up**", "to"] },
    { q: "Don't worry, we have _______ time before the flight.", opts: ["many", "few", "**plenty of**", "a little"] },
    { q: "They _______ their lunch when the phone rang.", opts: ["eat", "ate", "**were eating**", "have eaten"] },
    { q: "I _______ rather walk than take a bus.", opts: ["should", "**would**", "could", "had"] },
    { q: "The manager made the staff _______ overtime.", opts: ["work", "**to work**", "working", "worked"] },
    { q: "She is the _______ girl I have ever met.", opts: ["kind", "kinder", "**kindest**", "most kind"] },
    { q: "We need _______ help with these heavy boxes.", opts: ["an", "many", "**some**", "a"] },
    { q: "He arrived _______ home very late last night.", opts: ["in", "at", "to", "**(none)**"] },
    { q: "I don't think it _______ rain this afternoon.", opts: ["**will**", "is", "was", "has"] },
    { q: "My father _______ me to be careful.", opts: ["suggested", "said", "**told**", "ordered"] },
    { q: "It is _______ today than it was yesterday.", opts: ["warm", "warmest", "**warmer**", "more warm"] },
    { q: "Neither of the options _______ suitable for us.", opts: ["are", "**is**", "were", "be"] },
    { q: "You should avoid _______ late for class.", opts: ["come", "to come", "**coming**", "came"] },
    { q: "The news _______ not very encouraging.", opts: ["are", "**is**", "were", "been"] },
    { q: "He is looking _______ his glasses.", opts: ["**for**", "at", "after", "to"] },
    { q: "I _______ my breakfast yet.", opts: ["didn't have", "**haven't had**", "don't have", "hadn't had"] },
    { q: "She _______ play the violin beautifully.", opts: ["**can**", "may", "must", "might"] },
    { q: "The wall was _______ high that he couldn't jump over it.", opts: ["too", "very", "**so**", "much"] },
    { q: "He has _______ money than his brother.", opts: ["few", "fewer", "**less**", "least"] },
    { q: "She is good _______ dancing.", opts: ["in", "**at**", "for", "with"] },
    { q: "We _______ to the church every Sunday.", opts: ["**go**", "going", "gone", "are going"] },
    { q: "The police _______ patrolling the area.", opts: ["is", "**are**", "was", "has been"] },
    { q: "I'll see you _______ the afternoon.", opts: ["**in**", "on", "at", "to"] },
    { q: "He usually _______ his homework in the evening.", opts: ["do", "**does**", "doing", "done"] },
    { q: "This is the _______ day of the year.", opts: ["long", "longer", "**longest**", "most long"] },
    { q: "They _______ for two hours when they got tired.", opts: ["work", "worked", "**had been working**", "were working"] },
    { q: "You _______ wear a helmet when riding a bike.", opts: ["**should**", "may", "can", "might"] },
    { q: "The bag was _______ with old books.", opts: ["fill", "filling", "**filled**", "full"] },
    { q: "He _______ to the meeting because he was busy.", opts: ["didn't go", "doesn't go", "won't go", "**hasn't gone**"] },
    { q: "This is _______ car I bought last week.", opts: ["a", "an", "**the**", "some"] },
    { q: "The dress was _______ small for her.", opts: ["so", "enough", "**too**", "very"] },
    { q: "I would like _______ some fruit juice.", opts: ["drink", "**to drink**", "drinking", "drank"] },
    { q: "He is _______ youngest boy in the class.", opts: ["a", "an", "**the**", "one"] },
    { q: "I _______ a movie when the lights went out.", opts: ["watch", "watched", "**was watching**", "have watched"] },
    { q: "The man _______ lives next door is very friendly.", opts: ["which", "whom", "**who**", "whose"] },
    { q: "You _______ buy a ticket; I have already bought one.", opts: ["mustn't", "**needn't**", "shouldn't", "can't"] },
    { q: "She is as _______ as her sister.", opts: ["**clever**", "more clever", "most clever", "cleverly"] },
    { q: "They are _______ for their graduation.", opts: ["prepare", "**preparing**", "prepares", "prepared"] },
    { q: "I _______ him since we were in high school.", opts: ["know", "am knowing", "**have known**", "knows"] },
    { q: "The company _______ its new product next month.", opts: ["launch", "**will launch**", "launched", "has launched"] },
    { q: "He is interested _______ ancient history.", opts: ["on", "at", "**in**", "for"] },
    { q: "This is the place _______ we met for the first time.", opts: ["who", "whom", "**where**", "whose"] },
    { q: "I _______ go to the cinema tonight.", opts: ["**might**", "must", "should", "will"] },
    { q: "She _______ been sleeping since 10 PM.", opts: ["is", "was", "**has**", "had"] },
    { q: "He is the student _______ score was the highest.", opts: ["who", "whom", "**whose**", "which"] },
    { q: "Neither of the two roads _______ to the city.", opts: ["lead", "**leads**", "leading", "led"] },
    { q: "I was so _______ that I couldn't say a word.", opts: ["surprise", "surprising", "**surprised**", "surprises"] },
    { q: "We should arrive _______ the sun sets.", opts: ["after", "since", "**before**", "until"] },
    { q: "The school _______ built five years ago.", opts: ["build", "built", "**was built**", "is building"] },
    { q: "He is the best teacher _______ I have ever had.", opts: ["who", "whom", "**that**", "which"] },
    { q: "I don't have _______ bread left.", opts: ["some", "**any**", "many", "few"] },
    { q: "She _______ her keys on the table.", opts: ["leave", "left", "**has left**", "leaving"] },
    { q: "You _______ respect your parents.", opts: ["**must**", "may", "might", "could"] },
    { q: "He is _______ at Math than his brother.", opts: ["good", "best", "**better**", "well"] },
    { q: "We are going _______ a vacation next week.", opts: ["in", "**on**", "to", "at"] },
    { q: "The lady _______ you were talking to is my aunt.", opts: ["who", "**whom**", "whose", "which"] }];
QUESTIONS_DB.Common.English["2016"] = [{ q: "I _______ my lunch when the manager walked into the office.", opts: ["eat", "ate", "**was eating**", "have eaten"] },
    { q: "The woman _______ car was stolen is my English teacher.", opts: ["who", "whom", "**whose**", "which"] },
    { q: "If they _______ earlier, they wouldn't have missed the flight.", opts: ["leave", "left", "**had left**", "would leave"] },
    { q: "She has been working as a nurse _______ 2018.", opts: ["for", "**since**", "during", "at"] },
    { q: "Hardly _______ the room when everyone started cheering.", opts: ["did he enter", "**had he entered**", "he entered", "he had entered"] },
    { q: "The old bridge _______ by the government last month.", opts: ["repairs", "repaired", "**was repaired**", "is repaired"] },
    { q: "I am looking forward to _______ my family next holiday.", opts: ["visit", "visited", "**visiting**", "to visit"] },
    { q: "He is _______ most hardworking student in the class.", opts: ["a", "an", "**the**", "one"] },
    { q: "You _______ take photos here; it is strictly prohibited.", opts: ["shouldn't", "don't have to", "**mustn't**", "needn't"] },
    { q: "They _______ their dinner before the guests arrived.", opts: ["eat", "ate", "**had eaten**", "were eating"] },
    { q: "I would rather stay at home _______ go to the party.", opts: ["than", "**to**", "from", "for"] },
    { q: "The more you practice, _______ you will become at English.", opts: ["good", "best", "**the better**", "more good"] },
    { q: "She is very good _______ playing the piano.", opts: ["in", "on", "**at**", "with"] },
    { q: "Neither the players nor the coach _______ satisfied with the result.", opts: ["are", "**was**", "were", "be"] },
    { q: "I wish I _______ more time to finish the exam.", opts: ["have", "has", "**had**", "would have"] },
    { q: "He went to the store _______ buy some bread.", opts: ["for", "so", "**to**", "because"] },
    { q: "The bag is _______ heavy for the child to carry.", opts: ["so", "enough", "**too**", "very"] },
    { q: "I am not used to _______ early in the morning.", opts: ["get up", "got up", "**getting up**", "gets up"] },
    { q: "By next Friday, I _______ my assignment.", opts: ["finish", "will finish", "**will have finished**", "finished"] },
    { q: "She asked me where _______.", opts: ["do I live", "did I live", "**I lived**", "I live"] },
    { q: "He is responsible _______ cleaning the classroom.", opts: ["to", "with", "**for**", "at"] },
    { q: "_______ she was tired, she continued to study.", opts: ["Because", "**Although**", "Despite", "However"] },
    { q: "I don't know _______ pen this is.", opts: ["who", "**whose**", "which", "whom"] },
    { q: "We _______ each other for many years.", opts: ["know", "are knowing", "**have known**", "knew"] },
    { q: "Please wait here _______ I come back.", opts: ["**until**", "since", "while", "during"] },
    { q: "He is _______ honest man.", opts: ["a", "**an**", "the", "some"] },
    { q: "They suggested _______ to the cinema tonight.", opts: ["go", "to go", "**going**", "went"] },
    { q: "I will call you as soon as I _______ home.", opts: ["**get**", "will get", "got", "am getting"] },
    { q: "This exercise is _______ than the last one.", opts: ["easy", "**easier**", "easiest", "more easy"] },
    { q: "There is _______ milk left in the fridge.", opts: ["many", "**a little**", "a few", "any"] },
    { q: "The building _______ finished by next year.", opts: ["is", "was", "**will be**", "has been"] },
    { q: "I can't stand _______ in the rain.", opts: ["wait", "to wait", "**waiting**", "waited"] },
    { q: "If you _______ hard, you will pass the exam.", opts: ["**study**", "studied", "will study", "would study"] },
    { q: "I _______ my wallet. Have you seen it?", opts: ["**have lost**", "lost", "had lost", "lose"] },
    { q: "The tea was _______ hot that I couldn't drink it.", opts: ["too", "very", "**so**", "much"] },
    { q: "Who is in charge _______ the project?", opts: ["to", "with", "**of**", "at"] },
    { q: "She _______ in this school since 2015.", opts: ["works", "worked", "**has been working**", "is working"] },
    { q: "You _______ better see a doctor.", opts: ["should", "**had**", "would", "could"] },
    { q: "A new road _______ built in our town now.", opts: ["is", "was", "**is being**", "has been"] },
    { q: "None of the students _______ present today.", opts: ["are", "**is**", "were", "been"] },
    { q: "He was accused _______ stealing the money.", opts: ["for", "with", "**of**", "to"] },
    { q: "We are interested _______ learning new languages.", opts: ["on", "**in**", "at", "for"] },
    { q: "I _______ him since the graduation.", opts: ["didn't see", "don't see", "**haven't seen**", "am not seeing"] },
    { q: "The book _______ I bought is very interesting.", opts: ["who", "whom", "**which**", "whose"] },
    { q: "Please turn _______ the television.", opts: ["**off**", "on", "up", "to"] },
    { q: "Don't worry, we have _______ time.", opts: ["many", "few", "**plenty of**", "a little"] },
    { q: "They _______ their homework when the light went out.", opts: ["do", "did", "**were doing**", "have done"] },
    { q: "I _______ rather walk than take a taxi.", opts: ["should", "**would**", "could", "had"] },
    { q: "The teacher made the students _______ the lesson.", opts: ["repeat", "**to repeat**", "repeating", "repeated"] },
    { q: "She is the _______ girl in the class.", opts: ["pretty", "prettier", "**prettiest**", "most pretty"] },
    { q: "We need _______ water for the trip.", opts: ["an", "many", "**some**", "a"] },
    { q: "He arrived _______ the airport on time.", opts: ["in", "**at**", "to", "on"] },
    { q: "I don't think it _______ rain today.", opts: ["**will**", "is", "was", "has"] },
    { q: "My father _______ me to be a good person.", opts: ["suggested", "said", "**told**", "ordered"] },
    { q: "It is _______ today than it was yesterday.", opts: ["cold", "coldest", "**colder**", "more cold"] },
    { q: "Neither of the answers _______ correct.", opts: ["are", "**is**", "were", "be"] },
    { q: "You should avoid _______ coming late.", opts: ["come", "to come", "**coming**", "came"] },
    { q: "The news _______ very interesting.", opts: ["are", "**is**", "were", "been"] },
    { q: "He is looking _______ his keys.", opts: ["**for**", "at", "after", "to"] },
    { q: "I _______ my homework yet.", opts: ["didn't finish", "**haven't finished**", "don't finish", "hadn't finished"] },
    { q: "She _______ speak French very well.", opts: ["**can**", "may", "must", "might"] },
    { q: "The mountain was _______ high that we couldn't climb it.", opts: ["too", "very", "**so**", "much"] },
    { q: "He has _______ books than I do.", opts: ["few", "fewer", "**less**", "least"] },
    { q: "She is good _______ cooking.", opts: ["in", "**at**", "for", "with"] },
    { q: "We _______ to school every day.", opts: ["**go**", "going", "gone", "are going"] },
    { q: "The police _______ looking for the thief.", opts: ["is", "**are**", "was", "has been"] },
    { q: "I'll see you _______ the morning.", opts: ["**in**", "on", "at", "to"] },
    { q: "He usually _______ his homework in the evening.", opts: ["do", "**does**", "doing", "done"] },
    { q: "This is the _______ day of my life.", opts: ["good", "better", "**best**", "most good"] },
    { q: "They _______ for two hours when they stopped.", opts: ["walk", "walked", "**had been walking**", "were walking"] },
    { q: "You _______ take an umbrella; it's raining.", opts: ["**should**", "may", "can", "might"] },
    { q: "The room was _______ with smoke.", opts: ["fill", "filling", "**filled**", "full"] },
    { q: "He _______ to the party because he was sick.", opts: ["didn't go", "doesn't go", "won't go", "**hasn't gone**"] },
    { q: "This is _______ house I was talking about.", opts: ["a", "an", "**the**", "some"] },
    { q: "The shoes were _______ small for me.", opts: ["so", "enough", "**too**", "very"] },
    { q: "I would like _______ a cup of coffee.", opts: ["drink", "**to drink**", "drinking", "drank"] },
    { q: "He is _______ youngest child in the family.", opts: ["a", "an", "**the**", "one"] },
    { q: "I _______ a book when the phone rang.", opts: ["read", "readed", "**was reading**", "have read"] },
    { q: "The boy _______ lives next door is very smart.", opts: ["which", "whom", "**who**", "whose"] },
    { q: "You _______ worry; everything is fine.", opts: ["mustn't", "**needn't**", "shouldn't", "can't"] },
    { q: "She is as _______ as her mother.", opts: ["**beautiful**", "more beautiful", "most beautiful", "beauty"] },
    { q: "They are _______ for the exam.", opts: ["study", "**studying**", "studies", "studied"] },
    { q: "I _______ him since we were children.", opts: ["know", "am knowing", "**have known**", "knows"] },
    { q: "The students _______ their exams next week.", opts: ["take", "**will take**", "took", "have taken"] },
    { q: "He is interested _______ science.", opts: ["on", "at", "**in**", "for"] },
    { q: "This is the place _______ I was born.", opts: ["who", "whom", "**where**", "whose"] },
    { q: "I _______ visit my aunt this weekend.", opts: ["**might**", "must", "should", "will"] },
    { q: "She _______ been crying.", opts: ["is", "was", "**has**", "had"] },
    { q: "He is the man _______ son is a doctor.", opts: ["who", "whom", "**whose**", "which"] },
    { q: "Neither of the girls _______ here.", opts: ["are", "**is**", "were", "be"] },
    { q: "I was so _______ when I saw the gift.", opts: ["excite", "exciting", "**excited**", "excites"] },
    { q: "We should go _______ it rains.", opts: ["after", "since", "**before**", "until"] },
    { q: "The house _______ built ten years ago.", opts: ["build", "built", "**was built**", "is building"] },
    { q: "He is the best friend _______ I have.", opts: ["who", "whom", "**that**", "which"] },
    { q: "I don't have _______ money.", opts: ["some", "**any**", "many", "few"] },
    { q: "She _______ her keys.", opts: ["leave", "left", "**has left**", "leaving"] },
    { q: "You _______ listen to your teacher.", opts: ["**must**", "may", "might", "could"] },
    { q: "He is _______ at English than I am.", opts: ["good", "best", "**better**", "well"] },
    { q: "We are going _______ a journey.", opts: ["in", "**on**", "to", "at"] },
    { q: "The person _______ you saw is my brother.", opts: ["who", "**whom**", "whose", "which"] }];
QUESTIONS_DB.Common.English["2017"] = [{ q: "I _______ for my friend for over an hour before he finally arrived.", opts: ["wait", "waited", "**had been waiting**", "was waiting"] },
    { q: "The woman _______ house was destroyed in the fire is staying with us.", opts: ["who", "whom", "**whose**", "which"] },
    { q: "If I _______ you, I wouldn't go out in this heavy rain.", opts: ["am", "was", "**were**", "had been"] },
    { q: "They have been living in this neighborhood _______ 1995.", opts: ["for", "**since**", "at", "during"] },
    { q: "Hardly _______ the station when the train pulled out.", opts: ["I reached", "**had I reached**", "I had reached", "did I reach"] },
    { q: "The letter _______ by the secretary this morning.", opts: ["writes", "wrote", "**was written**", "is written"] },
    { q: "I am looking forward to _______ my relatives in the village.", opts: ["see", "saw", "**seeing**", "to see"] },
    { q: "He is _______ most talented athlete in our school.", opts: ["a", "an", "**the**", "one"] },
    { q: "You _______ smoke in the library; it is strictly forbidden.", opts: ["shouldn't", "don't have to", "**mustn't**", "needn't"] },
    { q: "They _______ their project before the teacher asked for it.", opts: ["finish", "finished", "**had finished**", "were finishing"] },
    { q: "I prefer reading books _______ watching television.", opts: ["than", "**to**", "from", "for"] },
    { q: "The harder you work, _______ your grades will be.", opts: ["good", "best", "**the better**", "more good"] },
    { q: "She is very good _______ solving mathematical problems.", opts: ["in", "on", "**at**", "with"] },
    { q: "Neither the students nor the teacher _______ aware of the change.", opts: ["are", "**was**", "were", "be"] },
    { q: "I wish I _______ more money for the trip last month.", opts: ["have", "has", "**had had**", "would have"] },
    { q: "He went to the post office _______ send a letter.", opts: ["for", "so", "**to**", "because"] },
    { q: "The table is _______ heavy for one person to move.", opts: ["so", "enough", "**too**", "very"] },
    { q: "I am not used to _______ in a noisy environment.", opts: ["work", "worked", "**working**", "works"] },
    { q: "By next year, they _______ the construction of the dam.", opts: ["finish", "will finish", "**will have finished**", "finished"] },
    { q: "She asked me where _______ my holidays.", opts: ["did I spend", "do I spend", "**I had spent**", "I spend"] },
    { q: "He is responsible _______ keeping the office clean.", opts: ["to", "with", "**for**", "at"] },
    { q: "_______ it was late, he decided to walk home.", opts: ["Because", "**Although**", "Despite", "However"] },
    { q: "I don't know _______ car that is parked outside.", opts: ["who", "**whose**", "which", "whom"] },
    { q: "We _______ each other since we were in primary school.", opts: ["know", "are knowing", "**have known**", "knew"] },
    { q: "Wait here _______ the bell rings.", opts: ["**until**", "since", "while", "during"] },
    { q: "He is _______ extremely hardworking person.", opts: ["a", "**an**", "the", "some"] },
    { q: "They suggested _______ to the park for a picnic.", opts: ["go", "to go", "**going**", "went"] },
    { q: "I will call you as soon as the results _______.", opts: ["**come out**", "will come out", "came out", "are coming out"] },
    { q: "This task is _______ than the previous one.", opts: ["difficult", "**more difficult**", "most difficult", "as difficult"] },
    { q: "There is _______ sugar left in the bowl.", opts: ["many", "**a little**", "a few", "any"] },
    { q: "The report _______ submitted by next Monday.", opts: ["is", "was", "**must be**", "has been"] },
    { q: "I can't stand _______ in such a crowded place.", opts: ["be", "to be", "**being**", "been"] },
    { q: "If you _______ the truth, I wouldn't be so angry.", opts: ["tell", "**had told**", "will tell", "would tell"] },
    { q: "I _______ my umbrella. Have you seen it?", opts: ["**have lost**", "lost", "had lost", "lose"] },
    { q: "The exam was _______ difficult that many students failed.", opts: ["too", "very", "**so**", "much"] },
    { q: "Who is in charge _______ this department?", opts: ["to", "with", "**of**", "at"] },
    { q: "She _______ as a teacher for twenty years.", opts: ["works", "worked", "**has been working**", "is working"] },
    { q: "You _______ better finish your homework now.", opts: ["should", "**had**", "would", "could"] },
    { q: "A new stadium _______ built in the city at the moment.", opts: ["is", "was", "**is being**", "has been"] },
    { q: "None of the water _______ clean enough to drink.", opts: ["are", "**is**", "were", "been"] },
    { q: "He was accused _______ stealing the jewelry.", opts: ["for", "with", "**of**", "to"] },
    { q: "We are interested _______ learning about African history.", opts: ["on", "**in**", "at", "for"] },
    { q: "I _______ him since he moved to Canada.", opts: ["didn't see", "don't see", "**haven't seen**", "am not seeing"] },
    { q: "The car _______ he bought last week is very fast.", opts: ["who", "whom", "**which**", "whose"] },
    { q: "Please turn _______ the lights before you go to bed.", opts: ["**off**", "on", "up", "to"] },
    { q: "Don't worry, we have _______ time to catch the bus.", opts: ["many", "few", "**plenty of**", "a little"] },
    { q: "They _______ their dinner when the lights went out.", opts: ["eat", "ate", "**were eating**", "have eaten"] },
    { q: "I _______ rather stay home than go to the party.", opts: ["should", "**would**", "could", "had"] },
    { q: "The teacher made the student _______ the blackboard.", opts: ["clean", "**to clean**", "cleaning", "cleaned"] },
    { q: "She is the _______ girl in her class.", opts: ["smart", "smarter", "**smartest**", "most smart"] },
    { q: "We need _______ salt for the soup.", opts: ["an", "many", "**some**", "a"] },
    { q: "He arrived _______ the airport very late.", opts: ["in", "**at**", "to", "on"] },
    { q: "I don't think it _______ rain today.", opts: ["**will**", "is", "was", "has"] },
    { q: "My mother _______ me to be careful on the road.", opts: ["suggested", "said", "**told**", "ordered"] },
    { q: "It is _______ today than it was yesterday.", opts: ["hot", "hottest", "**hotter**", "more hot"] },
    { q: "Neither of the two books _______ interesting.", opts: ["are", "**is**", "were", "be"] },
    { q: "You should avoid _______ too much coffee.", opts: ["drink", "to drink", "**drinking**", "drank"] },
    { q: "The news _______ very shocking to everyone.", opts: ["are", "**is**", "were", "been"] },
    { q: "He is looking _______ a new job.", opts: ["**for**", "at", "after", "to"] },
    { q: "I _______ my breakfast yet.", opts: ["didn't have", "**haven't had**", "don't have", "hadn't had"] },
    { q: "She _______ speak four languages fluently.", opts: ["**can**", "may", "must", "might"] },
    { q: "The tree was _______ high that he couldn't climb it.", opts: ["too", "very", "**so**", "much"] },
    { q: "He has _______ experience than his brother.", opts: ["few", "fewer", "**less**", "least"] },
    { q: "She is good _______ swimming.", opts: ["in", "**at**", "for", "with"] },
    { q: "We _______ to church every Sunday.", opts: ["**go**", "going", "gone", "are going"] },
    { q: "The police _______ looking for the missing child.", opts: ["is", "**are**", "was", "has been"] },
    { q: "I'll see you _______ the afternoon.", opts: ["**in**", "on", "at", "to"] },
    { q: "He usually _______ his bed in the morning.", opts: ["make", "**makes**", "making", "made"] },
    { q: "This is the _______ day of my life.", opts: ["good", "better", "**best**", "most good"] },
    { q: "They _______ for an hour when it started raining.", opts: ["walk", "walked", "**had been walking**", "were walking"] },
    { q: "You _______ take an umbrella; it's going to rain.", opts: ["**should**", "may", "can", "might"] },
    { q: "The room was _______ with beautiful paintings.", opts: ["fill", "filling", "**filled**", "full"] },
    { q: "He _______ to the party because he wasn't invited.", opts: ["didn't go", "doesn't go", "won't go", "**hasn't gone**"] },
    { q: "This is _______ house where I was born.", opts: ["a", "an", "**the**", "some"] },
    { q: "The dress was _______ small for her.", opts: ["so", "enough", "**too**", "very"] },
    { q: "I would like _______ a cup of tea.", opts: ["drink", "**to drink**", "drinking", "drank"] },
    { q: "He is _______ youngest boy in the class.", opts: ["a", "an", "**the**", "one"] },
    { q: "I _______ a book when the lights went out.", opts: ["read", "readed", "**was reading**", "have read"] },
    { q: "The man _______ lives next door is a pilot.", opts: ["which", "whom", "**who**", "whose"] },
    { q: "You _______ buy a ticket; I have an extra one.", opts: ["mustn't", "**needn't**", "shouldn't", "can't"] },
    { q: "She is as _______ as her mother.", opts: ["**beautiful**", "more beautiful", "most beautiful", "beauty"] },
    { q: "They are _______ for their final exams.", opts: ["prepare", "**preparing**", "prepares", "prepared"] },
    { q: "I _______ him since we were at university.", opts: ["know", "am knowing", "**have known**", "knows"] },
    { q: "The team _______ the trophy next week.", opts: ["win", "**will win**", "won", "has won"] },
    { q: "He is interested _______ learning how to play chess.", opts: ["on", "at", "**in**", "for"] },
    { q: "This is the restaurant _______ we had our dinner.", opts: ["who", "whom", "**where**", "whose"] },
    { q: "I _______ go to the cinema tonight.", opts: ["**might**", "must", "should", "will"] },
    { q: "She _______ been sleeping for two hours.", opts: ["is", "was", "**has**", "had"] },
    { q: "He is the boy _______ father is a famous actor.", opts: ["who", "whom", "**whose**", "which"] },
    { q: "Neither of the answers _______ correct.", opts: ["are", "**is**", "were", "be"] },
    { q: "I was so _______ when I heard the news.", opts: ["excite", "exciting", "**excited**", "excites"] },
    { q: "We should go _______ it gets dark.", opts: ["after", "since", "**before**", "until"] },
    { q: "The hospital _______ built five years ago.", opts: ["build", "built", "**was built**", "is building"] },
    { q: "He is the best teacher _______ I have ever had.", opts: ["who", "whom", "**that**", "which"] },
    { q: "I don't have _______ money left in my wallet.", opts: ["some", "**any**", "many", "few"] },
    { q: "She _______ her keys in the car.", opts: ["leave", "left", "**has left**", "leaving"] },
    { q: "You _______ follow the rules of the school.", opts: ["**must**", "may", "might", "could"] },
    { q: "He is _______ at English than his brother.", opts: ["good", "best", "**better**", "well"] },
    { q: "We are going _______ a trip next month.", opts: ["in", "**on**", "to", "at"] },
    { q: "The person _______ you were talking to is my uncle.", opts: ["who", "**whom**", "whose", "which"] }];
