// Geography Grade 12 Model Exam - Full 100 Questions (Strictly Sequential)
if (typeof QUESTIONS_DB === 'undefined') {
    var QUESTIONS_DB = { ModelExams: { "Natural": {}, "Social": {} } };
}

const geo_Final_100 = [
    { "q": "1. Who defined geography as 'the description of the earth'?", "opts": ["Kant", "**Eratosthenes**", "Humboldt", "Ritter"] },
    { "q": "2. Regional approach involves:", "opts": ["Systematic study", "**Dividing world into areas**", "Physical laws", "Human behavior"] },
    { "q": "3. Angular distance N or S of equator:", "opts": ["Longitude", "**Latitude**", "Altitude", "Grid"] },
    { "q": "4. Renewable resource:", "opts": ["Coal", "Gas", "**Solar**", "Oil"] },
    { "q": "5. Most abundant gas:", "opts": ["Oxygen", "**Nitrogen**", "CO2", "Argon"] },
    { "q": "6. Equatorial rainfall type:", "opts": ["Orographic", "Cyclonic", "**Convectional**", "Frontal"] },
    { "q": "7. Weather phenomena layer:", "opts": ["**Troposphere**", "Stratosphere", "Mesosphere", "Exosphere"] },
    { "q": "8. Landlocked East African country:", "opts": ["Kenya", "Somalia", "**Ethiopia**", "Sudan"] },
    { "q": "9. Prime meridian city:", "opts": ["Paris", "Tokyo", "**Greenwich**", "London"] },
    { "q": "10. Map scale 1cm to 5km:", "opts": ["1:500", "1:5000", "1:50000", "**1:500000**"] },
    { "q": "11. Earth's core composition:", "opts": ["Silica", "**Iron/Nickel**", "Magma", "Alum"] },
    { "q": "12. Continental Drift author:", "opts": ["Darwin", "**Wegener**", "Hess", "Morgan"] },
    { "q": "13. Cooling magma rock:", "opts": ["Sediment", "**Igneous**", "Meta", "Sand"] },
    { "q": "14. Largest ocean:", "opts": ["Atlantic", "Indian", "**Pacific**", "Arctic"] },
    { "q": "15. Earthquake intensity tool:", "opts": ["Baro", "**Seismo**", "Hygro", "Anemo"] },
    { "q": "16. Highest Africa mountain:", "opts": ["Dashen", "**Kilimanjaro**", "Kenya", "Atlas"] },
    { "q": "17. Cause of seasons:", "opts": ["Rotation", "**Axis tilt**", "Distance", "Currents"] },
    { "q": "18. Pressure measurement:", "opts": ["Thermo", "**Baro**", "Gauge", "Compass"] },
    { "q": "19. Best farming soil:", "opts": ["Sand", "Clay", "**Loam**", "Salt"] },
    { "q": "20. Rift Valley formation:", "opts": ["Folding", "**Faulting**", "Volcano", "Erosion"] },
    { "q": "21. Ethiopia surface area:", "opts": ["1M", "**1.1M**", "1.2M", "0.9M"] },
    { "q": "22. Largest lake in Ethiopia:", "opts": ["Abaya", "Chamo", "**Tana**", "Ziway"] },
    { "q": "23. Main export item:", "opts": ["Gold", "Leather", "**Coffee**", "Flower"] },
    { "q": "24. Pop growth formula:", "opts": ["B-D", "**(B-D)+M**", "B only", "M only"] },
    { "q": "25. Majority job in Ethiopia:", "opts": ["Industry", "Service", "**Agri**", "Mining"] },
    { "q": "26. High pressure belt 30 deg:", "opts": ["Low", "**Sub-high**", "Sub-low", "Polar"] },
    { "q": "27. Deforestation result:", "opts": ["Rain", "**Soil erosion**", "Oxygen", "Cold"] },
    { "q": "28. Polar map projection:", "opts": ["Cylin", "Conic", "**Azimuth**", "Merc"] },
    { "q": "29. Zero degree longitude:", "opts": ["Equator", "**Meridian**", "Cancer", "Circle"] },
    { "q": "30. Population study:", "opts": ["Carto", "Geology", "**Demo**", "Eco"] },
    { "q": "31. Atmosphere layers number:", "opts": ["3", "4", "**5**", "6"] },
    { "q": "32. Dryest desert in world:", "opts": ["Sahara", "Gobi", "**Atacama**", "Kalahari"] },
    { "q": "33. Longest river in world:", "opts": ["Amazon", "**Nile**", "Congo", "Yangtze"] },
    { "q": "34. Deepest point in ocean:", "opts": ["Java", "**Mariana**", "Tonga", "Puerto"] },
    { "q": "35. Rocks from heat/pressure:", "opts": ["Igneous", "Sediment", "**Metamorphic**", "Coal"] },
    { "q": "36. Largest continent by area:", "opts": ["Africa", "**Asia**", "N.America", "Europe"] },
    { "q": "37. Line joining equal pressure:", "opts": ["Isotherm", "**Isobar**", "Isohyet", "Contour"] },
    { "q": "38. Steep slope contours are:", "opts": ["Far apart", "**Close together**", "Crossing", "Straight"] },
    { "q": "39. GIS stands for:", "opts": ["**Geog Info System**", "Global Info", "Geog Intel", "Map System"] },
    { "q": "40. GPS uses how many satellites?", "opts": ["12", "**24**", "36", "48"] },
    { "q": "41. Ethiopia's lowest point:", "opts": ["Rift", "**Dallol**", "Ogaden", "Afar"] },
    { "q": "42. Main river of Abay basin:", "opts": ["Tekeze", "**Blue Nile**", "Baro", "Omo"] },
    { "q": "43. Most populated African country:", "opts": ["Egypt", "Ethiopia", "**Nigeria**", "Congo"] },
    { "q": "44. Type of map for themes:", "opts": ["General", "**Thematic**", "Topo", "Physical"] },
    { "q": "45. Representative Fraction (RF):", "opts": ["Words", "Line", "**Ratio/Fraction**", "Graph"] },
    { "q": "46. Standard time zones number:", "opts": ["12", "**24**", "36", "48"] },
    { "q": "47. Each time zone is how wide?", "opts": ["10 deg", "**15 deg**", "20 deg", "30 deg"] },
    { "q": "48. International Date Line is:", "opts": ["0 deg", "90 deg", "**180 deg**", "360 deg"] },
    { "q": "49. Plate tectonics driving force:", "opts": ["Gravity", "Wind", "**Convection currents**", "Tides"] },
    { "q": "50. Fold mountains example:", "opts": ["Rift", "**Himalayas**", "Kilimanjaro", "Vosges"] },
    { "q": "51. Igneous rock example:", "opts": ["Limestone", "Shale", "**Basalt**", "Marble"] },
    { "q": "52. Metamorphic version of limestone:", "opts": ["Slate", "Quartz", "**Marble**", "Gneiss"] },
    { "q": "53. Weathering by frost action:", "opts": ["Chemical", "**Physical**", "Biological", "Atomic"] },
    { "q": "54. Meander is a feature of:", "opts": ["Wind", "Glacier", "**River**", "Wave"] },
    { "q": "55. Delta forms at river:", "opts": ["Source", "**Mouth**", "Waterfall", "Valley"] },
    { "q": "56. Mushroom rock is formed by:", "opts": ["Water", "**Wind**", "Ice", "Waves"] },
    { "q": "57. Salinity of ocean average:", "opts": ["25%", "**35%**", "45%", "55%"] },
    { "q": "58. Tides are caused by:", "opts": ["Wind", "**Moon's gravity**", "Earthquakes", "Heat"] },
    { "q": "59. Warm ocean current example:", "opts": ["Canary", "**Gulf Stream**", "Benguela", "Peru"] },
    { "q": "60. Ecosystem study focus:", "opts": ["Rocks", "**Living/Non-living**", "Stars", "Maps"] },
    { "q": "61. Biome with permafrost:", "opts": ["Desert", "Savanna", "**Tundra**", "Taiga"] },
    { "q": "62. Largest tropical rainforest:", "opts": ["Congo", "**Amazon**", "Daintree", "Indo"] },
    { "q": "63. Greenhouse effect cause:", "opts": ["Oxygen", "**CO2/Methane**", "Nitrogen", "Argon"] },
    { "q": "64. Global warming result:", "opts": ["Ice growth", "**Sea level rise**", "More ozone", "Less rain"] },
    { "q": "65. Acid rain main cause:", "opts": ["Solar", "**Sulphur/Nitrogen oxides**", "Water", "Dust"] },
    { "q": "66. Sustainable development means:", "opts": ["Use all", "**Save for future**", "No use", "Fast growth"] },
    { "q": "67. Crude Birth Rate (CBR) is per:", "opts": ["100", "**1000**", "10000", "Million"] },
    { "q": "68. Push factor for migration:", "opts": ["Jobs", "**War/Famine**", "Peace", "Health"] },
    { "q": "69. Pull factor for migration:", "opts": ["Crime", "Disease", "**Better education**", "Drought"] },
    { "q": "70. Urbanization is growth of:", "opts": ["Farms", "**Cities**", "Forests", "Villages"] },
    { "q": "71. Primate city means:", "opts": ["Smallest", "**Disproportionately large**", "Industrial", "Coastal"] },
    { "q": "72. Primary economic activity:", "opts": ["**Farming**", "Factory", "Teaching", "Banking"] },
    { "q": "73. Secondary economic activity:", "opts": ["Mining", "**Manufacturing**", "Nursing", "Research"] },
    { "q": "74. Tertiary economic activity:", "opts": ["Fishing", "Lumbering", "**Tourism**", "Assembly"] },
    { "q": "75. Subsistence farming goal:", "opts": ["Export", "**Family consumption**", "Profit", "Tax"] },
    { "q": "76. Intensive agriculture needs:", "opts": ["Huge land", "**High labor/capital**", "No water", "No tools"] },
    { "q": "77. Commercial crop example:", "opts": ["Teff", "**Coffee/Rubber**", "Yam", "Potato"] },
    { "q": "78. Main energy source in Ethiopia:", "opts": ["Coal", "**Biomass/Wood**", "Nuclear", "Gas"] },
    { "q": "79. Renewable energy in Ethiopia:", "opts": ["Oil", "**Hydroelectric**", "Coal", "Gas"] },
    { "q": "80. GERD dam is on which river?", "opts": ["Omo", "Awash", "**Abay**", "Genale"] },
    { "q": "81. Ethiopia's main trading partner:", "opts": ["USA", "**China**", "Brazil", "Russia"] },
    { "q": "82. IGAD focuses on:", "opts": ["W.Africa", "**Horn of Africa**", "S.Africa", "N.Africa"] },
    { "q": "83. African Union (AU) HQ is in:", "opts": ["Nairobi", "Lagos", "**Addis Ababa**", "Cairo"] },
    { "q": "84. GIS data type for points/lines:", "opts": ["Raster", "**Vector**", "Pixel", "Grid"] },
    { "q": "85. Remote sensing tool:", "opts": ["Hammer", "**Satellite/Sensor**", "Scale", "Compass"] },
    { "q": "86. Map of Ethiopia is usually:", "opts": ["Large scale", "**Small scale**", "1:100", "1:500"] },
    { "q": "87. Highest peak in Ethiopia:", "opts": ["Batu", "**Ras Dashen**", "Guna", "Tulu Dimtu"] },
    { "q": "88. Largest drainage basin in Ethiopia:", "opts": ["Awash", "**Abay**", "Wabi Shebelle", "Omo"] },
    { "q": "89. Rift Valley lake without outlet:", "opts": ["Tana", "Ziway", "**Abaya/Chamo**", "Langen"] },
    { "q": "90. Ethiopia's 'Winter' is:", "opts": ["Kiremt", "**Bega**", "Belg", "Tseday"] },
    { "q": "91. IMR for country B (Table):", "opts": ["55.5", "**66.6**", "77.7", "88.8"] },
    { "q": "92. Less developed group:", "opts": ["A/C", "A/D", "**B/C**", "B/D"] },
    { "q": "93. Crude density country A:", "opts": ["**50 P/km2**", "45 P/km2", "40 P/km2", "55 P/km2"] },
    { "q": "94. Country D (0% rural) means:", "opts": ["No food", "No farm", "**Industrial focus**", "All urban"] },
    { "q": "95. Dependency ratio focus:", "opts": ["Adults", "**Young/Old**", "Workers", "Migrants"] },
    { "q": "96. Areal scale (1cm=0.5km):", "opts": ["**1cm2:0.25km2**", "1cm2:0.5km2", "1:1", "1:5"] },
    { "q": "97. Map elevation lines:", "opts": ["Isobars", "Isotherms", "**Contours**", "Isohyets"] },
    { "q": "98. Curved line measure tool:", "opts": ["Ruler", "**Opisometer**", "Protractor", "Scale"] },
    { "q": "99. V-contours to high ground:", "opts": ["Ridge", "Spur", "**Valley**", "Cliff"] },
    { "q": "100. Forest color on maps:", "opts": ["Blue", "Brown", "**Green**", "Yellow"] }
];

QUESTIONS_DB.ModelExams.Social["Geography"] = { "Model_2015_Full": geo_Final_100 };
console.log("Geography 100/100 Questions Loaded Successfully!");
