// 2017 History First Round Model Exam - Full 100 Questions (Complete)
if (!QUESTIONS_DB.ModelExams) QUESTIONS_DB.ModelExams = { "Natural": {}, "Social": {} };

QUESTIONS_DB.ModelExams.Social["History"] = {
    "Model_2017_Round_1": [
        { "q": "History as a field of study is primarily concerned with:", "opts": ["Predicting the future", "**The study of past human activities**", "The study of natural disasters", "The study of animal behavior"] },
        { "q": "Which of the following is considered a primary source of history?", "opts": ["History textbooks", "**Archaeological artifacts**", "Historical novels", "Biographies written decades later"] },
        { "q": "The process of critically examining the authenticity of a source is known as:", "opts": ["Historical Synthesis", "**Historical Criticism**", "Historical Imagination", "Historical Narrative"] },
        { "q": "In which period did humans begin to practice agriculture and animal domestication?", "opts": ["Paleolithic Age", "Mesolithic Age", "**Neolithic Age**", "Iron Age"] },
        { "q": "The ancient civilization that developed along the Nile River is:", "opts": ["Mesopotamia", "**Egyptian Civilization**", "Indus Valley Civilization", "Chinese Civilization"] },
        { "q": "The main reason for the decline of the Aksumite Empire was:", "opts": ["Internal rebellion", "**The expansion of Muslim Arabs across the Red Sea**", "Foreign invasion by the Romans", "The rise of the Zagwe dynasty"] },
        { "q": "The Zagwe dynasty is most famous for the rock-hewn churches of Lalibela. Who was the most renowned king of this dynasty?", "opts": ["Yekuno Amlak", "Mara Takla Haymanot", "**King Lalibela**", "King Gebre Meskel"] },
        { "q": "The restoration of the 'Solomonic' dynasty in 1270 was led by:", "opts": ["Amda Seyon", "**Yekuno Amlak**", "Zara Yaqob", "Eskender"] },
        { "q": "Which medieval Ethiopian king is known for his military expansions and the consolidation of the Christian Highland Kingdom?", "opts": ["Lalibela", "**Amda Seyon**", "Libne Dengel", "Galawdewos"] },
        { "q": "The capital of the Christian Kingdom was established at Gondar by:", "opts": ["Emperor Susenyos", "**Emperor Fasiladas**", "Emperor Iyasu I", "Emperor Bakaffa"] },
        { "q": "The period of Zemene Mesafint (Era of Judges) was characterized by:", "opts": ["A strong central government", "**The decline of imperial power and rise of regional lords**", "Massive foreign investment", "Peace and stability across the empire"] },
        { "q": "Who was the ruler that ended the Zemene Mesafint and unified Ethiopia?", "opts": ["Emperor Yohannes IV", "Emperor Menelik II", "**Emperor Tewodros II**", "Emperor Haile Selassie I"] },
        { "q": "The battle of Adwa in 1896 was a victory against which European power?", "opts": ["Britain", "France", "**Italy**", "Germany"] },
        { "q": "The Berlin Conference of 1884-1885 was significant because it:", "opts": ["Ended World War I", "**Regulated European colonization and trade in Africa**", "Abolished slavery globally", "Established the League of Nations"] },
        { "q": "Which African country remained independent during the Scramble for Africa, besides Ethiopia?", "opts": ["Ghana", "**Liberia**", "Nigeria", "Kenya"] },
        { "q": "The main cause of World War I was:", "opts": ["The Great Depression", "**Militarism, Alliances, Imperialism, and Nationalism (MAIN)**", "The rise of Nazi Germany", "The assassination of Abraham Lincoln"] },
        { "q": "The Russian Revolution of 1917 led to the rise of which political ideology?", "opts": ["Capitalism", "**Communism**", "Fascism", "Feudalism"] },
        { "q": "The League of Nations was created after WWI primarily to:", "opts": ["Encourage trade", "**Maintain world peace**", "Punish Germany", "Colonize Africa"] },
        { "q": "The Great Depression of 1929 began in which country?", "opts": ["Germany", "United Kingdom", "**United States**", "France"] },
        { "q": "Adolf Hitler was the leader of the:", "opts": ["Fascist Party in Italy", "**Nazi Party in Germany**", "Communist Party in Russia", "Labour Party in Britain"] },
        { "q": "World War II began in 1939 when Germany invaded:", "opts": ["France", "Russia", "**Poland**", "Austria"] },
        { "q": "The United Nations (UN) was established in 1945 to replace the:", "opts": ["OAU", "**League of Nations**", "NATO", "Warsaw Pact"] },
        { "q": "The Cold War was a period of tension between:", "opts": ["Germany and France", "**The USA and the USSR**", "China and Japan", "Britain and India"] },
        { "q": "The policy of Apartheid was a system of racial segregation in:", "opts": ["Namibia", "Zimbabwe", "**South Africa**", "Angola"] },
        { "q": "The Organization of African Unity (OAU) was founded in 1963 in:", "opts": ["Nairobi", "Cairo", "**Addis Ababa**", "Accra"] },
        { "q": "The first president of independent Ghana was:", "opts": ["Jomo Kenyatta", "Nelson Mandela", "**Kwame Nkrumah**", "Julius Nyerere"] },
        { "q": "The Cuban Missile Crisis of 1962 almost led to a nuclear war between:", "opts": ["Cuba and USA", "**USA and Soviet Union**", "Cuba and Soviet Union", "USA and China"] },
        { "q": "The Vietnam War was fought to prevent the spread of:", "opts": ["Democracy", "**Communism**", "Colonialism", "Religion"] },
        { "q": "The collapse of the Berlin Wall in 1989 symbolized the end of:", "opts": ["World War II", "**The Cold War**", "The French Revolution", "The Industrial Revolution"] },
        { "q": "Nelson Mandela became the first Black president of South Africa in:", "opts": ["1990", "**1994**", "1999", "1985"] },
        { "q": "The Industrial Revolution began in which country?", "opts": ["France", "Germany", "**Great Britain**", "USA"] },
        { "q": "The French Revolution of 1789 was inspired by the ideas of:", "opts": ["Mercantilism", "**The Enlightenment**", "Socialism", "Absolutism"] },
        { "q": "Who was the leader of the Haitian Revolution, the first successful slave revolt in the Americas?", "opts": ["Simon Bolivar", "**Toussaint L'Ouverture**", "Jose de San Martin", "Napoleon Bonaparte"] },
        { "q": "The 'Meiji Restoration' refers to the modernization of which country?", "opts": ["China", "**Japan**", "Korea", "Thailand"] },
        { "q": "The Opium Wars were fought between Great Britain and:", "opts": ["India", "**China**", "Japan", "Egypt"] },
        { "q": "The 'Scramble for Africa' reached its peak in the:", "opts": ["18th Century", "**Late 19th Century**", "Early 20th Century", "Mid-19th Century"] },
        { "q": "Which treaty ended World War I and imposed heavy reparations on Germany?", "opts": ["Treaty of Westphalia", "**Treaty of Versailles**", "Treaty of Utrecht", "Treaty of Paris"] },
        { "q": "The Bolsheviks were led by:", "opts": ["Joseph Stalin", "**Vladimir Lenin**", "Leon Trotsky", "Nicholas II"] },
        { "q": "The term 'Holocaust' refers to the genocide of Jews by:", "opts": ["The Soviet Union", "The Ottoman Empire", "**Nazi Germany**", "Imperial Japan"] },
        { "q": "The Marshall Plan was designed to:", "opts": ["Spread communism", "**Provide economic aid to rebuild post-WWII Europe**", "Establish colonies in Asia", "Build the Berlin Wall"] },
        { "q": "The 'Iron Curtain' was a term coined by:", "opts": ["Franklin D. Roosevelt", "Joseph Stalin", "**Winston Churchill**", "Harry Truman"] },
        { "q": "Which war started in 1950 and ended in a stalemate in 1953?", "opts": ["Vietnam War", "**Korean War**", "Gulf War", "Six-Day War"] },
        { "q": "The Pan-African movement aimed at:", "opts": ["Promoting European trade", "**Unifying people of African descent worldwide**", "Supporting colonial rule", "Dividing Africa into regions"] },
        { "q": "Which country is known as the 'Cradle of Mankind' due to numerous hominid fossil discoveries?", "opts": ["Egypt", "South Africa", "**Ethiopia**", "Tanzania"] },
        { "q": "The landmark fossil 'Lucy' (Dinknesh) was discovered in:", "opts": ["Olduvai Gorge", "**The Afar Triangle**", "The Omo Valley", "South Africa"] },
        { "q": "The first hominid to use fire and migrate out of Africa was:", "opts": ["Homo habilis", "**Homo erectus**", "Homo sapiens", "Australopithecus"] },
        { "q": "The Sabean migration to Northern Ethiopia influenced the rise of:", "opts": ["The Zagwe Kingdom", "The Funj Sultanate", "**The Aksumite Civilization**", "The Damat Kingdom"] },
        { "q": "The port of Adulis was essential for Aksum's:", "opts": ["Agriculture", "**International trade**", "Religious pilgrimage", "Military training"] },
        { "q": "Christianity was introduced to Aksum during the reign of:", "opts": ["King Kaleb", "**King Ezana**", "King Armah", "King Bazen"] },
        { "q": "The 16th-century conflict between the Christian Kingdom and the Adal Sultanate was led by:", "opts": ["Zara Yaqob", "**Ahmad ibn Ibrahim al-Ghazi (Gragn)**", "Libne Dengel", "Susenyos"] },
        { "q": "Which European country aided the Christian Kingdom during the war with Adal?", "opts": ["Britain", "**Portugal**", "Spain", "Turkey"] },
        { "q": "The Oromo population movement of the 16th century was mainly driven by:", "opts": ["Religious war", "**Social and demographic factors (Meda and Gadaa)**", "Foreign invasion", "Drought only"] },
        { "q": "The Gadaa system is a traditional social and political organization of the:", "opts": ["Amhara people", "**Oromo people**", "Tigray people", "Somali people"] },
        { "q": "The 'Jesuit' influence in the 17th century led to religious civil war under:", "opts": ["Emperor Fasiladas", "**Emperor Susenyos**", "Emperor Galawdewos", "Emperor Iyasu"] },
        { "q": "The rise of the Kingdom of Shoa in the 18th century was significant for the:", "opts": ["Spread of Islam", "**Future unification of Ethiopia**", "Decline of trade", "Rise of the Zagwe"] },
        { "q": "The Battle of Chelenqo (1887) led to the incorporation of:", "opts": ["Gondar", "**Harar**", "Kaffa", "Wolayta"] },
        { "q": "The Wuchale Treaty of 1889 was signed between Ethiopia and:", "opts": ["France", "Britain", "**Italy**", "Egypt"] },
        { "q": "The Italian occupation of Ethiopia (1936-1941) was ended by the help of:", "opts": ["The USA", "**The British and Ethiopian Patriots**", "The Soviet Union", "France"] },
        { "q": "The 1960 attempted coup d'état against Haile Selassie was led by:", "opts": ["The Derg", "**The Neway brothers**", "Mengistu Haile Mariam", "Aman Andom"] },
        { "q": "The Ethiopian Revolution of 1974 resulted in the overthrow of:", "opts": ["The Derg", "**Emperor Haile Selassie I**", "Lij Iyasu", "Empress Zewditu"] },
        { "q": "The Derg's official ideology was:", "opts": ["Capitalism", "**Marxism-Leninism**", "Liberalism", "Monarchism"] },
        { "q": "The 1977-1978 Ethio-Somali war was fought over the:", "opts": ["Eritrean region", "**Ogaden region**", "Afar region", "Gambella region"] },
        { "q": "The downfall of the Derg regime occurred in:", "opts": ["1974", "1984", "**1991**", "1995"] },
        { "q": "The Great Wall of China was built to:", "opts": ["Promote trade", "**Protect against northern nomadic invasions**", "Mark religious boundaries", "Control floods"] },
        { "q": "The Silk Road was a famous trade route connecting:", "opts": ["Africa and Europe", "**Asia and Europe**", "North and South America", "India and Australia"] },
        { "q": "The Renaissance began in which Italian city?", "opts": ["Rome", "**Florence**", "Venice", "Milan"] },
        { "q": "Who wrote 'The Prince', a famous book on political power?", "opts": ["Leonardo da Vinci", "**Niccolò Machiavelli**", "Dante Alighieri", "Michelangelo"] },
        { "q": "The Protestant Reformation was started by:", "opts": ["John Calvin", "**Martin Luther**", "Henry VIII", "Pope Leo X"] },
        { "q": "The discovery of the 'New World' by Christopher Columbus happened in:", "opts": ["1453", "**1492**", "1500", "1488"] },
        { "q": "The Atlantic Slave Trade is also known as the:", "opts": ["Silk Road", "**Triangular Trade**", "Trans-Saharan Trade", "Indian Ocean Trade"] },
        { "q": "The American War of Independence was fought against:", "opts": ["France", "**Great Britain**", "Spain", "The Netherlands"] },
        { "q": "The Declaration of Independence was primarily written by:", "opts": ["George Washington", "**Thomas Jefferson**", "Benjamin Franklin", "John Adams"] },
        { "q": "Napoleon Bonaparte was finally defeated at the Battle of:", "opts": ["Leipzig", "**Waterloo**", "Trafalgar", "Austerlitz"] },
        { "q": "The Suez Canal connects the Mediterranean Sea to the:", "opts": ["Atlantic Ocean", "**Red Sea**", "Indian Ocean", "Black Sea"] },
        { "q": "The Unification of Germany in 1871 was spearheaded by:", "opts": ["Wilhelm I", "**Otto von Bismarck**", "Frederick the Great", "Metternich"] },
        { "q": "The 'Boxer Rebellion' in China was an anti-______ movement.", "opts": ["Communist", "**Foreigner/Imperialist**", "Religious", "Peasant"] },
        { "q": "The 'Young Turks' movement aimed at reforming the:", "opts": ["Persian Empire", "**Ottoman Empire**", "Russian Empire", "Austro-Hungarian Empire"] },
        { "q": "The main trigger for the US entry into WWI was:", "opts": ["The attack on Pearl Harbor", "**Unrestricted submarine warfare by Germany**", "The invasion of France", "The Russian Revolution"] },
        { "q": "The 'Dust Bowl' was a significant event during the:", "opts": ["WWI", "**Great Depression**", "WWII", "Industrial Revolution"] },
        { "q": "The 'Night of Broken Glass' (Kristallnacht) was a targeted attack against:", "opts": ["Communists", "**Jews**", "Catholics", "Foreigners"] },
        { "q": "The 'Manhattan Project' was the secret US project to develop:", "opts": ["Jet engines", "**The Atomic Bomb**", "Radar technology", "The Computer"] },
        { "q": "The D-Day invasion took place in:", "opts": ["Italy", "**Normandy, France**", "Berlin, Germany", "London, UK"] },
        { "q": "The Cold War policy of 'Containment' aimed to stop the spread of:", "opts": ["Democracy", "**Communism**", "Fascism", "Imperialism"] },
        { "q": "The 'Great Leap Forward' was a policy implemented by:", "opts": ["Joseph Stalin", "**Mao Zedong**", "Ho Chi Minh", "Kim Il-sung"] },
        { "q": "The 1994 genocide in Africa took place in:", "opts": ["Sudan", "**Rwanda**", "Burundi", "Somalia"] },
        { "q": "The primary goal of the French Revolution was:", "opts": ["Restoring the Monarchy", "**Liberty, Equality, and Fraternity**", "Spreading Christianity", "Colonizing Africa"] },
        { "q": "Which invention revolutionized communication in the 15th century?", "opts": ["The Telegraph", "**The Printing Press**", "The Telephone", "The Radio"] },
        { "q": "The Magna Carta (1215) was important because it:", "opts": ["Gave the King absolute power", "**Limited the power of the King**", "Abolished the Parliament", "Ended feudalism"] },
        { "q": "The 'Middle Passage' refers to the journey of:", "opts": ["Spices from India", "**Slaves across the Atlantic**", "Gold from Africa", "Silk from China"] },
        { "q": "The 'Reign of Terror' is associated with which revolution?", "opts": ["American", "**French**", "Russian", "Industrial"] },
        { "q": "Simon Bolivar is known as the 'Liberator' of:", "opts": ["North America", "**South America**", "Africa", "Southeast Asia"] },
        { "q": "The primary cause of the 1857 Indian Mutiny was:", "opts": ["Land taxes", "**Religious and cultural grievances among soldiers (Sepoys)**", "Lack of education", "The Opium trade"] },
        { "q": "The 'Triple Entente' in WWI included Britain, France, and:", "opts": ["Germany", "**Russia**", "Italy", "Austria-Hungary"] },
        { "q": "The 'New Deal' was a series of programs by:", "opts": ["Herbert Hoover", "**Franklin D. Roosevelt**", "Woodrow Wilson", "Dwight Eisenhower"] },
        { "q": "The 'Salt March' was a non-violent protest led by:", "opts": ["Jawaharlal Nehru", "**Mahatma Gandhi**", "Subhash Chandra Bose", "Muhammad Ali Jinnah"] },
        { "q": "The first man to walk on the moon was:", "opts": ["Yuri Gagarin", "**Neil Armstrong**", "Buzz Aldrin", "John Glenn"] },
        { "q": "The 'Balfour Declaration' expressed British support for a Jewish home in:", "opts": ["Egypt", "**Palestine**", "Jordan", "Syria"] },
        { "q": "Which leader was the face of the struggle against Apartheid?", "opts": ["Desmond Tutu", "**Nelson Mandela**", "Steve Biko", "Thabo Mbeki"] },
        { "q": "The 1517 Ottoman conquest of Egypt ended the rule of the:", "opts": ["Fatimids", "**Mamluks**", "Ayyubids", "Abbasids"] },
        { "q": "Which US President made the decision to drop atomic bombs on Japan?", "opts": ["FDR", "**Harry S. Truman**", "Dwight Eisenhower", "John F. Kennedy"] }
    ]
};
