// maths.js - Common Subject Mathematics (2010 - 2017)
QUESTIONS_DB.Common.Maths["2010"] = [{ q: "If $f(x) = 2x + 3$ and $g(x) = x^2$, what is $(f \circ g)(2)$?", opts: ["14", "11", "**11**", "25"] },
    { q: "What is the derivative of $f(x) = \sin(x) + e^x$?", opts: ["$\cos(x) - e^x$", "**$\cos(x) + e^x$**", "$-\cos(x) + e^x$", "$\sin(x) + e^x$"] },
    { q: "The sum of the interior angles of a hexagon is:", opts: ["$360^\circ$", "$540^\circ$", "**$720^\circ$**", "$900^\circ$"] },
    { q: "Solve for $x$: $\log_2(x) = 5$.", opts: ["10", "25", "**32**", "64"] },
    { q: "What is the slope of the line $3x - 4y = 8$?", opts: ["$3/4$", "**$3/4$**", "$-3/4$", "$4/3$"] },
    { q: "Find the limit: $\lim_{x \to 0} \frac{\sin(x)}{x}$.", opts: ["0", "**1**", "$\infty$", "Undefined"] },
    { q: "If a matrix $A$ is $2 \times 3$ and $B$ is $3 \times 4$, the size of $AB$ is:", opts: ["$3 \times 3$", "$4 \times 2$", "**$2 \times 4$**", "$3 \times 4$"] },
    { q: "What is the value of $\int_0^1 x^2 dx$?", opts: ["1", "1/2", "**1/3**", "1/4"] },
    { q: "The distance between points $(1, 2)$ and $(4, 6)$ is:", opts: ["3", "4", "**5**", "7"] },
    { q: "In a right-angled triangle, if $a=3$ and $b=4$, the hypotenuse $c$ is:", opts: ["5", "**5**", "6", "7"] },
    { q: "What is the solution set of $x^2 - 5x + 6 = 0$?", opts: ["{1, 6}", "{-2, -3}", "**{2, 3}**", "{5, 0}"] },
    { q: "The arithmetic mean of 10, 20, and 30 is:", opts: ["15", "**20**", "25", "30"] },
    { q: "If $\cos(\theta) = 0$, what is a possible value for $\theta$?", opts: ["$0^\circ$", "**$90^\circ$**", "$180^\circ$", "$45^\circ$"] },
    { q: "The volume of a sphere with radius $r$ is:", opts: ["$\pi r^2$", "$2\pi r$", "**$\frac{4}{3}\pi r^3$**", "$\frac{1}{3}\pi r^2h$"] },
    { q: "What is the conjugate of the complex number $3 + 4i$?", opts: ["$-3 - 4i$", "$3 + 4i$", "**$3 - 4i$**", "$-3 + 4i$"] },
    { q: "Find $x$ if $2^{x+1} = 8$.", opts: ["1", "**2**", "3", "4"] },
    { q: "The determinant of $\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$ is:", opts: ["10", "2", "**-2**", "0"] },
    { q: "What is the $10^{th}$ term of the sequence $2, 4, 6, 8, \dots$?", opts: ["18", "**20**", "22", "24"] },
    { q: "If $P(A) = 0.3$ and $P(B) = 0.4$, and they are independent, $P(A \cap B)$ is:", opts: ["0.7", "0.1", "**0.12**", "0.5"] },
    { q: "The inverse of the function $f(x) = x - 5$ is:", opts: ["$5 - x$", "$1/(x-5)$", "**$x + 5$**", "$-x + 5$"] },
    { q: "What is the center of the circle $(x-1)^2 + (y+2)^2 = 9$?", opts: ["(-1, 2)", "**(1, -2)**", "(1, 2)", "(-1, -2)"] },
    { q: "The derivative of $x^n$ is:", opts: ["$x^{n+1}$", "$nx^n$", "**$nx^{n-1}$**", "$x^{n-1}$"] },
    { q: "If $a = \begin{pmatrix} 1 \\ 2 \end{pmatrix}$ and $b = \begin{pmatrix} 3 \\ 4 \end{pmatrix}$, then $a \cdot b$ is:", opts: ["7", "10", "**11**", "12"] },
    { q: "Simplify: $\sqrt{75}$.", opts: ["$3\sqrt{5}$", "$25\sqrt{3}$", "**$5\sqrt{3}$**", "$15\sqrt{5}$"] },
    { q: "The probability of flipping a coin and getting heads is:", opts: ["0", "1", "**0.5**", "0.25"] },
    { q: "What is the value of $5!$ (5 factorial)?", opts: ["60", "100", "**120**", "150"] },
    { q: "The area of a triangle with base 10 and height 5 is:", opts: ["50", "**25**", "15", "100"] },
    { q: "If $3x + 5 = 20$, then $x$ is:", opts: ["3", "4", "**5**", "6"] },
    { q: "What is $\tan(45^\circ)$?", opts: ["0", "0.5", "**1**", "$\sqrt{3}$"] },
    { q: "The midpoint of $(2, 4)$ and $(6, 8)$ is:", opts: ["(3, 5)", "**(4, 6)**", (2, 2), (8, 12)] },
    { q: "Which of these is a prime number?", opts: ["1", "9", "**17**", "21"] },
    { q: "The value of $e^0$ is:", opts: ["0", "**1**", "$e$", "Undefined"] },
    { q: "The number of subsets of a set with 3 elements is:", opts: ["3", "6", "**8**", "9"] },
    { q: "What is the range of $f(x) = x^2$?", opts: ["All real numbers", "**$y \geq 0$**", "$y > 0$", "$y \leq 0$"] },
    { q: "If the radius of a circle doubles, the area becomes:", opts: ["Double", "Triple", "**Four times**", "Same"] },
    { q: "Solve for $x$: $x/2 + 3 = 7$.", opts: ["2", "4", "**8**", "10"] },
    { q: "What is the square root of 144?", opts: ["10", "11", "**12**", "14"] },
    { q: "In the equation $y = mx + c$, $c$ represents:", opts: ["Slope", "**y-intercept**", "x-intercept", "Coordinate"] },
    { q: "What is the value of $\pi$ approximately?", opts: ["2.14", "**3.14**", "4.14", "1.14"] },
    { q: "The mode of the data 2, 3, 3, 4, 5 is:", opts: ["2", "**3**", "4", "5"] },
    { q: "If $\sin(\theta) = 1$, then $\theta$ is:", opts: ["$0^\circ$", "$45^\circ$","**$90^\circ$**", "$180^\circ$"] },
    { q: "The integral of a constant $k$ is:", opts: ["0", "$k$", "**$kx + C$**", "$k^2$"] },
    { q: "Which property is $a + b = b + a$?", opts: ["Associative", "**Commutative**", "Distributive", "Identity"] },
    { q: "What is the GCD of 12 and 18?", opts: ["2", "3", "**6**", "9"] },
    { q: "The value of $i^2$ in complex numbers is:", opts: ["1", "**-1**", "0", "$i$"] },
    { q: "A triangle with all three sides equal is called:", opts: ["Isosceles", "Scalene", "**Equilateral**", "Right"] },
    { q: "If $x^2 = 49$, then $x$ could be:", opts: ["6", "**7**", "8", "9"] },
    { q: "The perimeter of a square with side 5 is:", opts: ["10", "15", "**20**", "25"] },
    { q: "What is $\log_{10}(1000)$?", opts: ["1", "2", "**3**", "4"] },
    { q: "The derivative of $\ln(x)$ is:", opts: ["$e^x$", "$x$", "**$1/x$**", "$\ln(x)$"] },
    { q: "The binary equivalent of decimal 2 is:", opts: ["01", "**10**", "11", "00"] },
    { q: "The supplement of an angle of $60^\circ$ is:", opts: ["$30^\circ$", "$90^\circ$", "**$120^\circ$**", "$180^\circ$"] },
    { q: "What is $25\%$ of 200?", opts: ["25", "40", "**50**", "100"] },
    { q: "Find the median of 1, 3, 5, 7, 9.", opts: ["3", "**5**", "7", "4"] },
    { q: "The domain of $f(x) = \sqrt{x}$ is:", opts: ["All reals", "**$x \geq 0$**", "$x > 0$", "$x \neq 0$"] },
    { q: "If $y$ varies directly as $x$ and $y=10$ when $x=2$, find $y$ when $x=5$.", opts: ["20", "**25**", "30", "15"] },
    { q: "A polygon with 5 sides is a:", opts: ["Hexagon", "**Pentagon**", "Heptagon", "Octagon"] },
    { q: "What is the product of $(x+2)(x-2)$?", opts: ["$x^2+4$", "**$x^2-4$**", "$x^2-4x+4$", "$x^2+4x+4$"] },
    { q: "The sum of $1/2 + 1/4$ is:", opts: ["1/6", "2/6", "**3/4**", "1/2"] },
    { q: "What is the value of $\cos(0)$?", opts: ["0", "**1**", "-1", "0.5"] },
    { q: "Find the slope of the line passing through (0,0) and (2,4).", opts: ["1", "**2**", "3", "4"] },
    { q: "The value of $|-7|$ is:", opts: ["-7", "0", "**7**", "14"] },
    { q: "If a set $A = \{1, 2\}$ and $B = \{2, 3\}$, then $A \cup B$ is:", opts: ["{2}", "{1, 3}", "**{1, 2, 3}**", "{1, 2, 2, 3}"] },
    { q: "The coefficient of $x$ in $5x^2 - 3x + 7$ is:", opts: ["5", "7", "**-3**", "3"] },
    { q: "What is $10^0$?", opts: ["0", "**1**", "10", "100"] },
    { q: "The interior angle of a square is:", opts: ["$45^\circ$", "**$90^\circ$**", "$180^\circ$", "$360^\circ$"] },
    { q: "If $2x = 0$, then $x$ is:", opts: ["2", "**0**", "-2", "Undefined"] },
    { q: "The identity element for addition is:", opts: ["1", "**0**", "-1", "None"] },
    { q: "Simplify: $2(3x - 4) + 5$.", opts: ["$6x - 3$", "$6x + 3$", "**$6x - 3$**", "$6x - 8$"] },
    { q: "What is the probability of an impossible event?", opts: ["1", "0.5", "**0**", "-1"] },
    { q: "The area of a circle with radius 1 is:", opts: ["1", "$2\pi$", "**$\pi$**", "$\pi^2$"] },
    { q: "Convert 0.5 to a fraction.", opts: ["1/5", "**1/2**", "2/5", "1/4"] },
    { q: "Find $x$ if $x+x+x = 30$.", opts: ["5", "**10**", "15", "20"] },
    { q: "The LCM of 4 and 6 is:", opts: ["2", "10", "**12**", "24"] },
    { q: "The value of $\sin(30^\circ)$ is:", opts: ["1", "$\sqrt{3}/2$", "**1/2**", "0"] },
    { q: "A line that touches a circle at exactly one point is a:", opts: ["Chord", "Secant", "**Tangent**", "Diameter"] },
    { q: "If $f(x) = x^3$, then $f'(x)$ is:", opts: ["$x^2$", "$2x^3$", "**$3x^2$**", "$3x$"] },
    { q: "The sum of the angles in a triangle is:", opts: ["$90^\circ$", "**$180^\circ$**", "$270^\circ$", "$360^\circ$"] },
    { q: "What is the cube root of 27?", opts: ["2", "**3**", "9", "81"] },
    { q: "If $A$ is a subset of $B$, then $A \cap B$ is:", opts: ["$B$", "**$A$**", "$\emptyset$", "Universal Set"] },
    { q: "The value of $2^5$ is:", opts: ["10", "16", "**32**", "64"] },
    { q: "Find the average of 2, 4, 6, 8.", opts: ["4", "**5**", "6", "7"] },
    { q: "The volume of a cube with side 3 is:", opts: ["9", "18", "**27**", "81"] },
    { q: "The next prime number after 7 is:", opts: ["8", "9", "10", "**11**"] },
    { q: "The reciprocal of 2/3 is:", opts: ["-2/3", "1/3", "**3/2**", "2"] },
    { q: "What is $0 \times 15$?", opts: ["15", "**0**", "1", "Undefined"] },
    { q: "If $x - 7 = 0$, then $x$ is:", opts: ["-7", "0", "**7**", "14"] },
    { q: "The distance around a circle is called:", opts: ["Area", "Radius", "**Circumference**", "Volume"] },
    { q: "What is $1/2$ of $1/2$?", opts: ["1", "1/2", "**1/4**", "1/8"] },
    { q: "The side of a square with area 64 is:", opts: ["4", "6", "**8**", "16"] },
    { q: "Solve: $2x + 1 = 3$.", opts: ["0", "**1**", "2", "3"] },
    { q: "The value of $\sqrt{1}$ is:", opts: ["0", "**1**", "2", "Undefined"] },
    { q: "A right angle measures:", opts: ["$45^\circ$", "**$90^\circ$**", "$180^\circ$", "$360^\circ$"] },
    { q: "The smallest prime number is:", opts: ["1", "**2**", "3", "0"] },
    { q: "What is $100 \div 4$?", opts: ["20", "**25**", "50", "10"] },
    { q: "The value of $3^2 + 4^2$ is:", opts: ["7", "12", "**25**", "49"] },
    { q: "If $f(x) = 5$, then $f(10)$ is:", opts: ["10", "**5**", "50", "0"] },
    { q: "The number of degrees in a circle is:", opts: ["180", "**360**", "90", "540"] },
    { q: "What is the value of $x$ in $2x = 10$?", opts: ["2", "4", "**5**", "20"] },
    { q: "The sum of 0.1 and 0.2 is:", opts: ["0.03", "**0.3**", "0.12", "3.0"] }];
QUESTIONS_DB.Common.Maths["2011"] = [{ q: "What is the value of $\int_1^2 (3x^2 - 2x) dx$?", opts: ["3", "4", "**5**", "6"] },
    { q: "If $z = 1 + i$, then $z^2$ is equal to:", opts: ["2", "-2", "**2i**", "-2i"] },
    { q: "The focus of the parabola $y^2 = 12x$ is:", opts: ["(0, 3)", "**(3, 0)**", "(-3, 0)", "(0, -3)"] },
    { q: "Find the limit: $\lim_{x \to \infty} \frac{5x^2 - 3x}{2x^2 + 1}$.", opts: ["0", "1", "**2.5**", "$\infty$"] },
    { q: "What is the volume of a cone with radius 3 and height 4?", opts: ["$12\pi$", "**$12\pi$**", "$36\pi$", "$48\pi$"] },
    { q: "If $f(x) = \ln(x^2 + 1)$, then $f'(1)$ is:", opts: ["0", "1/2", "**1**", "2"] },
    { q: "The eccentricity of a circle is:", opts: ["**0**", "1", "0.5", "Undefined"] },
    { q: "Solve for $x$: $3^{2x-1} = 27$.", opts: ["1", "1.5", "**2**", "2.5"] },
    { q: "The dot product of $u = (2, -1)$ and $v = (3, 4)$ is:", opts: ["10", "6", "**2**", "-2"] },
    { q: "What is the period of the function $f(x) = \sin(2x)$?", opts: ["$2\pi$", "**$\pi$**", "$\pi/2$", "$4\pi$"] },
    { q: "If a die is rolled, what is the probability of getting a prime number?", opts: ["1/6", "1/3", "**1/2**", "2/3"] },
    { q: "The sum of the infinite geometric series $1 + 1/2 + 1/4 + \dots$ is:", opts: ["1.5", "**2**", "2.5", "$\infty$"] },
    { q: "What is the inverse of the matrix $\begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}$?", opts: ["$\begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix}$", "**$\begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}$**", "$\begin{pmatrix} -1 & 0 \\ 0 & -1 \end{pmatrix}$", "None"] },
    { q: "The slope of the tangent line to $y = x^2$ at $x = 3$ is:", opts: ["3", "4", "**6**", "9"] },
    { q: "Find the value of $\log_3(1/9)$.", opts: ["2", "1/2", "**-2**", "-1"] },
    { q: "The distance between the planes $z = 2$ and $z = 5$ is:", opts: ["2", "**3**", "5", "7"] },
    { q: "If $\vec{A} = (1, 2, 2)$, what is $|\vec{A}|$?", opts: ["3", "5", "**3**", "9"] },
    { q: "What is the area of a circle whose circumference is $10\pi$?", opts: ["$10\pi$", "$20\pi$", "**$25\pi$**", "$100\pi$"] },
    { q: "The derivative of $f(x) = \tan(x)$ is:", opts: ["$\cot(x)$", "$\sin^2(x)$", "**$\sec^2(x)$**", "$\cos^2(x)$"] },
    { q: "Solve the inequality: $2x - 5 > 7$.", opts: ["$x > 1$", "$x > 4$", "**$x > 6$**", "$x < 6$"] },
    { q: "The center of the ellipse $\frac{x^2}{9} + \frac{(y-3)^2}{4} = 1$ is:", opts: ["(0, 0)", "**(0, 3)**", "(3, 0)", "(3, 3)"] },
    { q: "What is the value of $\binom{5}{2}$?", opts: ["5", "**10**", "15", "20"] },
    { q: "If $f(x) = e^{2x}$, then $\int f(x) dx$ is:", opts: ["$2e^{2x} + C$", "**$\frac{1}{2}e^{2x} + C$**", "$e^{2x} + C$", "$e^{x} + C$"] },
    { q: "The angle between the vectors $(1, 0)$ and $(0, 1)$ is:", opts: ["$0^\circ$", "$45^\circ$", "**$90^\circ$**", "$180^\circ$"] },
    { q: "What is the units digit of $3^{20}$?", opts: ["3", "9", "7", "**1**"] },
    { q: "The median of 12, 15, 10, 20, 18 is:", opts: ["12", "**15**", "16", "18"] },
    { q: "If $\sin(\theta) = 3/5$ and $\theta$ is in quadrant I, $\cos(\theta)$ is:", opts: ["3/4", "**4/5**", "1/5", "4/3"] },
    { q: "The equation of the line through (0,0) with slope -1 is:", opts: ["$y = x$", "**$y = -x$**", "$y = 0$", "$x = 0$"] },
    { q: "What is $\sqrt[3]{-64}$?", opts: ["4", "**-4**", "8", "-8"] },
    { q: "The number of permutations of the letters in 'CAT' is:", opts: ["3", "**6**", "9", "27"] },
    { q: "Find $x$ if $\frac{x}{3} + \frac{x}{2} = 10$.", opts: ["6", "10", "**12**", "15"] },
    { q: "The sum of the roots of $x^2 - 7x + 10 = 0$ is:", opts: ["10", "5", "**7**", "-7"] },
    { q: "What is the value of $\cos(180^\circ)$?", opts: ["0", "1", "**-1**", "0.5"] },
    { q: "The domain of $f(x) = \frac{1}{x-2}$ is:", opts: ["All reals", "**$x \neq 2$**", "$x > 2$", "$x < 2$"] },
    { q: "What is the surface area of a cube with side 2?", opts: ["8", "12", "**24**", "16"] },
    { q: "Find the mean of the first five prime numbers.", opts: ["5", "**5.6**", "6", "6.2"] },
    { q: "The derivative of a constant is:", opts: ["1", "$x$", "**0**", "Constant"] },
    { q: "If $x^2 + y^2 = 25$, the radius of the circle is:", opts: ["5", "**5**", "25", "10"] },
    { q: "What is $15\% \text{ of } 300$?", opts: ["30", "40", "**45**", "50"] },
    { q: "The mode of 5, 8, 5, 10, 5, 2 is:", opts: ["2", "**5**", "8", "10"] },
    { q: "Simplify: $i^4$.", opts: ["$i$", "-1", "**1**", "$-i$"] },
    { q: "The intersection of $\{1, 2, 3\}$ and $\{3, 4, 5\}$ is:", opts: ["$\emptyset$", "{1, 2, 3, 4, 5}", "**{3}**", "{1, 5}"] },
    { q: "What is the value of $2^{-3}$?", opts: ["-6", "-8", "**1/8**", "1/6"] },
    { q: "A triangle with sides 5, 12, 13 is:", opts: ["Isosceles", "**Right-angled**", "Equilateral", "Acute"] },
    { q: "The slope of a horizontal line is:", opts: ["1", "**0**", "Undefined", "-1"] },
    { q: "What is $10! / 9!$?", opts: ["1", "9", "**10**", "90"] },
    { q: "If $\log(x) = 2$, then $x$ is:", opts: ["2", "20", "**100**", "10"] },
    { q: "The area of a square with diagonal $\sqrt{2}$ is:", opts: ["**1**", "2", "4", "0.5"] },
    { q: "The sum of angles in a quadrilateral is:", opts: ["$180^\circ$", "**$360^\circ$**", "$540^\circ$", "$720^\circ$"] },
    { q: "What is the remainder when 25 is divided by 4?", opts: ["0", "**1**", "2", "3"] },
    { q: "The derivative of $e^x$ is:", opts: ["$xe^{x-1}$", "$\ln(x)$", "**$e^x$**", "1"] },
    { q: "If $A = \{a, b\}$, the number of elements in the power set $P(A)$ is:", opts: ["2", "**4**", "3", "1"] },
    { q: "What is the value of $\sin^2(30^\circ) + \cos^2(30^\circ)$?", opts: ["0", "0.5", "**1**", "1.5"] },
    { q: "Solve: $x/5 = 4$.", opts: ["0.8", "9", "**20**", "1"] },
    { q: "The product of roots of $x^2 - 4x + 3 = 0$ is:", opts: ["-4", "4", "**3**", "-3"] },
    { q: "What is the y-intercept of $y = 2x - 7$?", opts: ["2", "7", "**-7**", "0"] },
    { q: "The sixth term of the sequence 3, 6, 12, 24... is:", opts: ["48", "**96**", "72", "120"] },
    { q: "A polygon with 8 sides is an:", opts: ["Hexagon", "Heptagon", "**Octagon**", "Decagon"] },
    { q: "The distance from (0,0) to (3,4) is:", opts: ["5", "**5**", "7", "25"] },
    { q: "What is $\tan(0^\circ)$?", opts: ["1", "$\infty$", "**0**", "0.5"] },
    { q: "If $3x = 0$, then $x$ is:", opts: ["3", "**0**", "-3", "Undefined"] },
    { q: "Find the area of a triangle with base 6 and height 8.", opts: ["48", "**24**", "14", "12"] },
    { q: "Which is a rational number?", opts: ["$\pi$", "$\sqrt{2}$", "**0.5**", "$\sqrt{3}$"] },
    { q: "What is the value of $0!$?", opts: ["0", "**1**", "Undefined", "10"] },
    { q: "The exterior angle of a regular triangle is:", opts: ["$60^\circ$", "$90^\circ$", "**$120^\circ$**", "$180^\circ$"] },
    { q: "Solve for $x$: $\sqrt{x} = 9$.", opts: ["3", "**81**", "18", "9"] },
    { q: "The range of $f(x) = \sin(x)$ is:", opts: ["All reals", "**[-1, 1]**", "[0, 1]", "(-1, 1)"] },
    { q: "What is $2^3 \times 2^2$?", opts: ["$2^6$", "$4^5$", "**$2^5$**", "12"] },
    { q: "The additive inverse of -5 is:", opts: ["1/5", "0", "**5**", "-5"] },
    { q: "The volume of a cube with side 4 is:", opts: ["16", "24", "**64**", "48"] },
    { q: "Find $x$ if $2x + 10 = 20$.", opts: ["10", "**5**", "2", "15"] },
    { q: "The GCD of 24 and 36 is:", opts: ["6", "**12**", "4", "8"] },
    { q: "What is $1/4$ as a percentage?", opts: ["2.5%", "4%", "**25%**", "40%"] },
    { q: "The square of 13 is:", opts: ["139", "166", "**169**", "196"] },
    { q: "If $y = x^3$, the second derivative $y''$ is:", opts: ["$3x^2$", "**$6x$**", "6", "$x^2$"] },
    { q: "A reflex angle is greater than:", opts: ["$90^\circ$", "**$180^\circ$**", "$270^\circ$", "$360^\circ$"] },
    { q: "The sum of $0.5 + 0.25$ is:", opts: ["0.6", "**0.75**", "0.8", "1.0"] },
    { q: "What is the degree of the polynomial $x^4 + 3x^2 + 1$?", opts: ["2", "**4**", "1", "0"] },
    { q: "Find the LCM of 5 and 7.", opts: ["12", "**35**", "1", "70"] },
    { q: "The value of $\log_5(5)$ is:", opts: ["0", "**1**", "5", "10"] },
    { q: "If a rectangle has length 5 and width 3, its perimeter is:", opts: ["8", "15", "**16**", "20"] },
    { q: "What is $1000^0$?", opts: ["0", "**1**", "1000", "Undefined"] },
    { q: "The interior angle of a regular hexagon is:", opts: ["$90^\circ$", "$108^\circ$", "**$120^\circ$**", "$140^\circ$"] },
    { q: "What is $\sin(90^\circ)$?", opts: ["0", "**1**", "-1", "0.5"] },
    { q: "The slope of the line $y = 5$ is:", opts: ["5", "1", "**0**", "Undefined"] },
    { q: "Find $x$: $5x - 5 = 20$.", opts: ["3", "4", "**5**", "6"] },
    { q: "The square root of 225 is:", opts: ["12", "13", "14", "**15**"] },
    { q: "What is $1/3$ of 90?", opts: ["20", "**30**", "60", "45"] },
    { q: "The complement of $40^\circ$ is:", opts: ["$140^\circ$", "**$50^\circ$**", "$90^\circ$", "$60^\circ$"] },
    { q: "The number of sides in a decagon is:", opts: ["12", "**10**", "8", "6"] },
    { q: "If $x + 5 = 5$, then $x$ is:", opts: ["5", "**0**", "-5", "10"] },
    { q: "What is the product of 12 and 11?", opts: ["121", "**132**", "144", "112"] },
    { q: "The value of $\pi$ is approximately:", opts: ["3.12", "**3.14**", "3.16", "3.18"] },
    { q: "A circle has how many tangents at a single point?", opts: ["0", "**1**", "2", "Infinite"] },
    { q: "What is $2^4$?", opts: ["8", "12", "**16**", "32"] },
    { q: "The value of $|-100|$ is:", opts: ["-100", "0", "**100**", "1"] },
    { q: "Solve: $3x = 9$.", opts: ["1", "2", "**3**", "6"] },
    { q: "The smallest prime number is:", opts: ["1", "**2**", "3", "0"] },
    { q: "What is $50 \times 2$?", opts: ["50", "25", "**100**", "200"] },
    { q: "The area of a circle with radius $r$ is:", opts: ["$2\pi r$", "**$\pi r^2$**", "$\pi d$", "$r^2$"] }];
QUESTIONS_DB.Common.Maths["2012"] = [{ q: "If $f(x) = \sqrt{x^2 - 9}$, what is the domain of $f$?", opts: ["$x \geq 3$", "$x \leq -3$", "**$|x| \geq 3$**", "$x > 3$"] },
    { q: "What is the limit: $\lim_{x \to 2} \frac{x^2 - 4}{x - 2}$?", opts: ["2", "0", "**4**", "$\infty$"] },
    { q: "The derivative of $f(x) = \cos(2x)$ is:", opts: ["$2\sin(2x)$", "**$-2\sin(2x)$**", "$\sin(2x)$", "$-\sin(2x)$"] },
    { q: "Find the value of $\int_0^\pi \sin(x) dx$.", opts: ["0", "1", "**2**", "-2"] },
    { q: "What is the modulus of the complex number $z = 3 - 4i$?", opts: ["1", "7", "**5**", "25"] },
    { q: "The scalar product of $u = (1, 2, 3)$ and $v = (4, 5, 6)$ is:", opts: ["15", "28", "**32**", "38"] },
    { q: "The center and radius of $x^2 + y^2 - 4x + 6y - 3 = 0$ are:", opts: ["(2, -3), 4", "**(2, -3), 4**", "(-2, 3), 16", "(4, -6), 3"] },
    { q: "If $2^{x-3} = 32$, then $x$ is:", opts: ["5", "2", "**8**", "7"] },
    { q: "What is the sum of the first 20 even natural numbers?", opts: ["210", "400", "**420**", "440"] },
    { q: "The slope of the line perpendicular to $y = 2x + 5$ is:", opts: ["2", "-2", "1/2", "**-1/2**"] },
    { q: "Find the inverse of $f(x) = \frac{x+1}{x-2}$.", opts: ["$\frac{x-2}{x+1}$", "**$\frac{2x+1}{x-1}$**", "$\frac{2x-1}{x+1}$", "$\frac{x+2}{x-1}$"] },
    { q: "The probability of drawing an Ace from a standard deck of 52 cards is:", opts: ["1/52", "1/26", "**1/13**", "4/13"] },
    { q: "What is the value of $\log_{10}(0.01)$?", opts: ["2", "1", "**-2**", "-1"] },
    { q: "The arithmetic mean of $x, x+2, x+4$ is:", opts: ["x", "x+1", "**x+2**", "3x+6"] },
    { q: "What is the derivative of $f(x) = \ln(3x)$?", opts: ["$3/x$", "$1/3x$", "**$1/x$**", "$\ln(3)$"] },
    { q: "The distance between the point $(2, 3)$ and the line $3x + 4y - 8 = 0$ is:", opts: ["1", "**2**", "3", "4"] },
    { q: "If $\tan(\theta) = 1$, then $\sin(2\theta)$ is:", opts: ["0", "1/2", "**1**", "$\sqrt{2}$"] },
    { q: "The volume of a sphere with diameter 6 is:", opts: ["$12\pi$", "$24\pi$", "**$36\pi$**", "$288\pi$"] },
    { q: "Find the solution set of $|2x - 1| = 5$.", opts: ["{3}", "{-2}", "**{3, -2}**", "{-3, 2}"] },
    { q: "What is the coefficient of $x^2$ in the expansion of $(x + 2)^4$?", opts: ["8", "12", "**24**", "16"] },
    { q: "The geometric mean of 4 and 16 is:", opts: ["10", "6", "**8**", "12"] },
    { q: "If $A = \begin{pmatrix} 1 & 2 \\ 0 & 1 \end{pmatrix}$, then $A^2$ is:", opts: ["$\begin{pmatrix} 1 & 4 \\ 0 & 1 \end{pmatrix}$", "**$\begin{pmatrix} 1 & 4 \\ 0 & 1 \end{pmatrix}$**", "$\begin{pmatrix} 2 & 4 \\ 0 & 2 \end{pmatrix}$", "$\begin{pmatrix} 1 & 2 \\ 0 & 1 \end{pmatrix}$"] },
    { q: "What is the value of $\sum_{n=1}^{5} (2n - 1)$?", opts: ["10", "15", "**25**", "20"] },
    { q: "The range of $f(x) = e^x$ is:", opts: ["All reals", "$y \geq 0$", "**$y > 0$**", "$y < 0$"] },
    { q: "What is the derivative of $f(x) = \frac{1}{x}$?", opts: ["$\ln(x)$", "$1/x^2$", "**$-1/x^2$**", "$-1/x$"] },
    { q: "If $\vec{a} = (2, 3)$ and $\vec{b} = (-1, 5)$, then $\vec{a} + \vec{b}$ is:", opts: ["(3, 8)", "(1, 2)", "**(1, 8)**", "(1, -2)"] },
    { q: "The vertical asymptote of $f(x) = \frac{x}{x-3}$ is:", opts: ["$y=3$", "$x=0$", "**$x=3$**", "$y=1$"] },
    { q: "What is $\sin(150^\circ)$?", opts: ["$\sqrt{3}/2$", "$-\sqrt{3}/2$", "**1/2**", "-1/2"] },
    { q: "Find the area of a sector with radius 6 and angle $60^\circ$.", opts: ["$3\pi$", "**$6\pi$**", "$12\pi$", "$36\pi$"] },
    { q: "The number of ways to arrange 5 people in a row is:", opts: ["25", "60", "**120**", "240"] },
    { q: "What is the square root of $i^2$?", opts: ["1", "-1", "**$i$**", "Undefined"] },
    { q: "If $\log_x 81 = 4$, then $x$ is:", opts: ["9", "2", "**3**", "4"] },
    { q: "The sum of the exterior angles of any convex polygon is:", opts: ["$180^\circ$", "**$360^\circ$**", "$540^\circ$", "$720^\circ$"] },
    { q: "What is the value of $P(6, 2)$?", opts: ["12", "15", "**30**", "36"] },
    { q: "The derivative of $f(x) = x^e$ is:", opts: ["$e^x$", "$x^e$", "**$ex^{e-1}$**", "$e \ln(x)$"] },
    { q: "Find $x$ if $x^2 - 9 = 0$.", opts: ["3", "-3", "**\pm 3**", "9"] },
    { q: "The median of 1, 8, 3, 9, 4 is:", opts: ["3", "**4**", "8", "5"] },
    { q: "What is $\cos(270^\circ)$?", opts: ["1", "-1", "**0**", "Undefined"] },
    { q: "The y-intercept of $f(x) = e^x + 2$ is:", opts: ["2", "1", "**3**", "0"] },
    { q: "If $f(x) = 3x^2$, find $\int f(x) dx$.", opts: ["$6x + C$", "$x^2 + C$", "**$x^3 + C$**", "$3x^3 + C$"] },
    { q: "The diagonal of a square with side 10 is:", opts: ["20", "10", "**10\sqrt{2}**", "100"] },
    { q: "What is $C(10, 9)$?", opts: ["1", "9", "**10**", "90"] },
    { q: "The product of $(2+i)(2-i)$ is:", opts: ["3", "4", "**5**", "3+4i"] },
    { q: "Find the slope of $x + y = 10$.", opts: ["1", "**-1**", "10", "0"] },
    { q: "What is $\sin(\pi/6)$?", opts: ["$\sqrt{3}/2$", "1", "**1/2**", "0"] },
    { q: "The derivative of $\sqrt{x}$ is:", opts: ["$2\sqrt{x}$", "$1/\sqrt{x}$", "**$1/(2\sqrt{x})$**", "$x^{-1/2}$"] },
    { q: "If $x/4 + 1 = 2$, then $x$ is:", opts: ["1", "2", "**4**", "8"] },
    { q: "The focus of $x^2 = 8y$ is:", opts: ["(2, 0)", "**(0, 2)**", "(0, -2)", "(4, 0)"] },
    { q: "What is $5! / 3!$?", opts: ["2", "10", "**20**", "120"] },
    { q: "The mode of 1, 2, 2, 3, 3, 3, 4 is:", opts: ["2", "**3**", "4", "1"] },
    { q: "Solve $e^x = 1$.", opts: ["1", "**0**", "$e$", "$\ln(1)$"] },
    { q: "The area of a square with perimeter 20 is:", opts: ["20", "400", "**25**", "100"] },
    { q: "What is the value of $i^{10}$?", opts: ["$i$", "-$i$", "1", "**-1**"] },
    { q: "The midpoint of (1, 1) and (5, 5) is:", opts: ["(2, 2)", "**(3, 3)**", "(4, 4)", "(6, 6)"] },
    { q: "If $\cos(\theta) = 1/2$, find $\theta$ in $[0, \pi/2]$.", opts: ["$30^\circ$", "$45^\circ$", "**$60^\circ$**", "$90^\circ$"] },
    { q: "The derivative of $x^2 + 2x + 1$ is:", opts: ["$2x$", "$x+2$", "**$2x+2$**", "2"] },
    { q: "Find the range of $f(x) = |x|$.", opts: ["All reals", "**$y \geq 0$**", "$y > 0$", "$y \leq 0$"] },
    { q: "What is $20\%$ of 50?", opts: ["5", "**10**", "15", "20"] },
    { q: "The value of $\log_2(64)$ is:", opts: ["5", "**6**", "7", "8"] },
    { q: "A triangle with sides 3, 4, 5 is:", opts: ["Isosceles", "**Right**", "Equilateral", "Obtuse"] },
    { q: "What is $\int \frac{1}{x} dx$?", opts: ["$1/x^2$", "$x$", "**$\ln|x| + C$**", "$e^x$"] },
    { q: "The determinant of $\begin{pmatrix} 2 & 1 \\ 4 & 3 \end{pmatrix}$ is:", opts: ["10", "5", "**2**", "1"] },
    { q: "Find $x$ if $2x - 8 = 0$.", opts: ["2", "**4**", "6", "8"] },
    { q: "The sum of $1/3 + 1/6$ is:", opts: ["2/9", "1/9", "**1/2**", "1/18"] },
    { q: "What is the surface area of a sphere with $r=1$?", opts: ["$\pi$", "$2\pi$", "**$4\pi$**", "$4/3\pi$"] },
    { q: "The limit of $1/x$ as $x \to \infty$ is:", opts: ["1", "$\infty$", "**0**", "-1"] },
    { q: "If $A = \{1, 2, 3\}$, how many subsets does it have?", opts: ["3", "6", "**8**", "9"] },
    { q: "What is $3^0 + 3^1 + 3^2$?", opts: ["12", "**13**", "9", "10"] },
    { q: "The slope of $y = 3x - 4$ is:", opts: ["-4", "4", "**3**", "1"] },
    { q: "What is $\sqrt{625}$?", opts: ["15", "20", "**25**", "35"] },
    { q: "The perimeter of a circle with $r=7$ is ($\pi \approx 22/7$):", opts: ["22", "**44**", "154", "88"] },
    { q: "Find the mean of 10, 20, 30, 40.", opts: ["20", "**25**", "30", "35"] },
    { q: "The derivative of $\sin(x)$ is:", opts: ["$-\cos(x)$", "$\sin(x)$", "**$\cos(x)$**", "1"] },
    { q: "What is $2^6$?", opts: ["32", "**64**", "128", "16"] },
    { q: "The value of $|-5| + |5|$ is:", opts: ["0", "-10", "**10**", "25"] },
    { q: "Solve $x/2 = 10$.", opts: ["5", "**20**", "12", "8"] },
    { q: "The GCD of 15 and 25 is:", opts: ["3", "**5**", "15", "75"] },
    { q: "What is $1/5$ as a decimal?", opts: ["0.1", "**0.2**", "0.5", "0.25"] },
    { q: "The interior angle of a regular octagon is:", opts: ["$120^\circ$", "**$135^\circ$**", "$144^\circ$", "$108^\circ$"] },
    { q: "What is $\cos(0)$?", opts: ["0", "**1**", "-1", "0.5"] },
    { q: "If $f(x) = x^2$, find $f'(3)$.", opts: ["3", "9", "**6**", "2"] },
    { q: "The distance from (0,0) to (6,8) is:", opts: ["14", "48", "**10**", "100"] },
    { q: "What is $10^3$?", opts: ["30", "100", "**1000**", "10000"] },
    { q: "The volume of a cube with side 5 is:", opts: ["25", "100", "**125**", "150"] },
    { q: "Find $x$: $3x + 1 = 10$.", opts: ["2", "**3**", "4", "9"] },
    { q: "The square root of 400 is:", opts: ["10", "**20**", "30", "40"] },
    { q: "What is $1/2$ of 500?", opts: ["100", "200", "**250**", "300"] },
    { q: "The complement of $30^\circ$ is:", opts: ["$150^\circ$", "$90^\circ$", "**$60^\circ$**", "$120^\circ$"] },
    { q: "The number of sides in a hexagon is:", opts: ["5", "**6**", "7", "8"] },
    { q: "If $x - 10 = 0$, then $x$ is:", opts: ["-10", "0", "**10**", "20"] },
    { q: "What is the product of 9 and 8?", opts: ["17", "64", "**72**", "81"] },
    { q: "The value of $\pi$ is roughly:", opts: ["2.14", "3.00", "**3.14**", "4.14"] },
    { q: "A circle's diameter is 10, what is its radius?", opts: ["20", "10", "**5**", "2.5"] },
    { q: "What is $2^5$?", opts: ["10", "16", "**32**", "64"] },
    { q: "The value of $|-15|$ is:", opts: ["-15", "0", "**15**", "1"] },
    { q: "Solve $4x = 16$.", opts: ["2", "3", "**4**", "8"] },
    { q: "The smallest prime is:", opts: ["1", "**2**", "3", "0"] },
    { q: "What is $25 \times 4$?", opts: ["25", "50", "**100**", "200"] },
    { q: "Area of a rectangle with length 10 and width 5 is:", opts: ["15", "30", "**50**", "100"] }];
QUESTIONS_DB.Common.Maths["2013"] = [{ q: "What is the derivative of $f(x) = x^x$?", opts: ["$x \cdot x^{x-1}$", "$x^x \ln(x)$", "**$x^x(1 + \ln(x))$**", "$x^x(1 - \ln(x))$"] },
    { q: "The value of $\lim_{x \to 0} \frac{e^x - 1}{x}$ is:", opts: ["0", "**1**", "$e$", "$\infty$"] },
    { q: "If $f(x) = \int_0^x \sin(t^2) dt$, then $f'(x)$ is:", opts: ["$\cos(x^2)$", "$2x\sin(x^2)$", "**$\sin(x^2)$**", "$-\cos(x^2)$"] },
    { q: "The eccentricity of the hyperbola $\frac{x^2}{9} - \frac{y^2}{16} = 1$ is:", opts: ["3/5", "4/5", "**5/3**", "5/4"] },
    { q: "What is the argument of the complex number $z = 1 + i\sqrt{3}$?", opts: ["$\pi/6$", "**$\pi/3$**", "$\pi/4$", "$\pi/2$"] },
    { q: "The volume of the solid generated by revolving $y=x$ from $x=0$ to $x=1$ about the x-axis is:", opts: ["$\pi/2$", "**$\pi/3$**", "$\pi$", "$2\pi$"] },
    { q: "If $\vec{u} \times \vec{v} = 0$, then the vectors are:", opts: ["Perpendicular", "**Parallel**", "Unit vectors", "Orthogonal"] },
    { q: "The solution to the differential equation $\frac{dy}{dx} = y$ is:", opts: ["$y = x + C$", "$y = x^2 + C$", "**$y = Ce^x$**", "$y = \ln(x) + C$"] },
    { q: "What is the sum of the series $\sum_{n=0}^{\infty} (\frac{2}{3})^n$?", opts: ["2", "**3**", "1.5", "$\infty$"] },
    { q: "The distance from the origin to the plane $2x + y - 2z = 9$ is:", opts: ["1", "2", "**3**", "9"] },
    { q: "If $A$ is a $3 \times 3$ matrix and $\det(A) = 2$, then $\det(3A)$ is:", opts: ["6", "18", "**54**", "2"] },
    { q: "The derivative of $\arcsin(x)$ is:", opts: ["$1/(1+x^2)$", "$1/\cos(x)$", "**$1/\sqrt{1-x^2}$**", "$-1/\sqrt{1-x^2}$"] },
    { q: "Find the local minimum of $f(x) = x^2 - 4x + 5$.", opts: ["(0, 5)", "(4, 5)", "**(2, 1)**", "(-2, 17)"] },
    { q: "The probability of getting a sum of 7 when rolling two dice is:", opts: ["1/12", "**1/6**", "1/36", "5/36"] },
    { q: "What is the value of $\log_2( \log_2(16) )$?", opts: ["1", "**2**", "3", "4"] },
    { q: "The focus of the ellipse $\frac{x^2}{25} + \frac{y^2}{16} = 1$ is at:", opts: ["(0, \pm 3)", "**(\pm 3, 0)**", "(\pm 4, 0)", "(0, \pm 5)"] },
    { q: "If $\cos(2\theta) = 0$, what is a possible value of $\sin^2(\theta)$?", opts: ["0", "1", "**1/2**", "1/4"] },
    { q: "The area bounded by $y = x^2$ and $y = x$ is:", opts: ["1/2", "1/3", "**1/6**", "1/4"] },
    { q: "What is the period of $f(x) = \tan(3x)$?", opts: ["$2\pi/3$", "$\pi$", "**$\pi/3$**", "$3\pi$"] },
    { q: "The inverse of the function $f(x) = 2^x$ is:", opts: ["$x^2$", "$1/2^x$", "**$\log_2(x)$**", "$\ln(x)/2$"] },
    { q: "Which of the following is an even function?", opts: ["$\sin(x)$", "$x^3$", "**$\cos(x)$**", "$e^x$"] },
    { q: "The derivative of $f(x) = |x|$ at $x=0$ is:", opts: ["1", "-1", "0", "**Undefined**"] },
    { q: "Find the work done by a force $\vec{F} = (3, 4)$ moving an object by $\vec{d} = (2, 1)$.", opts: ["7", "5", "**10**", "11"] },
    { q: "The value of $\binom{6}{3}$ is:", opts: ["18", "15", "**20**", "120"] },
    { q: "The horizontal asymptote of $f(x) = \frac{3x^2 - 1}{x^2 + 4}$ is:", opts: ["$y=0$", "**$y=3$**", "$y=1/3$", "None"] },
    { q: "What is the conjugate of $-2 - 5i$?", opts: ["$2 + 5i$", "$2 - 5i$", "**$-2 + 5i$**", "$-5 - 2i$"] },
    { q: "If $f(x) = \sin(x)$, then $f^{(4)}(x)$ (fourth derivative) is:", opts: ["$\cos(x)$", "$-\sin(x)$", "**$\sin(x)$**", "$-\cos(x)$"] },
    { q: "The radius of the sphere $x^2 + y^2 + z^2 = 49$ is:", opts: ["49", "14", "**7**", "3.5"] },
    { q: "What is $\sec^2(x) - \tan^2(x)$?", opts: ["0", "**1**", "$\sec(x)$", "$\cos(x)$"] },
    { q: "The mean of the data set {2, 4, 8, 16} is:", opts: ["7", "**7.5**", "8", "10"] },
    { q: "Find $x$ if $\det \begin{pmatrix} x & 1 \\ 4 & x \end{pmatrix} = 0$.", opts: ["1", "4", "**\pm 2**", "0"] },
    { q: "The integral $\int \frac{1}{x^2 + 1} dx$ is:", opts: ["$\ln(x^2+1)$", "**$\arctan(x) + C$**", "$-1/x$", "$\arcsin(x)$"] },
    { q: "What is the sum of interior angles of a pentagon?", opts: ["$360^\circ$", "**$540^\circ$**", "$720^\circ$", "$180^\circ$"] },
    { q: "If $P(A) = 0.6$, what is $P(A')$?", opts: ["0", "**0.4**", "1", "0.6"] },
    { q: "The slope of the normal line to $y = x^2$ at (1, 1) is:", opts: ["2", "1", "**-1/2**", "-1"] },
    { q: "What is the value of $e^{\ln(5)}$?", opts: ["0", "1", "**5**", "$e^5$"] },
    { q: "The distance between (1, 2, 3) and (1, 2, 0) is:", opts: ["0", "1", "**3**", "6"] },
    { q: "Simplify $i^{2013}$.", opts: ["1", "-1", "**$i$**", "$-i$"] },
    { q: "The area of a triangle with vertices (0,0), (4,0), and (0,3) is:", opts: ["12", "7", "**6**", "5"] },
    { q: "If $\vec{a} \cdot \vec{b} = |\vec{a}||\vec{b}|$, the angle between them is:", opts: ["$90^\circ$", "**$0^\circ$**", "$180^\circ$", "$45^\circ$"] },
    { q: "What is the third derivative of $x^3 + x^2$?", opts: ["$3x^2+2x$", "$6x+2$", "**6**", "0"] },
    { q: "The range of $f(x) = \cos^{-1}(x)$ is:", opts: ["$[-\pi/2, \pi/2]$", "**$[0, \pi]$**", "All reals", "$[-1, 1]$"] },
    { q: "Find the midpoint of (2, -4) and (8, 10).", opts: ["(5, 6)", "**(5, 3)**", "(10, 6)", "(3, 5)"] },
    { q: "What is $\log_{10}(1)$?", opts: ["1", "10", "**0**", "Undefined"] },
    { q: "The volume of a cylinder with $r=2, h=5$ is:", opts: ["$10\pi$", "**$20\pi$**", "$25\pi$", "$50\pi$"] },
    { q: "If $y = \sin(x^2)$, then $dy/dx$ is:", opts: ["$\cos(x^2)$", "**$2x\cos(x^2)$**", "$2\sin(x)$", "$x^2\cos(x)$"] },
    { q: "The sum of the first 100 natural numbers is:", opts: ["5000", "**5050**", "5100", "4950"] },
    { q: "What is the square root of 0.04?", opts: ["0.02", "**0.2**", "0.4", "0.002"] },
    { q: "A set with 4 elements has how many subsets?", opts: ["4", "8", "**16**", "32"] },
    { q: "The derivative of $5^x$ is:", opts: ["$x5^{x-1}$", "$5^x$", "**$5^x \ln(5)$**", "$5^x / \ln(5)$"] },
    { q: "Find the mode of {1, 1, 2, 2, 3, 3, 3}.", opts: ["1", "2", "**3**", "None"] },
    { q: "What is $\tan(\pi/4)$?", opts: ["0", "**1**", "$\sqrt{3}$", "Undefined"] },
    { q: "The identity for multiplication is:", opts: ["0", "**1**", "-1", "$x$"] },
    { q: "If $x^2 + y^2 = 9$, the area is:", opts: ["$3\pi$", "$6\pi$", "**$9\pi$**", "$81\pi$"] },
    { q: "The value of $|-3| \times |2|$ is:", opts: ["-6", "1", "**6**", "5"] },
    { q: "The derivative of $\ln(2x)$ is:", opts: ["$2/x$", "$1/2x$", "**$1/x$**", "2"] },
    { q: "What is $25\%$ of 80?", opts: ["25", "**20**", "10", "40"] },
    { q: "The sum of angles in a hexagon is:", opts: ["$360^\circ$", "$540^\circ$", "**$720^\circ$**", "$900^\circ$"] },
    { q: "If $x/3 = 9$, then $x$ is:", opts: ["3", "6", "**27**", "12"] },
    { q: "What is the GCD of 8 and 12?", opts: ["2", "**4**", "8", "24"] },
    { q: "The side of a square with area 121 is:", opts: ["10", "**11**", "12", "13"] },
    { q: "What is $0 \times \pi$?", opts: ["$\pi$", "3.14", "**0**", "1"] },
    { q: "Find the median of 5, 2, 9, 1, 7.", opts: ["9", "2", "**5**", "1"] },
    { q: "The value of $\cos(\pi)$ is:", opts: ["0", "1", "**-1**", "0.5"] },
    { q: "What is $\sqrt{169}$?", opts: ["11", "12", "**13**", "14"] },
    { q: "The slope of $y = -2x + 1$ is:", opts: ["1", "2", "**-2**", "0"] },
    { q: "A polygon with 10 sides is a:", opts: ["Octagon", "Nonagon", "**Decagon**", "Dodecagon"] },
    { q: "The value of $2^0$ is:", opts: ["0", "**1**", "2", "Undefined"] },
    { q: "What is $1/2 + 1/3$?", opts: ["2/5", "1/5", "**5/6**", "1/6"] },
    { q: "If $f(x) = 10$, $f'(x)$ is:", opts: ["10", "1", "**0**", "$x$"] },
    { q: "The circumference of a circle with $d=10$ is:", opts: ["$5\pi$", "**$10\pi$**", "$20\pi$", "$100\pi$"] },
    { q: "What is $10^2$?", opts: ["20", "**100**", "1000", "10"] },
    { q: "The supplement of $110^\circ$ is:", opts: ["$20^\circ$", "**$70^\circ$**", "$90^\circ$", "$180^\circ$"] },
    { q: "Find $x$ if $x+7 = 20$.", opts: ["10", "**13**", "27", "7"] },
    { q: "What is the product of 7 and 9?", opts: ["16", "56", "**63**", "72"] },
    { q: "The value of $|-25|$ is:", opts: ["-25", "0", "**25**", "1"] },
    { q: "Solve $5x = 25$.", opts: ["1", "**5**", "10", "20"] },
    { q: "The smallest prime number is:", opts: ["1", "**2**", "3", "0"] },
    { q: "What is $12 \times 12$?", opts: ["124", "**144**", "154", "164"] },
    { q: "Area of a triangle with $b=10, h=4$ is:", opts: ["40", "**20**", "14", "10"] },
    { q: "What is $1/4$ as a decimal?", opts: ["0.4", "0.5", "**0.25**", "0.1"] },
    { q: "The square of 15 is:", opts: ["125", "200", "**225**", "250"] },
    { q: "If $y = x^4$, then $y'$ is:", opts: ["$4x$", "$x^3$", "**$4x^3$**", "$3x^4$"] },
    { q: "A right angle is:", opts: ["$45^\circ$", "**$90^\circ$**", "$180^\circ$", "$360^\circ$"] },
    { q: "The number of sides in a quadrilateral is:", opts: ["3", "**4**", "5", "6"] },
    { q: "If $x - 5 = 5$, then $x$ is:", opts: ["0", "5", "**10**", "25"] },
    { q: "What is the product of 6 and 7?", opts: ["13", "36", "**42**", "49"] },
    { q: "The value of $\pi$ is approximately:", opts: ["2.14", "**3.14**", "3.16", "3.18"] },
    { q: "A circle's radius is 4, what is its diameter?", opts: ["2", "4", "**8**", "16"] },
    { q: "What is $2^4$?", opts: ["8", "12", "**16**", "32"] },
    { q: "The value of $|-10|$ is:", opts: ["-10", "0", "**10**", "1"] },
    { q: "Solve $3x = 12$.", opts: ["2", "3", "**4**", "9"] },
    { q: "The smallest odd prime is:", opts: ["1", "2", "**3**", "5"] },
    { q: "What is $20 \times 5$?", opts: ["20", "25", "**100**", "120"] },
    { q: "Area of a square with side 6 is:", opts: ["12", "24", "**36**", "48"] },
    { q: "What is $\sin(0)$?", opts: ["1", "**0**", "-1", "0.5"] },
    { q: "If $x + x = 10$, $x$ is:", opts: ["2", "**5**", "10", "20"] },
    { q: "The value of $3^2$ is:", opts: ["6", "**9**", "12", "27"] },
    { q: "What is $100 \div 5$?", opts: ["10", "**20**", "25", "50"] },
    { q: "The perimeter of a square with side 4 is:", opts: ["8", "12", "**16**", "20"] }];
QUESTIONS_DB.Common.Maths["2014"] = [{ q: "If $f(x) = \frac{e^x}{x}$, then $f'(1)$ is:", opts: ["0", "$e$", "**0**", "1"] },
    { q: "The limit $\lim_{x \to 0} \frac{1 - \cos(x)}{x^2}$ is:", opts: ["0", "1", "**1/2**", "Undefined"] },
    { q: "Find the area of the region bounded by $y = \sqrt{x}$ and $y = x^2$.", opts: ["1/2", "**1/3**", "1/4", "1/6"] },
    { q: "The value of $\int_0^1 \frac{1}{1+x^2} dx$ is:", opts: ["$\pi/2$", "**$\pi/4$**", "1", "0"] },
    { q: "If $z = i^{100} + i^{101}$, then $z$ is:", opts: ["$1-i$", "**$1+i$**", "$i$", "0"] },
    { q: "The eccentricity of the ellipse $9x^2 + 25y^2 = 225$ is:", opts: ["3/5", "**4/5**", "4/3", "5/4"] },
    { q: "The direction cosines of the vector $\vec{v} = (1, 1, 0)$ are:", opts: ["(1,1,0)", "**(1/\sqrt{2}, 1/\sqrt{2}, 0)**", "(1/2, 1/2, 0)", "(0,0,1)"] },
    { q: "What is the sum of the series $\sum_{n=1}^{\infty} \frac{1}{n(n+1)}$?", opts: ["0", "1/2", "**1**", "$\infty$"] },
    { q: "The derivative of $f(x) = \ln(\sin x)$ is:", opts: ["$\tan x$", "**$\cot x$**", "$1/\sin x$", "$\cos x$"] },
    { q: "Find the distance from (1,1,1) to the origin.", opts: ["1", "2", "**$\sqrt{3}$**", "3"] },
    { q: "If $A^2 = I$, then $A^{-1}$ is:", opts: ["$I$", "$0$", "**$A$**", "$A^2$"] },
    { q: "The solution to $x^2 + x - 6 < 0$ is:", opts: ["$x < -3$", "$x > 2$", "**-3 < x < 2**", "$x < 2$"] },
    { q: "What is the value of $\cos(75^\circ)$?", opts: ["$\frac{\sqrt{6}-\sqrt{2}}{4}$", "**$\frac{\sqrt{6}-\sqrt{2}}{4}$**", "$\frac{\sqrt{6}+\sqrt{2}}{4}$", "1/2"] },
    { q: "The slope of $x^2 + y^2 = 25$ at (3, 4) is:", opts: ["3/4", "4/3", "**-3/4**", "-4/3"] },
    { q: "The volume of a sphere with $r=3$ is:", opts: ["$12\pi$", "$27\pi$", "**$36\pi$**", "$108\pi$"] },
    { q: "If $\log_b a = c$, then:", opts: ["$a^b=c$", "$c^b=a$", "**$b^c=a$**", "$b^a=c$"] },
    { q: "The derivative of $f(x) = \arctan(2x)$ is:", opts: ["$\frac{1}{1+4x^2}$", "**$\frac{2}{1+4x^2}$**", "$\frac{2}{1+x^2}$", "$\frac{1}{1+x^2}$"] },
    { q: "Find the mean of {1, 2, 3, 4, 5, 6, 7}.", opts: ["3", "**4**", "5", "3.5"] },
    { q: "The number of ways to pick 2 students from 10 is:", opts: ["20", "90", "**45**", "100"] },
    { q: "If $\sin \theta = -1$, then $\theta$ could be:", opts: ["$90^\circ$", "$180^\circ$", "**$270^\circ$**", "$0^\circ$"] },
    { q: "The integral $\int e^{3x} dx$ is:", opts: ["$3e^{3x} + C$", "**$\frac{1}{3}e^{3x} + C$**", "$e^{3x} + C$", "$e^{x} + C$"] },
    { q: "What is the conjugate of $7i - 3$?", opts: ["$7i + 3$", "$-7i + 3$", "**$-3 - 7i$**", "$3 - 7i$"] },
    { q: "The focus of $y^2 = -8x$ is:", opts: ["(2,0)", "(-2,0)", "**(-2,0)**", "(0,-2)"] },
    { q: "What is the value of $\binom{7}{0}$?", opts: ["0", "**1**", "7", "Inf"] },
    { q: "The distance between (2,3) and (5,7) is:", opts: ["3", "4", "**5**", "7"] },
    { q: "If $f(x) = 3x - 2$, then $f^{-1}(x)$ is:", opts: ["$\frac{x-2}{3}$", "**$\frac{x+2}{3}$**", "$2x+3$", "$\frac{1}{3x-2}$"] },
    { q: "The derivative of $\cos^2 x$ is:", opts: ["$2\cos x$", "$-2\sin x$", "**$-2\sin x \cos x$**", "$\sin^2 x$"] },
    { q: "What is $\log_5 125$?", opts: ["2", "**3**", "5", "25"] },
    { q: "The area of a circle with $d=4$ is:", opts: ["$16\pi$", "$8\pi$", "**$4\pi$**", "$2\pi$"] },
    { q: "Find the median of {10, 2, 38, 23, 11}.", opts: ["38", "10", "**11**", "23"] },
    { q: "The value of $i^{402}$ is:", opts: ["1", "-1", "**-1**", "$i$"] },
    { q: "If $x + y = 5$ and $x - y = 1$, then $x$ is:", opts: ["2", "**3**", "4", "5"] },
    { q: "The slope of a vertical line is:", opts: ["0", "1", "-1", "**Undefined**"] },
    { q: "What is $\sin(30^\circ) + \cos(60^\circ)$?", opts: ["0", "1/2", "**1**", "$\sqrt{3}$"] },
    { q: "The derivative of $x^3 - 5x + 2$ is:", opts: ["$3x^2$", "$3x^2+5$", "**$3x^2-5$**", "$x^2-5$"] },
    { q: "What is the square root of 289?", opts: ["13", "15", "**17**", "19"] },
    { q: "The range of $f(x) = x^2 + 1$ is:", opts: ["All reals", "$y \geq 0$", "**$y \geq 1$**", "$y > 1$"] },
    { q: "How many sides does a nonagon have?", opts: ["7", "8", "**9**", "10"] },
    { q: "What is $2^3 \times 2^4$?", opts: ["$2^{12}$", "$4^7$", "**$2^7$**", "128"] },
    { q: "The GCD of 18 and 24 is:", opts: ["2", "3", "**6**", "12"] },
    { q: "If $2x = 10$, then $x^2$ is:", opts: ["5", "10", "**25**", "100"] },
    { q: "The area of a triangle with $b=12, h=5$ is:", opts: ["60", "**30**", "15", "25"] },
    { q: "What is the value of $\pi$ to 2 decimal places?", opts: ["3.12", "**3.14**", "3.16", "3.18"] },
    { q: "The mode of {5, 2, 5, 3, 5, 4} is:", opts: ["2", "3", "4", "**5**"] },
    { q: "What is $1/8$ as a decimal?", opts: ["0.12", "**0.125**", "0.25", "0.8"] },
    { q: "The sum of angles in a triangle is:", opts: ["$90^\circ$", "**$180^\circ$**", "$270^\circ$", "$360^\circ$"] },
    { q: "The derivative of a linear function $mx+c$ is:", opts: ["$x$", "$c$", "**$m$**", "0"] },
    { q: "What is $10\%$ of 500?", opts: ["5", "**50**", "100", "250"] },
    { q: "The value of $|-9| - |4|$ is:", opts: ["-13", "-5", "**5**", "13"] },
    { q: "Solve $x/3 = 12$.", opts: ["4", "9", "**36**", "15"] },
    { q: "The additive identity is:", opts: ["1", "**0**", "-1", "None"] },
    { q: "If $f(x) = x^2$, then $f(3)$ is:", opts: ["6", "**9**", "12", "27"] },
    { q: "The smallest prime number is:", opts: ["1", "**2**", "3", "5"] },
    { q: "What is $15 \times 4$?", opts: ["45", "50", "**60**", "75"] },
    { q: "The square of 12 is:", opts: ["122", "**144**", "164", "100"] },
    { q: "The value of $\sin(90^\circ)$ is:", opts: ["0", "**1**", "-1", "0.5"] },
    { q: "What is the product of 8 and 7?", opts: ["15", "49", "**56**", "63"] },
    { q: "Find $x$ if $x - 8 = 12$.", opts: ["4", "10", "**20**", "96"] },
    { q: "The radius of a circle with $C=2\pi$ is:", opts: ["2", "**1**", "0.5", "$\pi$"] },
    { q: "What is $10^4$?", opts: ["100", "1000", "**10000**", "40"] },
    { q: "The value of $0!$ is:", opts: ["0", "**1**", "10", "Inf"] },
    { q: "A polygon with 4 equal sides and angles is a:", opts: ["Rectangle", "Rhombus", "**Square**", "Parallelogram"] },
    { q: "What is $1/2$ of 150?", opts: ["50", "60", "**75**", "100"] },
    { q: "The supplement of $80^\circ$ is:", opts: ["$10^\circ$", "$20^\circ$", "**$100^\circ$**", "$180^\circ$"] },
    { q: "Find the mean of 2, 4, 6.", opts: ["3", "**4**", "5", "6"] },
    { q: "What is $3^3$?", opts: ["9", "**27**", "81", "12"] },
    { q: "The absolute value of -100 is:", opts: ["-100", "0", "**100**", "1"] },
    { q: "Solve $2x + 4 = 10$.", opts: ["2", "**3**", "4", "7"] },
    { q: "The number of sides in a heptagon is:", opts: ["5", "6", "**7**", "8"] },
    { q: "What is $25 \times 4$?", opts: ["25", "50", "**100**", "125"] },
    { q: "The square root of 1 is:", opts: ["0", "**1**", "2", "-1"] },
    { q: "What is $1/5$ of 100?", opts: ["10", "**20**", "25", "50"] },
    { q: "The value of $\cos(0)$ is:", opts: ["0", "**1**", "-1", "0.5"] },
    { q: "Find $x$ if $3x = 15$.", opts: ["3", "**5**", "15", "45"] },
    { q: "The perimeter of a square with $s=5$ is:", opts: ["10", "15", "**20**", "25"] },
    { q: "What is $9 \times 6$?", opts: ["45", "**54**", "63", "72"] },
    { q: "The value of $|-12|$ is:", opts: ["-12", "0", "**12**", "1"] },
    { q: "Solve $x + 5 = 15$.", opts: ["5", "**10**", "15", "20"] },
    { q: "The smallest odd prime is:", opts: ["1", "2", "**3**", "5"] },
    { q: "What is $10 \times 10$?", opts: ["20", "**100**", "1000", "1"] },
    { q: "Area of a rectangle with $l=8, w=3$ is:", opts: ["11", "22", "**24**", "30"] },
    { q: "What is $1/10$ as a decimal?", opts: ["0.01", "**0.1**", "1.0", "0.11"] },
    { q: "The square of 10 is:", opts: ["20", "50", "**100**", "1000"] },
    { q: "The derivative of $\sin x$ is:", opts: ["$-\cos x$", "$\sin x$", "**$\cos x$**", "1"] },
    { q: "A right angle is $x$ degrees:", opts: ["45", "60", "**90**", "180"] },
    { q: "Number of sides in a pentagon:", opts: ["4", "**5**", "6", "7"] },
    { q: "If $x - 2 = 8$, $x$ is:", opts: ["6", "**10**", "16", "4"] },
    { q: "What is $7 \times 6$?", opts: ["36", "**42**", "48", "49"] },
    { q: "Approximate value of $\pi$:", opts: ["3.12", "**3.14**", "3.16", "3.18"] },
    { q: "Radius of circle with $d=12$:", opts: ["24", "12", "**6**", "3"] },
    { q: "What is $2^5$?", opts: ["10", "16", "**32**", "64"] },
    { q: "Absolute value of -20:", opts: ["-20", "0", "**20**", "1"] },
    { q: "Solve $5x = 20$:", opts: ["2", "3", "**4**", "5"] },
    { q: "Smallest prime number:", opts: ["1", "**2**", "3", "4"] },
    { q: "What is $12 \times 3$?", opts: ["24", "30", "**36**", "42"] },
    { q: "Area of square with side 4:", opts: ["8", "12", "**16**", "20"] },
    { q: "What is $\sin(0)$?", opts: ["1", "**0**", "-1", "0.5"] },
    { q: "If $x + x = 20$, $x$ is:", opts: ["5", "**10**", "20", "40"] },
    { q: "Value of $4^2$:", opts: ["8", "**16**", "32", "64"] },
    { q: "What is $100 \div 2$?", opts: ["25", "**50**", "75", "10"] }];
QUESTIONS_DB.Common.Maths["2015"] = [{ q: "What is the derivative of $f(x) = \ln(\cos x)$?", opts: ["$\tan x$", "**$-\tan x$**", "$\cot x$", "$-\cot x$"] },
    { q: "The value of $\lim_{x \to 0} \frac{\sin(5x)}{3x}$ is:", opts: ["1", "0", "**5/3**", "3/5"] },
    { q: "If $\int_1^k 2x dx = 8$ and $k > 0$, then $k$ is:", opts: ["2", "**3**", "4", "5"] },
    { q: "The focus of the parabola $x^2 = -16y$ is:", opts: ["(4, 0)", "(-4, 0)", "(0, 4)", "**(0, -4)**"] },
    { q: "What is the modulus of $z = 1 - i\sqrt{3}$?", opts: ["1", "**2**", "3", "4"] },
    { q: "The angle between vectors $\vec{a} = (1, 1)$ and $\vec{b} = (1, 0)$ is:", opts: ["$30^\circ$", "**$45^\circ$**", "$60^\circ$", "$90^\circ$"] },
    { q: "The slope of the line $2x + 3y = 6$ is:", opts: ["2/3", "**-2/3**", "3/2", "-3/2"] },
    { q: "If $3^{x+1} = 81$, then $x$ is:", opts: ["2", "**3**", "4", "5"] },
    { q: "What is the area of a circle with circumference $12\pi$?", opts: ["$12\pi$", "$24\pi$", "**$36\pi$**", "$144\pi$"] },
    { q: "The derivative of $f(x) = e^{x^2}$ is:", opts: ["$e^{2x}$", "$e^{x^2}$", "**$2xe^{x^2}$**", "$2e^{x^2}$"] },
    { q: "Find the median of {5, 12, 3, 10, 7}.", opts: ["3", "**7**", "10", "12"] },
    { q: "The sum of an infinite geometric series with $a=1, r=1/3$ is:", opts: ["1.2", "**1.5**", "2", "3"] },
    { q: "What is the value of $\binom{8}{2}$?", opts: ["16", "**28**", "56", "64"] },
    { q: "The distance between (1, 2) and (4, 6) is:", opts: ["3", "4", "**5**", "7"] },
    { q: "If $\log_2 x + \log_2 3 = 3$, then $x$ is:", opts: ["5", "1", "**8/3**", "2"] },
    { q: "The derivative of $\sec x$ is:", opts: ["$\csc x$", "$\sec^2 x$", "**$\sec x \tan x$**", "$\tan x$"] },
    { q: "What is the volume of a cylinder with $r=3, h=10$?", opts: ["$30\pi$", "$60\pi$", "**$90\pi$**", "$100\pi$"] },
    { q: "The range of $f(x) = 3\sin x$ is:", opts: ["$[-1, 1]$", "**$[-3, 3]$**", "$[0, 3]$", "All reals"] },
    { q: "Find the mean of {2, 4, 6, 8, 10}.", opts: ["5", "**6**", "7", "8"] },
    { q: "What is $i^{14}$?", opts: ["$i$", "-$i$", "1", "**-1**"] },
    { q: "The equation of a circle with center (0,0) and radius 5 is:", opts: ["$x+y=25$", "$x^2+y^2=5$", "**$x^2+y^2=25$**", "$x^2-y^2=25$"] },
    { q: "Solve for $x$: $2x - 10 = x + 5$.", opts: ["5", "10", "**15**", "20"] },
    { q: "The derivative of $\arctan x$ is:", opts: ["$1/\sqrt{1-x^2}$", "**$1/(1+x^2)$**", "$1/\cos x$", "$\sec^2 x$"] },
    { q: "What is $P(5, 2)$?", opts: ["10", "**20**", "25", "60"] },
    { q: "The sum of interior angles of a decagon is:", opts: ["$360^\circ$", "$1080^\circ$", "**$1440^\circ$**", "$1800^\circ$"] },
    { q: "If $f(x) = x^3 - 1$, then $f^{-1}(7)$ is:", opts: ["1", "**2**", "3", "8"] },
    { q: "The horizontal asymptote of $y = \frac{2x+1}{x-3}$ is:", opts: ["$y=3$", "$x=3$", "**$y=2$**", "None"] },
    { q: "What is $\sin(210^\circ)$?", opts: ["1/2", "**-1/2**", "$\sqrt{3}/2$", "$-\sqrt{3}/2$"] },
    { q: "The product of $(1+i)(1-i)$ is:", opts: ["0", "1", "**2**", "1+i"] },
    { q: "Find the area of a square with diagonal $4\sqrt{2}$.", opts: ["8", "**16**", "32", "64"] },
    { q: "The derivative of $1/x^2$ is:", opts: ["$2/x^3$", "$-1/x$", "**$-2/x^3$**", "$1/x$"] },
    { q: "If $\vec{a} = (2, -1)$ and $\vec{b} = (3, 4)$, then $\vec{a} \cdot \vec{b}$ is:", opts: ["10", "6", "**2**", "-2"] },
    { q: "What is $\log_{10} 0.1$?", opts: ["0", "1", "**-1**", "-2"] },
    { q: "The surface area of a cube with side 3 is:", opts: ["9", "27", "**54**", "81"] },
    { q: "Solve $x^2 - 5x + 6 = 0$.", opts: ["{1, 6}", "**{2, 3}**", "{-2, -3}", "{5, 0}"] },
    { q: "The mode of {2, 3, 3, 4, 4, 4, 5} is:", opts: ["2", "3", "**4**", "5"] },
    { q: "What is $\sqrt{441}$?", opts: ["19", "20", "**21**", "22"] },
    { q: "The derivative of $\ln(x^2)$ is:", opts: ["$1/x^2$", "$2x$", "**$2/x$**", "$x/2$"] },
    { q: "If $A = \{1, 2\}$, the power set $P(A)$ size is:", opts: ["2", "**4**", "8", "1"] },
    { q: "What is $\tan(60^\circ)$?", opts: ["1", "1/2", "**$\sqrt{3}$**", "$\sqrt{3}/3$"] },
    { q: "The integral $\int \cos x dx$ is:", opts: ["$-\sin x + C$", "**$\sin x + C$**", "$\cos x + C$", "$x\sin x$"] },
    { q: "Find $x$ if $x/5 + 2 = 10$.", opts: ["8", "30", "**40**", "50"] },
    { q: "The y-intercept of $y = 4x^2 - 3x + 5$ is:", opts: ["4", "-3", "**5**", "0"] },
    { q: "What is $15\%$ of 200?", opts: ["15", "25", "**30**", "45"] },
    { q: "The smallest prime number is:", opts: ["1", "**2**", "3", "0"] },
    { q: "A triangle with sides 7, 24, 25 is:", opts: ["Isosceles", "**Right**", "Equilateral", "Acute"] },
    { q: "What is $4!$?", opts: ["12", "16", "**24**", "48"] },
    { q: "The value of $\cos(90^\circ)$ is:", opts: ["1", "-1", "**0**", "0.5"] },
    { q: "Find the slope of a line through (1,2) and (3,10).", opts: ["2", "**4**", "6", "8"] },
    { q: "The volume of a sphere with $r=1$ is:", opts: ["$\pi$", "$2\pi$", "**$4/3\pi$**", "$4\pi$"] },
    { q: "Solve $e^x = e^2$.", opts: ["1", "**2**", "0", "$e$"] },
    { q: "The GCD of 12 and 20 is:", opts: ["2", "**4**", "6", "12"] },
    { q: "What is $1/3$ as a percentage?", opts: ["30%", "**33.3%**", "13%", "3%"] },
    { q: "The square of 14 is:", opts: ["186", "**196**", "206", "144"] },
    { q: "If $x + 2x + 3x = 60$, then $x$ is:", opts: ["5", "**10**", "15", "20"] },
    { q: "The derivative of $7x$ is:", opts: ["$x$", "0", "**7**", "$7x$"] },
    { q: "What is $|-50|$?", opts: ["-50", "0", "**50**", "1"] },
    { q: "The area of a triangle with $b=8, h=3$ is:", opts: ["24", "**12**", "11", "10"] },
    { q: "The sum of $0.2 + 0.02$ is:", opts: ["0.4", "**0.22**", "0.202", "2.2"] },
    { q: "What is $\sin(\pi)$?", opts: ["1", "-1", "**0**", "0.5"] },
    { q: "If $y = 10$, $dy/dx$ is:", opts: ["10", "1", "**0**", "$x$"] },
    { q: "The number of sides in an octagon is:", opts: ["6", "7", "**8**", "10"] },
    { q: "What is $10^5$?", opts: ["1000", "10000", "**100000**", "50"] },
    { q: "The value of $2^0$ is:", opts: ["0", "**1**", "2", "Inf"] },
    { q: "Find $x$ if $x - 5 = -5$.", opts: ["10", "5", "**0**", "-10"] },
    { q: "What is $8 \times 9$?", opts: ["64", "**72**", "81", "56"] },
    { q: "The perimeter of a square with $s=10$ is:", opts: ["20", "**40**", "100", "80"] },
    { q: "What is $1/2$ of 1000?", opts: ["250", "**500**", "750", "100"] },
    { q: "The square root of 64 is:", opts: ["6", "7", "**8**", "9"] },
    { q: "The supplement of $150^\circ$ is:", opts: ["$10^\circ$", "$20^\circ$", "**$30^\circ$**", "$180^\circ$"] },
    { q: "What is $25 \times 3$?", opts: ["50", "65", "**75**", "100"] },
    { q: "The value of $|-5| + |5|$ is:", opts: ["0", "-10", "**10**", "25"] },
    { q: "Solve $4x = 20$.", opts: ["2", "4", "**5**", "10"] },
    { q: "The smallest odd prime is:", opts: ["1", "2", "**3**", "5"] },
    { q: "What is $11 \times 11$?", opts: ["111", "**121**", "131", "141"] },
    { q: "Area of a rectangle with $l=6, w=4$ is:", opts: ["10", "20", "**24**", "30"] },
    { q: "What is $1/4$ as a decimal?", opts: ["0.4", "**0.25**", "0.5", "0.1"] },
    { q: "The square of 9 is:", opts: ["18", "27", "**81**", "90"] },
    { q: "The derivative of $\cos x$ is:", opts: ["$\sin x$", "**$-\sin x$**", "$\cos x$", "1"] },
    { q: "A right angle is:", opts: ["$45^\circ$", "**$90^\circ$**", "$180^\circ$", "$360^\circ$"] },
    { q: "Number of sides in a hexagon:", opts: ["5", "**6**", "7", "8"] },
    { q: "If $x - 3 = 7$, $x$ is:", opts: ["4", "**10**", "21", "3"] },
    { q: "What is $6 \times 8$?", opts: ["42", "**48**", "54", "56"] },
    { q: "Approximate value of $\pi$:", opts: ["2.14", "**3.14**", "3.16", "3.18"] },
    { q: "Radius of circle with $d=20$:", opts: ["40", "20", "**10**", "5"] },
    { q: "What is $2^6$?", opts: ["32", "**64**", "128", "16"] },
    { q: "Absolute value of -30:", opts: ["-30", "0", "**30**", "1"] },
    { q: "Solve $5x = 50$:", opts: ["5", "**10**", "15", "20"] },
    { q: "Smallest prime number:", opts: ["1", "**2**", "3", "4"] },
    { q: "What is $15 \times 2$?", opts: ["25", "**30**", "35", "40"] },
    { q: "Area of square with side 5:", opts: ["10", "20", "**25**", "50"] },
    { q: "What is $\sin(0)$?", opts: ["1", "**0**", "-1", "0.5"] },
    { q: "If $x + x = 40$, $x$ is:", opts: ["10", "**20**", "40", "80"] },
    { q: "Value of $5^2$:", opts: ["10", "**25**", "50", "125"] },
    { q: "What is $100 \div 4$?", opts: ["20", "**25**", "50", "10"] },
    { q: "Perimeter of square with side 3:", opts: ["6", "9", "**12**", "15"] },
    { q: "What is $1/10$ of 1000?", opts: ["10", "**100**", "1000", "1"] },
    { q: "The value of $12 - (-5)$ is:", opts: ["7", "12", "**17**", "-17"] },
    { q: "Area of triangle with $b=10, h=6$ is:", opts: ["60", "**30**", "16", "10"] },
    { q: "What is $2^3$?", opts: ["6", "**8**", "9", "12"] }];
QUESTIONS_DB.Common.Maths["2016"] = [{ q: "What is the derivative of $f(x) = \ln(x^2 + 1)$?", opts: ["$2x$", "$\frac{1}{x^2+1}$", "**$\frac{2x}{x^2+1}$**", "$\frac{x}{x^2+1}$"] },
    { q: "The value of $\lim_{x \to 0} \frac{1 - e^x}{x}$ is:", opts: ["0", "1", "**-1**", "$\infty$"] },
    { q: "Find the area bounded by $y = x^3$, the x-axis, and $x = 1$.", opts: ["1/3", "**1/4**", "1/2", "1"] },
    { q: "The modulus of $z = \sqrt{3} + i$ is:", opts: ["1", "**2**", "3", "4"] },
    { q: "If $\int_0^1 (ax + 1) dx = 2$, then $a$ is:", opts: ["1", "**2**", "3", "4"] },
    { q: "The focus of $y^2 = 20x$ is:", opts: ["(0, 5)", "**(5, 0)**", "(-5, 0)", "(0, -5)"] },
    { q: "The slope of the tangent to $y = \sin x$ at $x = 0$ is:", opts: ["0", "**1**", "-1", "0.5"] },
    { q: "What is the sum of the infinite series $1 - 1/2 + 1/4 - 1/8 + \dots$?", opts: ["1/2", "1", "**2/3**", "3/2"] },
    { q: "The dot product of $(1, 2, 3)$ and $(2, -1, 0)$ is:", opts: ["4", "1", "**0**", "-1"] },
    { q: "If $f(x) = e^{3x}$, then $f''(x)$ is:", opts: ["$3e^{3x}$", "$6e^{3x}$", "**$9e^{3x}$**", "$e^{3x}$"] },
    { q: "The center of the circle $x^2 + y^2 - 4x + 2y = 0$ is:", opts: ["(-2, 1)", "**(2, -1)**", "(4, -2)", "(0, 0)"] },
    { q: "What is the value of $\binom{10}{3}$?", opts: ["30", "60", "**120**", "720"] },
    { q: "The probability of rolling a sum of 2 with two dice is:", opts: ["1/6", "1/12", "**1/36**", "1/18"] },
    { q: "If $\log_3 x = -2$, then $x$ is:", opts: ["-6", "1/6", "**1/9**", "9"] },
    { q: "The derivative of $\csc x$ is:", opts: ["$\sec x \tan x$", "$-\csc^2 x$", "**$-\csc x \cot x$**", "$\cot^2 x$"] },
    { q: "The volume of a cone with $r=3, h=3$ is:", opts: ["$3\pi$", "**$9\pi$**", "$27\pi$", "$81\pi$"] },
    { q: "Find the median of {8, 1, 5, 10, 2}.", opts: ["1", "**5**", "8", "10"] },
    { q: "What is $i^{20}$?", opts: ["$i$", "-$i$", "**1**", "-1"] },
    { q: "The range of $f(x) = \arctan x$ is:", opts: ["All reals", "$[0, \pi]$", "**$(-\pi/2, \pi/2)$**", "$[-1, 1]$"] },
    { q: "The derivative of $f(x) = \sqrt{2x}$ is:", opts: ["$\sqrt{2}$", "$\frac{1}{\sqrt{2x}}$", "**$\frac{1}{\sqrt{2x}}$**", "$\frac{2}{\sqrt{2x}}$"] },
    { q: "If $\vec{a} = (3, 4)$, the unit vector in direction $\vec{a}$ is:", opts: ["(3, 4)", "**(3/5, 4/5)**", "(1, 1)", "(0.6, 0.8)"] },
    { q: "The vertical asymptote of $y = \frac{1}{x^2-1}$ is:", opts: ["$x=1$", "$x=-1$", "**$x=\pm 1$**", "None"] },
    { q: "What is $\cos(120^\circ)$?", opts: ["1/2", "**-1/2**", "$\sqrt{3}/2$", "$-\sqrt{3}/2$"] },
    { q: "The integral $\int \frac{1}{x+1} dx$ is:", opts: ["$x$", "$1/(x+1)^2$", "**$\ln|x+1| + C$**", "$e^{x+1}$"] },
    { q: "The number of ways to arrange 4 books on a shelf is:", opts: ["4", "12", "**24**", "16"] },
    { q: "Find $x$ if $2^{2x} = 64$.", opts: ["2", "**3**", "4", "6"] },
    { q: "The eccentricity of a parabola is:", opts: ["0", "**1**", ">1", "<1"] },
    { q: "What is the value of $P(4, 4)$?", opts: ["1", "4", "16", "**24**"] },
    { q: "The derivative of $\tan(x^2)$ is:", opts: ["$\sec^2(x^2)$", "**$2x\sec^2(x^2)$**", "$2x\tan(x^2)$", "$\sec^2(2x)$"] },
    { q: "The sum of roots of $x^2 + 5x + 6 = 0$ is:", opts: ["5", "6", "**-5**", "-6"] },
    { q: "What is $\sin(45^\circ) \cos(45^\circ)$?", opts: ["1", "$\sqrt{2}$", "**1/2**", "1/4"] },
    { q: "The domain of $\ln(x-5)$ is:", opts: ["$x \geq 5$", "**$x > 5$**", "All reals", "$x \neq 5$"] },
    { q: "The product of $(3+2i)$ and $i$ is:", opts: ["$3i+2$", "**$-2+3i$**", "$2+3i$", "$3-2i$"] },
    { q: "Find the mean of the first four even numbers.", opts: ["4", "**5**", "6", "8"] },
    { q: "The distance from (0,0,0) to (2,2,1) is:", opts: ["2", "4", "5", "**3**"] },
    { q: "What is $\log_2(1/8)$?", opts: ["3", "1/3", "**-3**", "-1/3"] },
    { q: "The derivative of $f(x) = \pi$ is:", opts: ["$\pi$", "1", "**0**", "3.14"] },
    { q: "If $y = \cos x$, then $y^{(4)}$ is:", opts: ["$\sin x$", "$-\cos x$", "**$\cos x$**", "$-\sin x$"] },
    { q: "The volume of a sphere with $r=2$ is:", opts: ["$8\pi$", "$16\pi$", "**$32\pi/3$**", "$4\pi/3$"] },
    { q: "Solve $3x - 5 = 10$.", opts: ["3", "4", "**5**", "15"] },
    { q: "The GCD of 100 and 25 is:", opts: ["5", "10", "**25**", "50"] },
    { q: "What is $5\%$ of 1000?", opts: ["5", "**50**", "500", "10"] },
    { q: "The smallest prime number is:", opts: ["1", "**2**", "3", "0"] },
    { q: "A square with side 7 has area:", opts: ["14", "28", "**49**", "70"] },
    { q: "What is $\sqrt{144}$?", opts: ["10", "11", "**12**", "14"] },
    { q: "The mode of {1, 2, 2, 3, 4} is:", opts: ["1", "**2**", "3", "4"] },
    { q: "What is $1/5$ of 200?", opts: ["20", "**40**", "50", "100"] },
    { q: "The supplement of $60^\circ$ is:", opts: ["$30^\circ$", "$90^\circ$", "**$120^\circ$**", "$180^\circ$"] },
    { q: "The number of sides in a dodecagon is:", opts: ["10", "**12**", "14", "20"] },
    { q: "If $x + 10 = 5$, $x$ is:", opts: ["15", "5", "**-5**", "0"] },
    { q: "What is $8 \times 7$?", opts: ["48", "54", "**56**", "64"] },
    { q: "The value of $\pi$ is approximately:", opts: ["3.12", "**3.14**", "3.16", "3.18"] },
    { q: "The radius of a circle with $d=16$ is:", opts: ["32", "16", "**8**", "4"] },
    { q: "What is $2^4$?", opts: ["8", "12", "**16**", "32"] },
    { q: "The absolute value of -15 is:", opts: ["-15", "0", "**15**", "1"] },
    { q: "Solve $4x = 24$.", opts: ["4", "5", "**6**", "12"] },
    { q: "The smallest odd prime is:", opts: ["1", "2", "**3**", "5"] },
    { q: "What is $25 \times 4$?", opts: ["25", "50", "**100**", "200"] },
    { q: "Area of a triangle with $b=6, h=4$ is:", opts: ["24", "**12**", "10", "6"] },
    { q: "What is $1/4$ as a decimal?", opts: ["0.4", "0.5", "**0.25**", "0.1"] },
    { q: "The square of 11 is:", opts: ["111", "**121**", "131", "141"] },
    { q: "The derivative of $e^x$ is:", opts: ["$xe^{x-1}$", "$\ln x$", "**$e^x$**", "1"] },
    { q: "A right angle is:", opts: ["$45^\circ$", "**$90^\circ$**", "$180^\circ$", "$360^\circ$"] },
    { q: "Number of sides in a pentagon:", opts: ["4", "**5**", "6", "7"] },
    { q: "If $x - 2 = 10$, $x$ is:", opts: ["8", "**12**", "20", "5"] },
    { q: "What is $7 \times 9$?", opts: ["56", "**63**", "72", "81"] },
    { q: "Radius of circle with $d=10$:", opts: ["10", "**5**", "2.5", "20"] },
    { q: "What is $3^3$?", opts: ["9", "**27**", "81", "12"] },
    { q: "Absolute value of -50:", opts: ["-50", "0", "**50**", "1"] },
    { q: "Solve $5x = 45$:", opts: ["5", "7", "**9**", "10"] },
    { q: "Smallest prime number:", opts: ["1", "**2**", "3", "4"] },
    { q: "What is $12 \times 2$?", opts: ["14", "20", "**24**", "36"] },
    { q: "Area of square with side 10:", opts: ["20", "40", "**100**", "200"] },
    { q: "What is $\sin(90^\circ)$?", opts: ["0", "**1**", "-1", "0.5"] },
    { q: "If $x + x = 30$, $x$ is:", opts: ["10", "**15**", "30", "60"] },
    { q: "Value of $6^2$:", opts: ["12", "**36**", "64", "100"] },
    { q: "What is $100 \div 5$?", opts: ["10", "**20**", "25", "50"] },
    { q: "Perimeter of square with side 5:", opts: ["10", "15", "**20**", "25"] },
    { q: "What is $1/10$ of 500?", opts: ["5", "**50**", "500", "1"] },
    { q: "Value of $10 - (-3)$ is:", opts: ["7", "10", "**13**", "-13"] },
    { q: "Area of triangle with $b=12, h=2$ is:", opts: ["24", "**12**", "14", "6"] },
    { q: "What is $2^5$?", opts: ["10", "16", "**32**", "64"] },
    { q: "Absolute value of -5:", opts: ["-5", "0", "**5**", "1"] },
    { q: "Solve $x/2 = 8$.", opts: ["4", "**16**", "10", "6"] },
    { q: "The GCD of 9 and 15 is:", opts: ["1", "**3**", "5", "45"] },
    { q: "What is $1/2$ as a decimal?", opts: ["0.2", "**0.5**", "0.25", "0.1"] },
    { q: "The square of 8 is:", opts: ["16", "32", "**64**", "81"] },
    { q: "The derivative of $\ln x$ is:", opts: ["$e^x$", "$x$", "**$1/x$**", "1"] },
    { q: "A straight angle is:", opts: ["$90^\circ$", "**$180^\circ$**", "$270^\circ$", "$360^\circ$"] },
    { q: "Number of sides in a square:", opts: ["3", "**4**", "5", "6"] },
    { q: "If $x - 1 = 9$, $x$ is:", opts: ["8", "**10**", "11", "1"] },
    { q: "What is $6 \times 6$?", opts: ["12", "24", "**36**", "48"] },
    { q: "Value of $1^5$:", opts: ["5", "**1**", "0", "15"] },
    { q: "Radius of circle with $d=2$:", opts: ["2", "**1**", "0.5", "4"] },
    { q: "What is $2^1$?", opts: ["0", "1", "**2**", "4"] },
    { q: "Absolute value of -1:", opts: ["-1", "0", "**1**", "2"] },
    { q: "Solve $10x = 100$:", opts: ["1", "**10**", "100", "0"] },
    { q: "Smallest prime number:", opts: ["1", "**2**", "3", "0"] },
    { q: "What is $3 \times 4$?", opts: ["7", "10", "**12**", "15"] },
    { q: "Area of square with side 1:", opts: ["0", "**1**", "2", "4"] }];
QUESTIONS_DB.Common.Maths["2017"] = [{ q: "If $f(x) = \ln(x^2 - 3x + 2)$, the domain of $f$ is:", opts: ["$x > 2$", "$x < 1$", "**$x < 1$ or $x > 2$**", "$1 < x < 2$"] },
    { q: "The value of $\lim_{x \to \infty} \frac{3x^2 - 5x}{x^2 + 1}$ is:", opts: ["0", "5", "**3**", "$\infty$"] },
    { q: "The derivative of $f(x) = \sin(e^x)$ is:", opts: ["$\cos(e^x)$", "$e^x\sin(e^x)$", "**$e^x\cos(e^x)$**", "$-e^x\cos(e^x)$"] },
    { q: "Find the area under $y = e^x$ from $x=0$ to $x=\ln 2$.", opts: ["2", "$\ln 2$", "**1**", "$e-1$"] },
    { q: "What is the modulus of $z = \frac{1+i}{1-i}$?", opts: ["0", "$\sqrt{2}$", "**1**", "2"] },
    { q: "The distance from point $(1, 2, 3)$ to the plane $x=0$ is:", opts: ["$\sqrt{14}$", "3", "2", "**1**"] },
    { q: "If $\vec{a} \cdot \vec{b} = 0$, the angle between the vectors is:", opts: ["$0^\circ$", "$45^\circ$", "**$90^\circ$**", "$180^\circ$"] },
    { q: "The second derivative of $f(x) = \ln x$ is:", opts: ["$1/x$", "$1/x^2$", "**$-1/x^2$**", "$\ln^2 x$"] },
    { q: "The sum of the series $\sum_{n=1}^{\infty} \frac{3}{10^n}$ is:", opts: ["0.3", "3", "**1/3**", "1/10"] },
    { q: "What is the slope of $x^2 + y^2 = 25$ at $(4, -3)$?", opts: ["-4/3", "-3/4", "**4/3**", "3/4"] },
    { q: "The focus of $x^2 = 12y$ is:", opts: ["(3, 0)", "**(0, 3)**", "(0, -3)", "(6, 0)"] },
    { q: "If $\det(A) = 5$, what is $\det(A^{-1})$?", opts: ["-5", "0", "**1/5**", "5"] },
    { q: "What is the value of $\binom{5}{2} + \binom{5}{3}$?", opts: ["10", "15", "**20**", "25"] },
    { q: "The integral $\int \tan x dx$ is:", opts: ["$\sec^2 x + C$", "**$\ln|\sec x| + C$**", "$-\ln|\sin x| + C$", "$\sec x + C$"] },
    { q: "Find the argument of $z = -i$.", opts: ["$0$", "$\pi/2$", "$\pi$", "**$3\pi/2$**"] },
    { q: "The mean of five numbers is 10. If their sum is $x$, then $x$ is:", opts: ["2", "5", "**50**", "100"] },
    { q: "What is $i^{403}$?", opts: ["1", "-1", "$i$", "**$-i$**"] },
    { q: "The range of $f(x) = e^{-x}$ is:", opts: ["All reals", "$y \geq 0$", "**$y > 0$**", "$y < 0$"] },
    { q: "The derivative of $f(x) = \cos^2 x$ is:", opts: ["$2\cos x$", "$-2\sin x$", "**$-\sin 2x$**", "$\sin 2x$"] },
    { q: "If $\log_x 64 = 3$, then $x$ is:", opts: ["2", "**4**", "8", "16"] },
    { q: "The volume of a sphere with radius 3 is:", opts: ["$9\pi$", "$12\pi$", "$27\pi$", "**$36\pi$**"] },
    { q: "Find the midpoint of $(-1, 5)$ and $(7, 3)$.", opts: ["(4, 4)", "**(3, 4)**", "(6, 8)", "(3, 8)"] },
    { q: "What is $\sin(300^\circ)$?", opts: ["1/2", "-1/2", "$\sqrt{3}/2$", "**$-\sqrt{3}/2$**"] },
    { q: "The vertical asymptote of $y = \frac{x}{x+4}$ is:", opts: ["$x=0$", "$y=1$", "**$x=-4$**", "$x=4$"] },
    { q: "The derivative of $f(x) = \frac{1}{x+1}$ is:", opts: ["$\ln(x+1)$", "$\frac{1}{(x+1)^2}$", "**$\frac{-1}{(x+1)^2}$**", "$-1$"] },
    { q: "If $P(A) = 0.3$ and $P(B) = 0.4$ (independent), $P(A \cap B)$ is:", opts: ["0.7", "0.1", "**0.12**", "0.5"] },
    { q: "What is $\log_{10} 1000$?", opts: ["2", "**3**", "10", "100"] },
    { q: "The perimeter of a circle with $r=3.5$ is ($\pi = 22/7$):", opts: ["11", "**22**", "44", "38.5"] },
    { q: "The value of $\int_1^e \frac{1}{x} dx$ is:", opts: ["$e$", "$0$", "**1**", "$\ln 2$"] },
    { q: "Find $x$: $x^2 - 16 = 0$.", opts: ["4", "-4", "**\pm 4**", "16"] },
    { q: "The median of {4, 1, 7, 9, 3} is:", opts: ["7", "1", "**4**", "5"] },
    { q: "What is $\cos(180^\circ)$?", opts: ["0", "1", "**-1**", "Undefined"] },
    { q: "The derivative of $f(x) = x^3$ at $x=2$ is:", opts: ["4", "8", "**12**", "6"] },
    { q: "If $A = \begin{pmatrix} 2 & 0 \\ 0 & 2 \end{pmatrix}$, then $A^2$ is:", opts: ["$\begin{pmatrix} 4 & 0 \\ 0 & 4 \end{pmatrix}$", "**$\begin{pmatrix} 4 & 0 \\ 0 & 4 \end{pmatrix}$**", "$\begin{pmatrix} 2 & 0 \\ 0 & 2 \end{pmatrix}$", "$\begin{pmatrix} 8 & 0 \\ 0 & 8 \end{pmatrix}$"] },
    { q: "What is $5! / 4!$?", opts: ["1", "4", "**5**", "20"] },
    { q: "The mode of {1, 1, 2, 3, 3, 3, 4} is:", opts: ["1", "2", "**3**", "4"] },
    { q: "Solve $2^x = 1/2$.", opts: ["1", "0", "**-1**", "2"] },
    { q: "The area of a square with perimeter 12 is:", opts: ["144", "12", "**9**", "36"] },
    { q: "What is $i^2$?", opts: ["1", "**-1**", "$i$", "0"] },
    { q: "The distance from $(0,0)$ to $(3,4)$ is:", opts: ["7", "1", "**5**", "25"] },
    { q: "If $\cos \theta = 0$, then $\sin \theta$ could be:", opts: ["0", "1/2", "**1**", "$\sqrt{3}/2$"] },
    { q: "The derivative of $x^2 + 5$ is:", opts: ["$x$", "$2x+5$", "**$2x$**", "2"] },
    { q: "Find the range of $f(x) = -x^2$.", opts: ["All reals", "$y \geq 0$", "**$y \leq 0$**", "$y > 0$"] },
    { q: "What is $10\%$ of 80?", opts: ["4", "**8**", "10", "16"] },
    { q: "The value of $\log_3 81$ is:", opts: ["3", "**4**", "9", "27"] },
    { q: "A triangle with sides 5, 12, 13 is:", opts: ["Isosceles", "**Right**", "Equilateral", "Acute"] },
    { q: "What is $\int 2x dx$?", opts: ["$2$", "$x^2$", "**$x^2 + C$**", "$2x^2 + C$"] },
    { q: "The determinant of $\begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$ is:", opts: ["10", "2", "**-2**", "-10"] },
    { q: "Find $x$: $3x - 9 = 0$.", opts: ["1", "2", "**3**", "9"] },
    { q: "The sum of $1/4 + 1/4$ is:", opts: ["1/8", "1/2", "**1/2**", "2/8"] },
    { q: "The surface area of a sphere with $r=2$ is:", opts: ["$4\pi$", "$8\pi$", "**$16\pi$**", "$32\pi$"] },
    { q: "The limit of $1/x$ as $x \to 0^+$ is:", opts: ["0", "1", "**\infty**", "-1"] },
    { q: "If $A = \{a, b\}$, how many subsets?", opts: ["1", "2", "**4**", "0"] },
    { q: "What is $2^0 + 2^1 + 2^2$?", opts: ["6", "**7**", "8", "4"] },
    { q: "The slope of $y = 5x$ is:", opts: ["0", "1", "**5**", "x"] },
    { q: "What is $\sqrt{100}$?", opts: ["1", "5", "**10**", "20"] },
    { q: "Perimeter of a circle with $d=14$ ($\pi=22/7$):", opts: ["22", "**44**", "88", "154"] },
    { q: "Mean of 1, 2, 3, 4, 5:", opts: ["2", "**3**", "4", "5"] },
    { q: "Derivative of $\sin x$ is:", opts: ["$-\cos x$", "$\sin x$", "**$\cos x$**", "1"] },
    { q: "What is $2^4$?", opts: ["8", "**16**", "32", "64"] },
    { q: "Value of $|-10| + 10$ is:", opts: ["0", "10", "**20**", "100"] },
    { q: "Solve $x/5 = 4$.", opts: ["1", "**20**", "9", "0.8"] },
    { q: "GCD of 20 and 30 is:", opts: ["5", "**10**", "20", "60"] },
    { q: "What is $1/5$ as a decimal?", opts: ["0.1", "**0.2**", "0.5", "0.05"] },
    { q: "The interior angle of a square is:", opts: ["$45^\circ$", "$60^\circ$", "**$90^\circ$**", "$180^\circ$"] },
    { q: "What is $\cos(0)$?", opts: ["0", "**1**", "-1", "0.5"] },
    { q: "If $f(x) = x^3$, $f'(1)$ is:", opts: ["1", "**3**", "2", "0"] },
    { q: "Distance from (0,0) to (0,10) is:", opts: ["0", "5", "**10**", "100"] },
    { q: "What is $10^2$?", opts: ["20", "**100**", "1000", "10"] },
    { q: "Volume of a cube with $s=2$ is:", opts: ["4", "6", "**8**", "12"] },
    { q: "Find $x$: $2x + 2 = 10$.", opts: ["2", "**4**", "6", "8"] },
    { q: "Square root of 25 is:", opts: ["2.5", "**5**", "10", "12.5"] },
    { q: "What is $1/2$ of 100?", opts: ["25", "40", "**50**", "60"] },
    { q: "Complement of $40^\circ$ is:", opts: ["$140^\circ$", "$90^\circ$", "**$50^\circ$**", "$60^\circ$"] },
    { q: "Sides in a triangle:", opts: ["1", "2", "**3**", "4"] },
    { q: "If $x - 1 = 0$, $x$ is:", opts: ["-1", "0", "**1**", "2"] },
    { q: "Product of 5 and 6:", opts: ["11", "25", "**30**", "36"] },
    { q: "Value of $\pi$ approx:", opts: ["2.14", "3.00", "**3.14**", "3.16"] },
    { q: "Diameter is 2, radius is:", opts: ["2", "**1**", "0.5", "4"] },
    { q: "What is $2^3$?", opts: ["6", "**8**", "9", "12"] },
    { q: "Value of $|-2|$ is:", opts: ["-2", "0", "**2**", "1"] },
    { q: "Solve $3x = 9$:", opts: ["2", "**3**", "4", "9"] },
    { q: "Smallest prime is:", opts: ["1", "**2**", "3", "0"] },
    { q: "What is $10 \times 4$?", opts: ["14", "30", "**40**", "50"] },
    { q: "Area of square with side 2:", opts: ["2", "**4**", "6", "8"] },
    { q: "What is $\sin(0)$?", opts: ["1", "**0**", "-1", "0.5"] },
    { q: "If $x + x = 4$, $x$ is:", opts: ["1", "**2**", "3", "4"] },
    { q: "Value of $2^2$:", opts: ["2", "**4**", "6", "8"] },
    { q: "What is $10 \div 2$?", opts: ["2", "**5**", "8", "10"] },
    { q: "Perimeter of square with side 1:", opts: ["1", "2", "3", "**4**"] },
    { q: "What is $1/10$ of 100?", opts: ["1", "**10**", "100", "0.1"] },
    { q: "Value of $5 - (-2)$:", opts: ["3", "5", "**7**", "-7"] },
    { q: "Area of triangle $b=4, h=2$:", opts: ["8", "**4**", "6", "2"] },
    { q: "What is $3^1$?", opts: ["1", "**3**", "6", "9"] },
    { q: "Absolute value of 0:", opts: ["1", "-1", "**0**", "Inf"] },
    { q: "Solve $x + 1 = 5$:", opts: ["3", "**4**", "5", "6"] },
    { q: "Smallest even prime:", opts: ["0", "1", "**2**", "4"] },
    { q: "What is $5 \times 5$?", opts: ["10", "20", "**25**", "30"] },
    { q: "Area of rectangle $l=2, w=3$:", opts: ["5", "**6**", "10", "12"] },
    { q: "What is $1/4$ as a percentage?", opts: ["4%", "10%", "**25%**", "40%"] }];
