// 2017 Physics First Round Model Exam - Full 60 Questions (Complete)
if (typeof QUESTIONS_DB === 'undefined') {
    var QUESTIONS_DB = { ModelExams: { "Natural": {}, "Social": {} } };
}

const physicsData_2017 = [
    { "q": "Which of the following is a vector quantity?", "opts": ["Mass", "Time", "**Force**", "Temperature"] },
    { "q": "The rate of change of momentum is equal to:", "opts": ["Work", "Velocity", "**Net Force**", "Acceleration"] },
    { "q": "A car starts from rest and accelerates uniformly at 2 m/s² for 10 seconds. What is its final velocity?", "opts": ["10 m/s", "**20 m/s**", "5 m/s", "40 m/s"] },
    { "q": "According to Newton's Second Law, if the net force acting on an object is doubled, its acceleration will:", "opts": ["Be halved", "Stay the same", "**Be doubled**", "Be quadrupled"] },
    { "q": "What is the work done in lifting a 5 kg object to a height of 2 meters? (Take g = 10 m/s²)", "opts": ["10 J", "50 J", "**100 J**", "200 J"] },
    { "q": "Which type of energy is stored in a compressed spring?", "opts": ["Kinetic energy", "**Elastic potential energy**", "Chemical energy", "Thermal energy"] },
    { "q": "The period of a simple pendulum depends primarily on its:", "opts": ["Mass", "**Length**", "Amplitude", "Density"] },
    { "q": "Which law states that for every action, there is an equal and opposite reaction?", "opts": ["Newton's 1st Law", "Newton's 2nd Law", "**Newton's 3rd Law**", "Law of Gravitation"] },
    { "q": "The unit of electric power is:", "opts": ["Joule", "Ampere", "Volt", "**Watt**"] },
    { "q": "In a series circuit, which quantity remains the same across all resistors?", "opts": ["Voltage", "**Current**", "Resistance", "Power"] },
    { "q": "What is the equivalent resistance of two 4Ω resistors connected in parallel?", "opts": ["8Ω", "4Ω", "**2Ω**", "1Ω"] },
    { "q": "The speed of light in a vacuum is approximately:", "opts": ["3 x 10^6 m/s", "**3 x 10^8 m/s**", "3 x 10^10 m/s", "1.5 x 10^8 m/s"] },
    { "q": "Which mirror is commonly used as a rear-view mirror in vehicles?", "opts": ["Plane mirror", "Concave mirror", "**Convex mirror**", "Cylindrical mirror"] },
    { "q": "The process by which heat travels through a vacuum is:", "opts": ["Conduction", "Convection", "**Radiation**", "Evaporation"] },
    { "q": "What happens to the pressure of a gas if its volume is decreased at constant temperature?", "opts": ["Decreases", "**Increases**", "Remains constant", "Becomes zero"] },
    { "q": "The measure of the average kinetic energy of the particles in a substance is called:", "opts": ["Heat", "**Temperature**", "Internal energy", "Specific heat capacity"] },
    { "q": "Sound waves are examples of:", "opts": ["Transverse waves", "**Longitudinal waves**", "Electromagnetic waves", "Matter waves"] },
    { "q": "Which part of the electromagnetic spectrum has the highest frequency?", "opts": ["Radio waves", "Infrared", "Visible light", "**Gamma rays**"] },
    { "q": "A convex lens is also known as a:", "opts": ["Diverging lens", "**Converging lens**", "Plane lens", "Bifocal lens"] },
    { "q": "The bending of light as it passes from one medium to another is called:", "opts": ["Reflection", "**Refraction**", "Diffraction", "Interference"] },
    { "q": "What is the momentum of a 2 kg object moving at 5 m/s?", "opts": ["2.5 kg.m/s", "7 kg.m/s", "**10 kg.m/s**", "20 kg.m/s"] },
    { "q": "The force of gravity between two objects depends on their masses and:", "opts": ["Their colors", "The time of day", "**The distance between them**", "Their volumes"] },
    { "q": "Which scientist is famous for the theory of relativity?", "opts": ["Isaac Newton", "**Albert Einstein**", "Galileo Galilei", "Marie Curie"] },
    { "q": "An object that does not allow light to pass through it is:", "opts": ["Transparent", "Translucent", "**Opaque**", "Reflective"] },
    { "q": "The tendency of an object to resist changes in its state of motion is:", "opts": ["Friction", "Gravity", "**Inertia**", "Weight"] },
    { "q": "What is the frequency of a wave with a period of 0.02 seconds?", "opts": ["20 Hz", "**50 Hz**", "100 Hz", "5 Hz"] },
    { "q": "The escape velocity from Earth's surface is approximately:", "opts": ["7.9 km/s", "**11.2 km/s**", "30 km/s", "42 km/s"] },
    { "q": "Which of the following is the best conductor of electricity?", "opts": ["Rubber", "Glass", "Wood", "**Copper**"] },
    { "q": "The SI unit of magnetic flux density (B) is:", "opts": ["Weber", "**Tesla**", "Henry", "Farad"] },
    { "q": "The half-life of a radioactive substance is the time taken for:", "opts": ["All atoms to decay", "**Half of the atoms to decay**", "The mass to double", "The temperature to drop"] },
    { "q": "The photoelectric effect proves that light behaves as a:", "opts": ["Wave only", "**Particle (Photon)**", "Continuous fluid", "Stationary field"] },
    { "q": "Which law relates the current, voltage, and resistance in a circuit?", "opts": ["Faraday's Law", "Lenz's Law", "**Ohm's Law**", "Pascal's Law"] },
    { "q": "A machine with a mechanical advantage of 5 requires 100 N of input force to lift a load of:", "opts": ["20 N", "100 N", "**500 N**", "1000 N"] },
    { "q": "Which of the following describes a 'Projective Motion'?", "opts": ["Movement in a straight line", "**Movement in a parabolic path under gravity**", "Circular motion at constant speed", "Back and forth motion"] },
    { "q": "The density of water is approximately:", "opts": ["100 kg/m³", "**1000 kg/m³**", "10,000 kg/m³", "1 kg/m³"] },
    { "q": "What is the power of a lens with a focal length of 0.5 meters?", "opts": ["0.5 D", "1.0 D", "**2.0 D**", "5.0 D"] },
    { "q": "Pascal's principle is the basis for the operation of:", "opts": ["Airplanes", "**Hydraulic lifts**", "Electric motors", "Steam engines"] },
    { "q": "Which fundamental force is the weakest?", "opts": ["Strong nuclear force", "Electromagnetic force", "Weak nuclear force", "**Gravitational force**"] },
    { "q": "The torque acting on a body is the product of force and:", "opts": ["Mass", "Velocity", "**Lever arm distance**", "Time"] },
    { "q": "What is the charge of an electron?", "opts": ["Positive", "**Negative**", "Neutral", "Variable"] },
    { "q": "A transformer works on the principle of:", "opts": ["Self-induction", "**Mutual induction**", "Thermal expansion", "The Doppler effect"] },
    { "q": "The color of light with the longest wavelength in the visible spectrum is:", "opts": ["Violet", "Blue", "Green", "**Red**"] },
    { "q": "Specific heat capacity is the amount of heat required to raise the temperature of 1 kg of a substance by:", "opts": ["10°C", "**1°C (or 1 K)**", "100°C", "0.1°C"] },
    { "q": "Archimedes' principle states that the buoyant force is equal to the:", "opts": ["Mass of the object", "Volume of the object", "**Weight of the displaced fluid**", "Density of the fluid"] },
    { "q": "The unit of magnetic field strength is the Gauss. How many Gauss are in one Tesla?", "opts": ["100", "1,000", "**10,000**", "1,000,000"] },
    { "q": "In a nuclear reactor, control rods are used to:", "opts": ["Produce fuel", "**Absorb neutrons**", "Cool the core", "Speed up the reaction"] },
    { "q": "Which type of wave requires a medium to travel?", "opts": ["Radio waves", "X-rays", "**Sound waves**", "Light waves"] },
    { "q": "What is the net force acting on an object moving at a constant velocity?", "opts": ["Equal to its weight", "Increasing", "**Zero**", "Constant but non-zero"] },
    { "q": "If the distance between two charges is doubled, the electrostatic force between them:", "opts": ["Doubles", "Stays the same", "Decreases to 1/2", "**Decreases to 1/4**"] },
    { "q": "Which component in a circuit stores energy in an electric field?", "opts": ["Resistor", "**Capacitor**", "Inductor", "Switch"] },
    { "q": "The process of combining two light nuclei to form a heavier nucleus is:", "opts": ["Fission", "**Fusion**", "Radioactive decay", "Ionization"] },
    { "q": "What is the velocity of a body at the maximum height of its upward projectile motion?", "opts": ["Maximum", "9.8 m/s", "**0 m/s (vertical component)**", "Initial velocity"] },
    { "q": "Which instrument is used to measure atmospheric pressure?", "opts": ["Thermometer", "Hydrometer", "**Barometer**", "Anemometer"] },
    { "q": "The 'Doppler Effect' refers to changes in the observed frequency of a wave due to:", "opts": ["Reflection", "Refraction", "**Relative motion between source and observer**", "Absorption"] },
    { "q": "A device that converts mechanical energy into electrical energy is a:", "opts": ["Motor", "**Generator**", "Battery", "Solar cell"] },
    { "q": "In the equation E=mc², 'c' represents:", "opts": ["Capacitance", "Charge", "**The speed of light**", "Center of mass"] },
    { "q": "Which mirror can form both real and virtual images?", "opts": ["Plane mirror", "Convex mirror", "**Concave mirror**", "All of them"] },
    { "q": "What is the moment of inertia of a spinning object with a radius of 5m and mass 6kg moving at 5m/s, given its total K.E is 100J?", "opts": ["2 kg.m²", "**0.5 kg.m²**", "3.5 kg.m²", "9 kg.m²"] },
    { "q": "Which is NOT true about electric and magnetic fields?", "opts": ["Electric field is produced by static charges", "Electric field lines are discontinuous", "No electric field lines exist inside a charged body", "**The unit of electric field is coulomb**"] },
    { "q": "Which sound wave characteristic can damage our eardrum if it is too high?", "opts": ["Frequency", "Wavelength", "Period", "**Intensity**"] }
];

// ዳታውን መመደብ
QUESTIONS_DB.ModelExams.Natural["Physics"] = { "Model_2017_Round_1": physicsData_2017 };
